// @r1ck404/fast-es-module-lexer: drop-in replacement for es-module-lexer 1.7.0
// (same exports: ImportType, init, initSync, parse; same results, same
// errors). One module (each module costs Node ~0.5 ms to load): this code,
// then the wasm (build.mjs writes it at the end, base64).
//
// build.mjs also writes browser.mjs, the module bundlers take for browsers
// (the "browser" export condition): this code with BROWSER = true, without
// the Node.js paths, and the wasm as a denser text (see decode) instead of
// base64: ~25% smaller after gzip, but decoding it costs a few tenths of a
// millisecond that base64 in Node does not.
//
// The lexer is a port of es-module-lexer's lexer.c (rust/src/lib.rs) that
// skips over code with SIMD instead of walking it char by char. Sources go
// into wasm memory by the fastest means the engine has: Node's Buffer
// latin1Write/ucs2Write (memcpy), a wasm loop over the JS-string builtins in
// other V8 hosts (Chromium), TextEncoder.encodeInto elsewhere (Firefox and
// Safari); either way they end up as one byte per UTF-16 code unit, which is
// all the lexer distinguishes. Results come back as one int array instead
// of a wasm call per field, and import specifiers without escapes are
// sliced instead of eval'd (eval of a plain quoted literal is its body).

                                                                         

/** true in browser.mjs (see above) */
const BROWSER          = false;

// the globals of Deno and Bun (only tested for)
                                          

/** exports of rust/src/lib.rs */
                        
                             
                                                                                                                                                                              
                          
                                          
                         
                              
                               
                                             
 
/** copy8(string, from, to, base, mask, useCharCodeAt): the JS-string builtins copy loop */
                                                                                                    
                                                                                                                                                          

/** es-module-lexer's ImportType enum: name -> number and number -> name */
export const ImportType                                           = {};
"Static Dynamic ImportMeta StaticSourcePhase DynamicSourcePhase StaticDeferPhase DynamicDeferPhase"
  .split(" ")
  .forEach((k, i) => (ImportType[(ImportType[k] = i + 1)] = k));

const b64 = (s        )                          =>
  !BROWSER && typeof Buffer === "function" ? Buffer.from(s, "base64") : Uint8Array.from(atob(s), (c) => c.charCodeAt(0));

// browser.mjs: the modules are text (see build.mjs): the first 64 characters
// say which bytes are one character, the others are two; a small wasm
// module (base64) turns the text back into bytes.
let decoder                                ;
let enc                         ;
function decode(text        )                          {
  decoder ||= new WebAssembly.Module(b64(DECODER()));
  const d = new WebAssembly.Instance(decoder).exports                                                              ;
  // (the text at 1024, in as many pages as it needs)
  d.m.grow((text.length + 1024) >> 16);
  const n = d.d((enc ||= new TextEncoder()).encodeInto(text, new Uint8Array(d.m.buffer, 1024)).written);
  return new Uint8Array(d.m.buffer, 1024, n);
}
const bytesOf = (s        )                          => (BROWSER ? decode(s) : b64(s));

let W                      = null;
let I32            ;
let H = 0; // header index into I32
let srcPtr = 0; // source buffer in wasm memory
let cap = -1; // capacity of the source buffer in bytes
let srcView            ; // Uint8Array over the source buffer
// (latin1Write / ucs2Write: undocumented, in every Node version)
let NB                                                                                                                                           ; // Node: Buffer over wasm memory
let C8               = null; // V8: copy8(string, from, to, base, 255, cca) (wasm JS-string builtins)
// how sources get into wasm memory: 0 Node Buffer, 1 V8 builtins, 2 encodeInto
let mode = 2;

// Node.js: Buffer's latin1Write / ucs2Write put a string into wasm memory at
// memcpy speed (TextEncoder.encodeInto is ~1-2 ns per char). Only the real
// Node: not a Buffer polyfill in a browser, not Deno's or Bun's Node APIs
// (their own paths are faster there). (Not `navigator`: in Node its first
// use builds it, ~0.1 ms.)
const isNode = ()          =>
  typeof process === "object" &&
  typeof process?.versions?.node === "string" &&
  typeof Deno === "undefined" &&
  typeof Bun === "undefined" &&
  typeof Buffer === "function" &&
  typeof (Buffer.prototype       ).latin1Write === "function" &&
  typeof (Buffer.prototype       ).ucs2Write === "function";
// Which of the two to use: a string's one-byte representation means all its
// chars are <= 0xff (then latin1Write is exact). v8.isStringOneByteRepresentation
// (Node >= 22.15) tells in O(1), but loading node:v8 costs ~1ms, so it is
// only fetched once a few hundred KB went through. Until then a regexp that
// cannot match a one-byte string (V8 answers that in O(1) as well; on a
// two-byte string it stops at the first char above 0xff).
let isOneByte                                  = null;
let nodeChars = 0;
function loadIsOneByte()       {
  isOneByte = (s) => !NON_LATIN1.test(s);
  try {
    const v8      = process.getBuiltinModule("node:v8");
    if (typeof v8.isStringOneByteRepresentation === "function") isOneByte = v8.isStringOneByteRepresentation;
  } catch {}
}
const NON_LATIN1 = /[^\x00-\xff]/;

// V8 (Chromium, Deno): a wasm loop over the JS-string builtins copies a
// string 1.5-4x faster than TextEncoder.encodeInto (a scalar UTF-8 encoder in
// Blink). Firefox and Safari have a fast encodeInto and slow charCodeAt
// builtins, so they keep encodeInto.
function copyModule()               {
  try {
    // V8 only (its message for property reads of null)
    try {
      JSON.parse("null").x;
    } catch (e) {
      if (!/^Cannot read propert/.test(e.message)) return null;
    }
    // (js-string builtins: the options argument is newer than lib.dom's types)
    const m = new (WebAssembly.Module       )(bytesOf(COPY8()), { builtins: ["js-string"] })                      ;
    // without builtin support the import would have to come from JS (slow)
    if (WebAssembly.Module.imports(m).some((i) => i.module !== "env")) return null;
    return new WebAssembly.Instance(m, { env: { memory: W.memory } }).exports.copy8         ;
  } catch {
    return null;
  }
}

// copy8 reads strings with intoCharCodeArray until V8 has had the time to
// optimize it (~0.5M chars), then with charCodeAt (fastest, but ~10x slower
// than encodeInto in V8's baseline code; see build.mjs)
let c8cca = 0;
let c8chars = 0;

function setup(instance                      )       {
  W = instance.exports                           ;
  H = W.HDR.value >> 2;
  mode = !BROWSER && isNode() ? 0 : (C8 = copyModule()) ? 1 : 2;
  refresh();
}

function refresh()       {
  const b = W.memory.buffer;
  I32 = new Int32Array(b);
  if (!BROWSER && mode === 0) NB = Buffer.from(b)             ;
  if (cap >= 0) srcView = new Uint8Array(b, srcPtr, cap);
}

/** make room for n bytes of source (and views on current memory) */
function grow(n        )       {
  srcPtr = W.buf(n);
  cap = new Int32Array(W.memory.buffer)[H + 6];
  refresh();
}

const bytes = bytesOf(WASM());
/**
 * Wait for init to resolve before calling `parse`.
 */
export const init                = WebAssembly.instantiate(bytes).then((r) => {
  W || setup(r.instance);
});

export const initSync = ()       => {
  W || setup(new WebAssembly.Instance(new WebAssembly.Module(bytes)));
};

// es-module-lexer decodes quoted names with `(0, eval)(literal)`
function evalName(str        )                     {
  try {
    return (0, eval)(str);
  } catch (e) {}
}

// es-module-lexer's glue for a source that is not a string: `length + 1`
// units of memory, filled by charCodeAt (the same TypeError for null,
// undefined and objects without charCodeAt, the same RangeError for a
// negative length), lexed as `length` chars.
function fromObject(A     )         {
  const u = new Uint16Array(A.length + 1);
  for (let i = 0, n = A.length; i < n; ) u[i] = A.charCodeAt(i++);
  let s = "";
  for (let i = 0; i < u.length - 1; i += 4096) s += String.fromCharCode.apply(null, u.subarray(i, Math.min(i + 4096, u.length - 1)));
  return s;
}

/**
 * Outputs the list of exports and locations of import specifiers,
 * including dynamic import and import meta handling.
 *
 * @param source Source code to parser
 * @param name Optional sourcename
 * @returns Tuple contaning imports list and exports list.
 */
                                                                  
export function parse(source     , name = "@")                                     {
  if (!W) return init.then(() => parse(source));
  if (typeof source !== "string") source = fromObject(source);

  const len = source.length;
  // bytes per UTF-16 unit: UTF-16 (Node, two-byte strings), bytes (V8), UTF-8
  const need = mode === 1 ? len : !BROWSER && mode === 0 ? 2 * len : 3 * len;
  // (a memory.grow, also in a parse that trapped, detaches the old buffer:
  // its views read as empty)
  if (need > cap || I32.length === 0) grow(need);

  let status = -1;
  if (!BROWSER && mode === 0) {
    if (isOneByte === null && (nodeChars += len) > 262144) loadIsOneByte();
    if (isOneByte !== null ? isOneByte(source) : !NON_LATIN1.test(source)) {
      NB.latin1Write(source, srcPtr, len);
      status = W.parse8(len);
    } else {
      NB.ucs2Write(source, srcPtr, len * 2);
      status = W.parse16(len);
    }
  } else if (mode === 1) {
    C8(source, 0, len, srcPtr, 255, c8cca);
    if (c8cca === 0 && (c8chars += len) > 1e6) c8cca = 1;
    status = W.parse8(len);
  } else {
    if (len <= 128) {
      // a JS copy beats the fixed cost of encodeInto for short strings
      // (Latin-1 bytes are as good as the reduced form, see parse16)
      let any = 0;
      for (let i = 0; i < len; i++) any |= srcView[i] = source.charCodeAt(i);
      if (any < 256) status = W.parse8(len);
    }
    if (status < 0) {
      // UTF-8 into wasm memory; the wasm side reduces it to one byte per
      // UTF-16 code unit (a no-op for ASCII) so positions are UTF-16 indices
      const written = (enc ||= new TextEncoder()).encodeInto(source, srcView).written;
      status = written === len ? W.parse8(len) : W.parse_utf8(len, written);
    }
  }
  if (I32.length === 0) refresh();

  if (status !== 0) {
    const e = I32[H + 1];
    throw Object.assign(
      new Error(`Parse error ${name}:${source.slice(0, e).split("\n").length}:${e - source.lastIndexOf("\n", e - 1)}`),
      { idx: e },
    );
  }

  // the records in the order they were made: an import is 9 ints (kind 1, or
  // 3 if dropped), an export 5 (kind 2)
  const I = I32;
  const end = I[H + 5] >> 2;
  const imports                    = [];
  const exports                    = [];
  for (let o = I[H + 4] >> 2; o < end; ) {
    const kind = I[o];
    if (kind !== 2) {
      if (kind === 1) {
        const s = I[o + 1], e = I[o + 2], ss = I[o + 3], se = I[o + 4], d = I[o + 5], a = I[o + 6], t = I[o + 7], f = I[o + 8];
        // (static: s..e is the body of the literal; dynamic: the literal)
        let n                    ;
        if (f === 1) n = d === -1 ? source.slice(s, e) : source.slice(s + 1, e - 1);
        else if (f !== 0) n = evalName(d === -1 ? source.slice(s - 1, e + 1) : source.slice(s, e));
        imports.push({ n, t, s, e, ss, se, d, a });
      }
      o += 9;
      continue;
    }
    const s = I[o + 1], e = I[o + 2], ls = I[o + 3], le = I[o + 4];
    o += 5;
    let n = source.slice(s, e);
    let c = source.charCodeAt(s);
    if ((c === 34 || c === 39) && s < e) n = evalName(n);
    let ln                    ;
    if (ls >= 0) {
      ln = source.slice(ls, le);
      c = source.charCodeAt(ls);
      if ((c === 34 || c === 39) && ls < le) ln = evalName(ln);
    }
    exports.push({ s, e, ls, le, n, ln });
  }
  return [imports, exports, !!I[H + 2], !!I[H + 3]]               ;
}

// ---- test hooks (not exported: test/hooks.mjs loads this module with an
// export of them added)

/** force how sources are copied ("node" | "node-re" | "v8" | "v8-into" | "encode") */
function __mode(m        )       {
  initSync();
  if (m === "node" && !BROWSER && isNode()) (mode = 0), loadIsOneByte();
  else if (m === "node-re" && !BROWSER && isNode()) (mode = 0), (isOneByte = (s) => !NON_LATIN1.test(s));
  else if ((m === "v8" || m === "v8-into") && (C8 ||= copyModule())) (mode = 1), (c8cca = m === "v8" ? 1 : 0), (c8chars = -Infinity);
  else if (m === "encode") mode = 2;
  else throw new Error("mode not available: " + m);
  refresh();
}
/** how sources are copied now, and how many reads the lexer made outside a source so far */
function __stats()                                    {
  initSync();
  return { mode: ["node", "v8", "encode"][mode], outside: I32[H + 7] };
}

// generated by build.mjs (everything below this line)
/** the lexer (rust/), base64 (browser.mjs: as text, see build.mjs) */
function WASM()         {
  return "AGFzbQEAAAABOQlgAn9/AX9gAX8AYAF/AX9gBX9/f39/AGAEf39+fwF/YAN/f38Bf2ADf39/AGACf38AYAR/f39/AAMfHgIDAwYEAAUABwABBAAIAQEAAAUAAQEAAAECAgICAAUDAQADBh0EfwFBgIAEC38AQeCBBQt/AEGcggoLfwBBoIIKCwc2BgZtZW1vcnkCAANIRFIDAQNidWYAGgdwYXJzZTE2ABsGcGFyc2U4ABwKcGFyc2VfdXRmOAAdDAEFCrZ+HkIBAn8CQCAAPwAiAUEQdCICTQ0AIAFBA3ZB/z9xIgEgACACa0H//wNqQRB2IgAgACABSRtAAEF/Rw0AAAs/AEEQdAuCAQECfyAAKAI4IgVBFGoiBiAAKAJATQRAIAAoAjwgBkkEQCAAIAYQADYCPAsgBSAENgIQIAUgAzYCDCAFIAI2AgggBSABNgIEIAVBAjYCACAAIAY2AjggAEEBOgBFIAAgBTYCMA8LQfyBBUH8gQUoAgBBAWo2AgBBAC0A/////w8aAAu3AgEEfwJAIAAoAjgiBUEkaiIGIAAoAkBNBEAgACgCPCAGSQRAIAAgBhAANgI8C0ECIQdBfyEIAkACQAJAIARBAmoOAgABAgsgBf0M/v////////8DAAAAAAAAAP0LAhQgBSADNgIQIAUgATYCDCAFIAM2AgggBSACNgIEIAVBATYCACAAIAY2AjggACgCKCEBIAAgBTYCKCAAIAE2AiwMAwtBASEHIANBAWohCAsgBSAHNgIcIAVBfzYCGCAFIAQ2AhQgBSAINgIQIAUgATYCDCAFIAM2AgggBSACNgIEIAVBATYCACAAIAY2AjggBSAEQX9GIgE2AiAgACgCKCECIAAgBTYCKCAAIAI2AiwgAQ0BDwtB/IEFQfyBBSgCAEEBajYCAEEALQD/////DxoACyAAQQE6AEULjQQCAn8BewJAAkAgAUEvRgRAIAAoAhQiAkEBaiEBIAIgACgCEE4NASAAKAIMIgIgAUwEQCACIQEMAgsgACgCCCEDAkADQCABIANq/QAAACIF/QwNDQ0NDQ0NDQ0NDQ0NDQ0N/SMgBf0MCgoKCgoKCgoKCgoKCgoKCv0j/VD9ZCIEDQEgAUEQaiIBIAJIDQALIAIhAQwCCyACIAEgBGhqIgEgASACShshAQwBCyAAKAIUIgNBAmohASAAKAIQIANBAWpMDQAgACgCDCIDIAFMBEAgAyEBDAELIAAoAgghBAJAIAJFBEADQCABIARqIgL9AAAAIgX9DA0NDQ0NDQ0NDQ0NDQ0NDQ39IyAF/QwKCgoKCgoKCgoKCgoKCgoK/SP9UCAF/QwqKioqKioqKioqKioqKioq/SMgAkEBav0AAAD9DC8vLy8vLy8vLy8vLy8vLy/9I/1O/VD9ZCICDQIgAUEQaiIBIANIDQALIAMhAQwCCwNAIAEgBGoiAv0AAAD9DCoqKioqKioqKioqKioqKir9IyACQQFq/QAAAP0MLy8vLy8vLy8vLy8vLy8vL/0j/U79ZCICDQEgAUEQaiIBIANIDQALIAMhAQwBCyADIAEgAmhqIgFMBEAgAyEBDAELIAAgAyABIAEgA0obIgE2AhQgASAEai0AAEEqRw0BIAFBAWohAQsgACABNgIUCwtKAgJ+An8gA61CA4ZCCH0hBQNAIAAgARAFIgMgAiAEiKdB/wFxIgZGBEAgAUEBaiEBIAQgBVIhByAEQgh8IQQgBw0BCwsgAyAGRgsfACAAKAIMIAFJBEAgACABEAwPCyAAKAIIIAFqLQAAC64BAQR/AkAgACAAKAIUIgQQBSIGQeEARwRAIAIhAyABIQUMAQsgACAEQQJqNgIUIABBARAHIQMgACgCFCEFAkACQAJAIANBImsOBgABAQEBAAELIAAgAxAIIAAgACgCFEEBaiIDNgIUDAELIAAgAxAJGiAAKAIUIQMLIABBARAHIQYgACgCFCEECyAEIAVHBEAgACAFIANBfyABIAEgAkYiABtBfyACIAAbEAELIAYLqwMBA38gACgCFCECAkAgAUUEQANAAkACQAJ/AkACfyAAKAIMIgMgAkkEQCAAIAIQDAwBCyAAKAIIIAJqLQAACyIBQS9GBEAgAyACQQFqIgNPDQEgACADEAwMAgsgAUH9/wNxQQlHDQIgAiEDDAMLIAAoAgggA2otAAALIQJBLyEEAkAgAkEqaw4GAAUFBQUABQsgACACQQAQAyAAKAIUIQMMAQsgAUEMRgRAIAIhAwwBCyABQSBGBEAgAiEDDAELIAIhAyABQaABRg0AIAEhBAwDCyAAIANBAWoiAjYCFCABIQQgAyAAKAIQSA0ADAILAAsDQCAAAn8CfyAAKAIMIgMgAk8EQCAAKAIIIAJqLQAADAELIAAgAhAMCyIBQS9HBEAgAUEJSQRAIAEPCyACIAFBDkkNARogAiABQYABckGgAUYNARogAQ8LQS8hBAJAAn8gAyACQQFqIgJPBEAgACgCCCACai0AAAwBCyAAIAIQDAsiAkEqaw4GAAMDAwMAAwsgACACQQEQAyAAKAIUCyIDQQFqIgI2AhQgASEEIAMgACgCEEgNAAsLIAQL0QICBn8CewJAAkACQCAAKAIUIgIgACgCECIHSARAIAAoAgghBiAAKAIMIQQgAf0PIQkDQCACQQFqIgIgBE4NAgNAIAIgBmr9AAAAIgj9DA0NDQ0NDQ0NDQ0NDQ0NDQ39IyAI/QwKCgoKCgoKCgoKCgoKCgoK/SP9UCAI/QxcXFxcXFxcXFxcXFxcXFxc/SMgCCAJ/SP9UP1Q/WQiA0UEQCACQRBqIgIgBEgNAQwECwsgAiADaGoiAyAETg0CIAAgBCADIAMgBEobIgU2AhQgASAFIAZqLQAAIgNGDQQgA0HcAEcNAyAAIAVBAWoiAjYCFAJAIAAgAhAFQQ1HDQAgACAFQQJqIgMQBUEKRw0AIAAgAzYCFCADIQILIAIgB0gNAAsLIAJBAWohBAsgACAENgIUCyAAQQE6AEggACAAKAIUNgIcIAAgACgCEEEBajYCFAsLgAEBBH8gACgCFEEBaiECIAAoAgghBCAAKAIMIQUCQANAAkAgAUGAAU8EQEGgASEDIAFBoAFHDQEMAwsgASIDLQCAgARBCHENAgsgACACNgIUAn8gAiAFSwRAIAAgAhAMDAELIAIgBGotAAALIQEgAkEBaiECIAENAAtBACEDCyADC/0DAgV/AXsCQAJAAkACQCAAKAIUIgEgACgCECIFSARAIAAoAgghBCAAKAIMIQIDQCABQQFqIgEgAk4NBANAIAEgBGoiA/0AAAAiBv0MXFxcXFxcXFxcXFxcXFxcXP0jIAb9DGBgYGBgYGBgYGBgYGBgYGD9I/1QIAb9DCQkJCQkJCQkJCQkJCQkJCT9IyADQQFq/QAAAP0Me3t7e3t7e3t7e3t7e3t7e/0j/U79UP1kIgNFBEAgAUEQaiIBIAJIDQEMBgsLIAEgA2hqIgEgAk4NBCAAIAIgASABIAJKGyIBNgIUIAEgBGotAAAiA0HgAEYNAiADQSRGBEAgACABQQFqIgI2AhQgACgCICIBQYCAAU8EQAwHCyABQQQ6AOCBBCABQQJ0IAI2ApyCBiAAIAFBAWo2AiAMBAsgACABQQFqIgE2AhQgASAFSA0ACwsgAUEBaiECDAILAkAgACgCICIBQQBKBEAgACABQQFrNgIgDAELIABBAToASCAAIAAoAhQ2AhwgACAAKAIQQQFqNgIUCyAALQBIDQAgACgCICIBQYCAAUkEQCABLQDggQRBA0YNAQsMAgsPCyAAIAI2AhQgAEEBOgBIIAAgACgCFDYCHCAAIAAoAhBBAWo2AhQPCyAAQQE6AEggACAAKAIUNgIcIAAgACgCEEEBajYCFAtnAQJ/AkAgASADayIFQQFqIgFBAXRBv41/Sw0AAkAgACgCDCABTwRAIAAoAgggAWopAABCf0HAACADQQN0a62IgyACUg0CIAENAUEBDwsgACABIAIgAxAERQ0BCyAAIAUQFyEECyAEC9sDAQd/QfyBBUH8gQUoAgBBAWo2AgACQAJAAkACQCAAKQMAIAFBAXQiAkHA8gBqrUICfFoEQCACQb+Nf00EQCACIAAoAgxBAXQiCGtBAmshBCAAKAI0IgcgACgCOCIFTw0FIARBAnYhACAHIQICQAJAA0ACQAJAIAIoAgAiBkECRgRAQQUhASAAQQVPDQEgAEEERw0EQRQhAEECIQYMCgtBCSEBIABBCUkNAQsgACABayEAIAFBAnQgAmoiAiAFSQ0BDAkLCyAAQQhHDQFBJCEADAYLIAIgAEECdGooAgQhAgwECyACIAAtAICBBEECdGooAgAhAiAAQQVLBEAgAiEDDAYLIABBBUcNAyACQQBODQNBACACayEDDAULIAJBgEBrIgRBgIAITw0EIARBA3YiAi0A4IEEIgBFDQQgAUECcQ0BIAAhAwwEC0EALQD/////DxoACyACQQJ0KAKcggZBAXRBwPIAaiEDDAILIAJBf0YNASACQQF0QcDyAGohAwwBCyAGQQNGDQAgACACaiIAIAVPDQADQCAGIAAoAgAiAUcEQEEUQSQgAUECRhsgAGoiACAFSQ0BDAILCyAIIAdrIABqQcLyAGohAwsgAyAEQQN0QRBxdkH//wNxC64FAQJ/AkACQAJAAkACQCACQSJrDgYAAQEBAQABCyAAKAIUIQQgACACEAggACABIARBAWogACgCFEF/EAJBBCECIAMOAgMCAQsgAEEBOgBIIAAgACgCFDYCHCAAIAAoAhBBAWo2AhQPC0EGIQILIAAoAiggAjYCHAsgACAAKAIUQQFqIgI2AhQCQAJAIAIgACgCDCIBTw0AIAAoAhAhBCAAKAIIIQUDQAJAAkAgAiAFai0AACIDQQlrDicBBAEBBAQEBAQEBAQEBAQEBAQEBAQEBAEEBAQEBAQEBAQEBAQEBAMACyADQaABRw0DCyACIARODQEgACACQQFqIgI2AhQgASACRw0ACwsgAEEAEAchAyAAKAIUIQILAkAgAAJ/IANB4QBHBEAgA0H3AEcNAiAAIAJBAWoQBUHpAEcNAiAAIAJBAmoQBUH0AEcNAiAAIAJBA2oQBUHoAEcNAkEEDAELAkAgAkEBaiIBIAAoAgxNBEAgACgCCCABaikAAEL//////x+DQvPmlZPHDlENAQwDCyAAIAFC8+aVk8cOQQUQBEUNAgtBBgsgAmo2AhQCQCAAQQEQB0H7AEcNACAAKAIUIQMDQCAAIAAoAhRBAWo2AhQCfwJAAkAgAEEBEAciAUEiaw4GAAEBAQEAAQsgACABEAggACAAKAIUQQFqNgIUIABBARAHDAELIAAgARAJC0E6Rw0BIAAgACgCFEEBajYCFAJAIABBARAHIgFBImsOBgACAgICAAILIAAgARAIIAAgACgCFEEBajYCFAJAIABBARAHIgFBLEcEQCABQf0ARg0BDAMLIAAgACgCFEEBajYCFCAAQQEQB0H9AEcNAQsLIAAoAigiASADNgIYIAEgACgCFEEBajYCEA8LIAAgAjYCFA8LIAAgAkEBazYCFAuzAQEEfwJAAkAgACgCFCIBIAAoAhAiAkgEQANAIAAgAUEBaiIDNgIUAkACQAJAAkAgACgCCCADai0AACIEQdsAaw4CAQIACyAEQS9GDQYgAyEBIARBCmsOBAUCAgUCCyAAEA8gACgCECECIAAoAhQhAQwBCyAAIAFBAmoiATYCFAsgASACSA0ACwsgACABQQFqNgIUCyAAQQE6AEggACAAKAIUNgIcIAAgACgCEEEBajYCFAsLmQEBBX8CQCAAKAIUIgEgACgCECIDSARAIAAoAgghBANAAkACQAJAAkAgBCABQQFqIgJqLQAAIgVB3ABrDgICAQALIAIhASAFQQprDgQFAgIFAgsgACACNgIUDwsgAUECaiEBCyABIANIDQALCyABQQFqIQILIAAgAjYCFCAAQQE6AEggACAAKAIUNgIcIAAgACgCEEEBajYCFAtbAQF/AkACQAJAIAAgARAFQeUAaw4HAQICAgICAAILIAAgAUEBa0Li5JWLBkEEEAshAgwBCyAAIAFBAWsQBUH1AEcNACAAIAFBAmtC4965o5fNG0EGEAsPCyACC5oEAQJ/AkAgACABEAUiA0H/AEsNAAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQCADQeQAaw4UAAECEhISEgMSEg8EEhIFEgYSEgcSCyAAIAFBAWsQBUHpAGsOBAcREQgRCyAAIAFBAWsQBUHzAGsOAwgJChALIAAgAUEBaxAFQe8ARw0PIAAgAUECaxAFQeUARw0PIAAgAUEDaxAFQeMAaw4OCg8PDw8PDw8PDw8PDwsPCyAAIAFBAWtC4uSViwZBBBALDwsgACABQQFrQeQAEBIPCyAAIAFBAWtC5MqJq/fs2TJBBxALDwsgACABQQFrQuHuhcsGQQQQCw8LIAAgAUEBaxAFQeUAaw4LCAoKCgoKCgoKCgkKCyAAIAFBAmtC9t4BQQIQCw8LIAAgAUECa0L50pUDQQMQCw8LAkACQCAAIAFBAmsQBUHhAGsODAEJCQkJCQkJCQkJAAkLIAAgAUEDa0HlABASDwsgACABQQNrQeMAEBIPCyAAIAFBAmtC5MqxqwZBBBALDwsgACABQQJrQuPeuaOXzRtBBhALDwsgACABQQRrQunczaOXzBtBBhALDwsgACABQQRrQvTyAUECEAshAgwDC0EBIQIgACABQQFrIgFB6QAQEg0CIAAgAULyytGrpw5BBRALDwsgACABQQJrQe4AEBIPCyAAIAFBAmtC9NDJA0EDEAsPCyACC1UBAX8CQCABQQF0Qb+Nf0sNACAAIAEQBSACQf8BcUcNACABRQRAQQEPCyAAIAFBAWsQBSIAQYABTwRAIABBoAFGDwsgAC0AgIAEQQJxQQF2IQMLIAMLqQEBAn9BASECAkACQAJAAkACQAJAAkAgACABEAUiA0Epaw4WAgYGBgYGBgYGBgYGBgYGBgYGAgYGAQALIANB5QBrDhUEBQUCBQUFBQUFBQUFBQUFBQUFBQMFCyAAIAFBAWsQBUE9RiECCyACDwsgACABQQFrQuPC0ZsGQQQQCw8LIAAgAUEBa0Lm0rmLxo0bQQYQCw8LIAAgAUEBa0Ll2M0DQQMQCw8LQQAL9hEBCH8gACAAKAIUIgNBBmoiBDYCFCAAKAI4IQYCQAJAIAQgACgCDCIHTw0AIAAoAhAhCCAAKAIIIQUgBCECA0ACQCACIAVqLQAAIgFBCWtBBUkNAAJAIAFBIGsOEAEEBAQEBAQEBAQEBAQEBAMACyABQaABRw0DCyACIAhODQEgACACQQFqIgI2AhQgAiAHRw0ACwsgAEEBEAchASAAKAIUIQILAkACQAJAAkAgAiAERgRAIAFBgAFPDQEgAS0AgIAEQQFxRQ0BCwJAAkAgAUEqRwRAIAFB+wBHDQEgACACQQFqNgIUIABBARAHIQIgACgCFCEBA0ACQAJAAkAgAkEiaw4GAAEBAQEAAQsgACACEAggACAAKAIUQQFqIgI2AhQMAQsgACACEAkaIAAoAhQhAgsgAEEBEAcaIAAgASACEAYiAkEsRgRAIAAgACgCFEEBajYCFCAAQQEQByECCyACQf0ARgRAIABBAToARSAAIAAoAhRBAWo2AhQMBAsgASAAKAIUIgRHBEAgBCIBIAAoAhBMDQELCyAAQQE6AEggACAAKAIUNgIcIAAgACgCEEEBajYCFA8LIAAgAkEBajYCFCAAQQEQBxogACAAKAIUIgEgARAGGgwBCyAAQQA6AEQgAUGAAU8NASABQeEAayIFQRVLDQECQAJAQQEgBXQiBEGEkIABcUUEQCAEQSFxRQRAIAVBA0cNBSAAIAJBB2oiBDYCFCAEIAAoAgwiB08NAiAAKAIQIQggACgCCCEFIAQhAQNAAkAgASAFai0AACIDQQlrQQVJDQACQCADQSBrDhABBgYGBgYGBgYGBgYGBgYFAAsgA0GgAUcNBQsgASAITg0DIAAgAUEBaiIBNgIUIAEgB0cNAAsMAgsgACABQeEARgR/IAAgAkEFajYCFCAAQQAQBxogACgCFAUgAgtBCGo2AhQgAEEBEAciAUEqRgRAIAAgACgCFEEBajYCFCAAQQEQByEBCwwGCyAAKAIMIQMgAUHjAEYEQAJAAkAgAyACQQFqIgFPBEAgACgCCCABaigAAEHsws2bB0cNAgwBCyAAIAFC7MLNmwdBBBAERQ0BIAAoAhQhAgsCQCAAIAJBBWoQBSIBQYABTwRAIAFBoAFGDQEMAgsgAS0AgIAEQQJxRQ0BCyAAIAAoAhRBBWo2AhQgAEEBEAchAQwHCyAAKAIMIQMgACgCFEECaiECCyAAQQA6AEQgACACQQNqIgI2AhQCQAJAIAIgA08NACAAKAIQIQUgACgCCCEEA0ACQCACIARqLQAAIgFBCWtBBUkNAAJAIAFBIGsOEAEEBAQEBAQEBAQEBAQEBAMACyABQaABRw0DCyACIAVODQEgACACQQFqIgI2AhQgAiADRw0ACwsgAEEBEAchASAAKAIUIQILAn8CQCAAIAEQCSIFQfsARgRAIAAoAhQhAQwBCyAAKAIUIgEhBEEAIAVB2wBHDQEaCyAAIAEiBEEBajYCFCAAQQEQByEBIAAoAhQhAiAAIAEQCRogACgCFCEBQQELIQMCQCABIAJGDQADQCAAIAIgASACIAEQAQJAAkAgACgCFCICIAAoAgwiB08NACACIAAoAhAiASABIAJIGyEIIAAoAgghBQNAAkAgAiAFai0AACIBQQlrQQVJDQACQCABQSBrDhABBAQEBAQEBAQEBAQEBAQDAAsgAUGgAUcNAwsgAiAIRg0BIAAgAkEBaiICNgIUIAIgB0cNAAsLIABBARAHIQELIAMgAUHf/wNxQd0ARnENBSAAKAIUIQICQCABQSxHDQAgACACQQFqNgIUIABBARAHIQEgACgCFCECIAFB3/8DcUHbAEYNACAAIAEQCRogACgCFCIBIAJHDQEMAgsLIAAgAkEBazYCFAsgA0UNAyAAIARBAWs2AhQPCyAAQQEQByEDCwJAAkACQAJAAkACQAJAIANB4QBrDgYABgEGBgQGCwJAIAAoAhQiA0EBaiIBIAAoAgxNBEAgACgCCCABaigAAEHz8rmbBkYNAQwHCyAAIAFC8/K5mwZBBBAERQ0GIAAoAhQhAwsgACADQQVqEAUiBUEJayIBQRdLDQFBASABdEGNgIAEcUUNAQwCCwJAIAAoAhQiA0EBaiIBIAAoAgxNBEAgACgCCCABaigAAEHsws2bB0YNAQwGCyAAIAFC7MLNmwdBBBAERQ0FIAAoAhQhAwsCQCAAIANBBWoQBSIBQQlPBEAgAUEOSQ0BIAFBgAFyQaABRg0BCyAAIAAoAhRBBWoQBUH7AEcNBQsgACAAKAIUQQVqNgIUIABBARAHIgFB+wBHDQMMBAsgBUGgAUcNAwsgACAAKAIUQQVqNgIUIABBABAHGgsCQCAAKAIUIgNBAWoiASAAKAIMTQRAIAAoAgggAWopAABC//////////8Ag0L13I2jl+2bN1ENAQwDCyAAIAFC9dyNo5ftmzdBBxAERQ0CIAAoAhQhAwsCQCAAIANBCGoQBSIBQQlPBEAgAUEOSQ0BIAFBgAFyQaABRg0BCyAAIAAoAhRBCGoQBUEqRg0AIAAgACgCFEEIahAFQShHDQILIAAgACgCFEEIajYCFCAAQQEQByIBQSpGBEAgACAAKAIUQQFqNgIUIABBARAHIQELIAFBKEYNAQsgACgCFCEFIAAgARAJGiAAKAIUIgEgBUwNACAAIAIgBCAFIAEQAQwFCyAAIAIgBEF/QX8QASAAIAJBBmo2AhQPCyAAQQEQByEBIAAoAhQhAiABQeYARw0BAkAgAkEBaiIBIAAoAgxNBEAgACgCCCABaikAAEL///8Hg0Ly3rUDUQ0BDAMLIAAgAULy3rUDQQMQBCEBIAAoAhQhAiABRQ0CCyAAIAJBBGo2AhQgACADIABBARAHQQAQDSAGIAAoAjgiAk8NAANAAn8gBigCAEECRgRAIAZCfzcCDCAAKAI4IQIgBkEUagwBCyAGQSRqCyIGIAJJDQALCw8LIAAgAkEBazYCFA8LIAAoAhQhBCAAIAEQCRogACAEIAAoAhQiASAEIAEQAQsgACAAKAIUQQFrNgIUC5oSAgd/AXsgACAAKAIUIgdBBmoiBTYCFAJAAkAgBSAAKAIMIgNPDQAgACgCECEEIAAoAgghBiAFIQIDQAJAIAIgBmotAAAiAUEJa0EFSQ0AAkAgAUEgaw4QAQQEBAQEBAQEBAQEBAQEAwALIAFBoAFHDQMLIAIgBE4NASAAIAJBAWoiAjYCFCACIANHDQALCyAAQQEQByEBIAAoAhQhAgsCQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkAgAAJ/AkACQAJAAkACQAJAIAFBLkYEQCAAIAJBAWo2AhQgAEEBEAchAiAAKAIYIQEgAkHkAGsOEAMQEBAQEBAQEAEQEBAQEAIQCyABQfMARiACIAVKcQ0EIAFB5ABHDQggAiAHQQVqTA0IIAJBAWoiASAAKAIMSw0FQQAhBEEAIQMgAiAAKAIIIAFqKAAAQeXMlZMHRg0GGgwRCwJAIAAoAhRBAWoiAiAAKAIMTQRAIAAoAgggAmopAABC////B4NC5eiFA1ENAQwQCyAAIAJC5eiFA0EDEARFDQ8LIAAgARAWRQRAIAAgARAFQS5GDQ8LIAAgByAHIAAoAhRBBGpBfhACDwsCQCAAKAIUQQFqIgIgACgCDE0EQCAAKAIIIAJqKQAAQv//////H4NC7+rJm9YMUQ0BDA8LIAAgAkLv6smb1gxBBRAERQ0OC0EBIQNBBiECIAAgARAWDQEgACABEAVBLkcNAQwNCwJAIAAoAhRBAWoiAiAAKAIMTQRAIAAoAgggAmooAABB5cyVkwdGDQEMDgsgACACQuXMlZMHQQQQBEUNDQtBAiEDQQUhAiAAIAEQFg0AIAAgARAFQS5GDQwLIAAgACgCFCACajYCFCAAQQEQByEBDAULAkAgAkEBaiIGIAAoAgxNBEBBACEEIAIhAUEAIQMgACgCCCAGaikAAEL//////x+DQu/qyZvWDFINDgwBC0EAIQRBACEDIAAgBkLv6smb1gxBBRAERQ0NIAAoAhQhAQsgACABQQZqEAUiAUEJSQ0MAkAgAUEOSQ0AIAFBgAFyQaABRg0ADA0LIAAgACgCFEEGajYCFEEBIQMgAEEBEAchASAAKAIUIgQgAkEGakYNAiABQeYARw0EAkAgBEEBaiIBIAAoAgxNBEAgACgCCCABaikAAEL///8Hg0Ly3rUDUQ0BDAgLIAAgAULy3rUDQQMQBEUNByAAKAIUIQQLAkAgACAEQQRqEAUiAUGAAU8EQCABQaABRg0BDAgLIAEtAICABEECcUUNBwtB5gAhAQwCC0EAIQRBACEDIAAgAULlzJWTB0EEEARFDQsgACgCFAtBBWoQBSIBQQlJDQoCQCABQQ5JDQAgAUGAAXJBoAFGDQAMCwsgACAAKAIUQQVqNgIUQQEhBEECIQMgAEEBEAciAUEqRg0LCyAAIAI2AhQLQQAhAyABQShGDQEgAUH7AEcNAyAAKAIgRQRAAkAgAiAAKAIQIgVODQADQAJAIAJBACACQQBKGyIBIAAoAgwiA04NACAAKAIIIQQDQCABIARq/QAAACII/Qx9fX19fX19fX19fX19fX19/SMgCP0MIiIiIiIiIiIiIiIiIiIiIv0j/VAgCP0M9/f39/f39/f39/f39/f39/1O/QwnJycnJycnJycnJycnJycn/SP9UP1kIgZFBEAgAUEQaiIBIANIDQEMAgsLIAMgASAGaGoiASABIANKGyEDCyACIAVBAWsiASADIAEgA0gbIgFIBEAgACABNgIUCwJAAkACQCAAQQEQByICQSJrDgYBAAAAAAEACyACQf0ARw0BIAAgACgCFEEBajYCFAwDCyAAIAIQCAsgACAAKAIUQQFqIgI2AhQgAiAAKAIQIgVIDQALCyAAQQEQByEBIAAoAhQhAgJAIAFB5gBHDQAgAkEBaiIBIAAoAgxNBEAgACgCCCABaikAAEL///8Hg0Ly3rUDUg0NDAELIAAgAULy3rUDQQMQBEUNDCAAKAIUIQILIAAgAkEEajYCFAJAIABBARAHIgJBImsOBgAMDAwMAAwLIAAgByACQQAQDQwHCyAAIAJBAWs2AhQPCyABQfsARg0BIAFBKEcNAiAAKAIUIQILIAAoAiAiAUGAgAFJDQIgAEEBOgBIIAAgACgCFDYCHCAAIAAoAhBBAWo2AhQMAwtBACEEDAULIAFBKkYhBCABQSJrIgJBCEsNBEEBIAJ0QaECcUUNBAwFCyABQQU6AOCBBCABQQJ0IAI2ApyCBiAAIAFBAWo2AiALIAAgACgCGBAFQS5GDQAgACAAKAIUIgFBAWo2AhQgAEEBEAchAiAAIAcgACgCFEF/IAEQAiADBEAgACgCKEEFQQcgA0EBRhs2AhwLIAAoAiQiAUH/H0oNBCABQQJ0IAAoAig2ApSCBSAAIAFBAWo2AiQgAkEiaw4GAQYGBgYBBgsPCyAAIAIQCCAAIAAoAhRBAWoiAjYCFAJAAkAgAEEBEAdBKWsOBAEGBgAGCyAAIAAoAhRBAWo2AhQgAEEBEAcaIAAoAhQhBSAAKAIoIgFBATYCICABIAU2AhggASACNgIIDAULAkAgACgCICIBQQBKBEAgACABQQFrNgIgDAELIABBAToASCAAIAAoAhQ2AhwgACAAKAIQQQFqNgIUCyAAKAIUIQUgACgCKCIBQQE2AiAgASACNgIIIAEgBUEBajYCECAAIAAoAiRBAWs2AiQPCyAAKAIUIAVHDQAgACAHQQVqNgIUDwsCQCAEQX9zIANBAkZxRQRAIAAoAiBFDQELDAMLIAAoAgghBAJAIAAoAhQiBUEAIAVBAEobIgIgACgCDCIBTg0AA0AgAiAEav0AAAAiCP0MIiIiIiIiIiIiIiIiIiIiIv0jIAj9DCcnJycnJycnJycnJycnJyf9I/1Q/WQiBkUEQCACQRBqIgIgAUgNAQwCCwsgASACIAZoaiICIAEgAkgbIQELIAAoAhAiAiABSiABIAVOcQ0BIAIgBUwNACAAIAI2AhQLIABBAToASCAAIAAoAhQ2AhwgACAAKAIQQQFqNgIUDwsgACABNgIUIAAgByABIARqLQAAIAMQDQ8LIAAgACgCFEEBazYCFAswAQF/AkAgACABEAVBLkcNACAAIAFBAWsQBUEuRw0AIAAgAUECaxAFQS5GIQILIAILdAECf0EBIQICQAJ/IAAoAgwgAUkEQCAAIAEQDAwBCyAAKAIIIAFqLQAACyIDQQlrQQVJDQAgA0H//gNxQSBGDQBBACECIANB/wBLDQAgAy0AgIAEQQFxRQ0AQQEhAiAAIAEQFg0AIAAgARAFQS5HIQILIAILzgUBBX8gACAAKAIYIgIQBSEEIAAoAiAhAwJAAkAgBEGAAU8NAAJAIAQtAICABEEEcUUNAAJAAkACQCAEQStrDgQABQECBQsgACACQQFrEAVBK0YNAgwECyAAIAJBAWsQBUEtRw0DDAELIAAgAkEBaxAFQTBrQQpPDQILIARBKUcNAEHgRiEBAkAgA0H//wBLDQAgAy0A4IEERQ0AIANBAnQoApyCBiEBC0EBIQUCQCAAIAFC99Cl49YMQQUQCw0AIAAgAULm3skDQQMQCw0AIAAgAULpzAFBAhALIQULIAUNAQsCQCADQQBMDQAgA0GAgAFLDQAgA0EBayIBLQDggQRBAUcNACAAIAIQBUHmAEcNACAAIAJBAWsQBUHvAEcNACAAIAFB4IEEai0AAAR/IAFBAnQoApyCBgVB4EYLQubeyQNBAxALDQELAkAgBEH9AEcNACADQf//AE0EQCAAIAMtAOCBBAR/IANBAnQoApyCBgVB4EYLEBMNAiADQeCBBGotAABBBkcNAQwCCyAAQeBGEBMNAQsgACACEBENACAERQ0AIAAtAEYgBEEvRnENAAJAIAAoAjAiAUUNACACIAEoAgRIDQAgAiABKAIITA0BCwJAIAJBAEwEQCACIQEMAQsDQCAAIAJBAWsiATYCGAJ/IAAgARAFIgNBgAFPBEAgA0GgAUcMAQsgAy0AgIAEQQJxRQshAyACQQJJDQEgASECIAMNAAsLAkAgACABEAUiAkEJayIDQRdNQQBBASADdEGNgIAEcRtFIAJBoAFHcQ0AAkAgAUEATA0AIAFBAWohAgNAIAAgAkECayIBNgIYAkAgACABEAUiA0EJayIEQRdNQQBBASAEdEGNgIAEcRsNACADQaABRg0ADAILIAJBAWsiAkEBSw0AC0EAIQELIAAgARAQRQ0ADAELIABBAToARg8LIAAQDiAAQQA6AEYLuiQDEH8JewR+IwBBgAFrIgEkAEGUggYoAgAhCyAB/QwAAAAAAAAAAAAAAAAAAAAA/QsEACAAIAtqIgNB8ABqIAH9AAQAIhH9CwAAIANB4ABqIBH9CwAAIANB0ABqIBH9CwAAIANBQGsgEf0LAAAgA0EwaiAR/QsAACADQSBqIBH9CwAAIANBEGogEf0LAAAgAyAR/QsAAEFwIQIDQAJAIAJB8IEEaiIG/QAAAP1TRQ0AIAYgEf0LAAAgAkGAggRqIgb9AAAA/VNFDQAgBiAR/QsAACACQSBqIgJB8P8ASQ0BCwsgAUEANgIwIAFBADYARSABQQE6AEQgAUEANgIkIAH9DAAAAABg5f//AAAAAAAAAAD9CwIUIAFBmIIGKAIANgI8IAEgCzYCCCABIAA2AgwgASADQYcBakF4cSIINgI4IAEgCDYCNCABIACtQgF8IhtCAoZCv/IEfEKAgPz//wGDIho3AwAgAUIANwMoIAFC/////w8gCK0gGiAbQgGGfULA8gB9IhtCACAaIBtaG3wiGiAaQv////8PWhs+AkBBfyEEIAEgAEEBayIANgIQQQAhAgJAAkACQAJAIABBAEgNAANAAkACQAJAAkACQAJAAkAgASgCCCACai0AAEEJaw5hBgYGBgYDAwMDAwMDAwMDAwMDAwMDAwMGAwMDAwMDAwMDAwMDAwMCAwMDAwMDAwMDAwMFAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAAwMDAQMLIAEoAiANBAJAIAIEfyABIAQQF0UNBiABKAIUQQFqBUEBCyIAIAEoAgxNBEAgASgCCCAAaikAAEL//////x+DQvjgvZPHDlENAQwGCyABIABC+OC9k8cOQQUQBEUNBQsgARAUIAEtAEQNBCABIAEoAhQiAjYCGAwHCwJAIAIEfyABIAQQF0UNBSABKAIUQQFqBUEBCyIAIAEoAgxNBEAgASgCCCAAaikAAEL//////x+DQu3gvZPHDlINBQwBCyABIABC7eC9k8cOQQUQBEUNBAsgARAVDAMLAkAgASAEQQJqEAUiAEEqaw4GAgAAAAACAAsgASgCFCECCyABQQA6AEQgASACQQFrIgI2AhQMBAsgASAAQQEQAyABKAIUIQIMAQsgASABKAIUIgI2AhgLIAEgAiIEQQFqIgI2AhQgBCABKAIQSA0ACyABLQBIQQFHDQAgASgCOCECIAEtAEUhBCABLQBEIQMgASgCHCEAIAEoAjwhBgwBCyABKAIgIQQgASgCGCEAIAEoAgghCSABKAIMIQYgAUL/////DzcDeCABQQA2AnAgAULA////DzcDaAJAAkAgAkEBaiICIAZODQACQANAAn4gAkFAcSIDIAEoAmhHBEAgASACQT9xNgJwIAEgA0FAajYCaEIAIRpCAAwBC0J/IAKthiIbQYiCBSkDAIMhGkGAggUpAwAgG4MLIRsgASAaNwNYIAEgGzcDUCAAIQIDQCABIAQ2AmQgASACNgJgIAEgAS0ARzYCdCABIAEoAigiAAR/IAAoAggFQX8LNgJ4IAEgASgCJDYCfEGQgQT9AAQAIRJBoIEE/QAEACEXQbCBBP0ABAAhGEHAgQT9AAQAIRkgAUHQAGoiBSgCKCENIAUoAiQhCiAFKQMIIRsgBSkDACEaIAUoAhghAyAFKAIUIQQgBSgCECEAQdCBBP0ABAAhESAFKAIsQQBKIQ4DQAJAAkACQAJAAkACQAJAAkACQAJAIBpCAFIEQCAAIQIMAQsgACECIAMhAANAIAIgACAbeadrQT9qIBtQGyECIABBQGsiAyAGTg0CQYCCBSAZIAAgCWoiAEHxAGr9AAAAIhNBBP2NASAR/U79DiAYIBMgEf1O/Q79TiAXIABB8ABq/QAAACITQQT9jQEgEf1O/Q4gEiATIBH9Tv0O/U4iE/1O/QwAAAAAAAAAAAAAAAAAAAAA/Sf9ZK1CMIYgGSAAQcEAav0AAAAiFEEE/Y0BIBH9Tv0OIBggFCAR/U79Dv1OIBcgAEFAa/0AAAAiFEEE/Y0BIBH9Tv0OIBIgFCAR/U79Dv1OIhT9Tv0MAAAAAAAAAAAAAAAAAAAAAP0n/WQgGSAAQdEAav0AAAAiFUEE/Y0BIBH9Tv0OIBggFSAR/U79Dv1OIBcgAEHQAGr9AAAAIhVBBP2NASAR/U79DiASIBUgEf1O/Q79TiIV/U79DAAAAAAAAAAAAAAAAAAAAAD9J/1kQRB0cq0gGSAAQeEAav0AAAAiFkEE/Y0BIBH9Tv0OIBggFiAR/U79Dv1OIBcgAEHgAGr9AAAAIhZBBP2NASAR/U79DiASIBYgEf1O/Q79TiIW/U79DAAAAAAAAAAAAAAAAAAAAAD9J/1krUIghoSEIho3AwBBiIIFIBQgFEEB/YsB/VD9ZCAVIBVBAf2LAf1Q/WRBEHRyrSAWIBZBAf2LAf1Q/WStQiCGhCATIBNBAf2LAf1Q/WStQjCGhEJ/hSIbNwMAIAU1AiAhHCAFQQA2AiBCfyAchiIcIBuDIRsgAyEAIBogHIMiGlANAAsLIAIgAyAaQgF9IhwgGyAaQn+Fg4MiHXmna0E/aiAdUBshAkEBIQwCQCAJIAMgGnqnaiIAaiIHLQAAIg9B4wBrIhAOGwYJBgkJCQYJCQkJCQkJCQkJCQkJCQkJCQQJBQALIA9BKGsOAgECCAsgAEFAayEDQQAhDEIAIRogBiEADAcLIARB//8ASg0GIARBAToA4IEEIARBAnQgAjYCnIIGIARBAWohBAwFCyAERQRAQQAhBAwGCyAORQ0DIARB34EEai0AAEEFRg0FDAMLIARB//8ASg0EIAIgDUYNBCAEQQJ0IAI2ApyCBiAEQQZBAiAKGzoA4IEEIARBAWohBEEAIQogGiAcgyEaDAULIARFBEBBACEEDAQLIARB34EEai0AAEEERg0DIARBAWshBCAaIByDIRoMBAsCQAJAAkAgEA4HAAEBAQEBAgELIAdBAmotAABB4QBHDQMgB0EDai0AAEHzAEcNAyAHQQRqLQAAQfMARg0EDAMLIAQNAgsgB0ECai0AAEHwAEcNASAHQQNqLQAAQe8ARw0BIAdBBGotAABB8gBHDQEgB0EFai0AAEH0AEYNAgwBCyAEQQFrIQQgGiAcgyEaDAILIBogHIMhGgwBCwsgBSAANgIcIAUgAzYCGCAFIAQ2AhQgBSACNgIQIAUgCjYCJCAFIBs3AwggBSAaNwMAIAEgASgCdEEARzoARyABKAJkIQQgASgCYCEAIAxFBEAgASAENgIgIAEgADYCGCABIAY2AhQMBQsgASABKQNQIhpCAX0gGoM3A1ACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQCAJIAEoAmwiAmoiAy0AACIFQSJrDlwBExMTEwEKCRMTExMTCxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTEwwTAhMTEw0TExMTExMTExMTExMTExMTEwATBRMLIABBAEgNECABKAIoIgMNBwwQCyACQQFqIgIgBk4NAiAF/Q8hEgNAAkAgAiABKAIMIgNODQAgASgCCCEHA0AgAiAHav0AAAAiEf0MDQ0NDQ0NDQ0NDQ0NDQ0NDf0jIBH9DAoKCgoKCgoKCgoKCgoKCgr9I/1QIBH9DFxcXFxcXFxcXFxcXFxcXFz9IyARIBL9I/1Q/VD9ZCIKRQRAIAJBEGoiAiADSA0BDAILCyADIAIgCmhqIgIgAiADShshAwsgAyAGTgRAIAYhAgwECyADIAlqLQAAIgIgBUYNDiACQdwARwRAIAMhAgwECyABIANBAWoiAhAFQQ1GBH8gA0ECaiIDIAIgASADEAVBCkYbBSACC0EBaiICIAZIDQALDAILIAQNEEEAIQQgA0ECai0AAEHwAEcNECADQQNqLQAAQe8ARw0QIANBBGotAABB8gBHDRAgA0EFai0AAEH0AEcNEAJAIAJFBEBBACECDAELIAEgAkEBaxAXRQ0RCyABQQA2AiAgASAANgIYIAEgAjYCFCABEBQMCwsgBEH//wBLDQ4gBEEDOgDggQQgBEECdCAANgKcggYgASAANgIYIAEgAjYCFCABIARBAWo2AiAMAgsgASAENgIgIAEgADYCGCABIAI2AhQgAUEBOgBIIAEgASgCFDYCHCABIAEoAhBBAWo2AhQMCQsgBEUNASAEQd+BBGohAyAEQQFrIQQgAy0AAEEERw0NIAEgBDYCICABIAA2AhggASACNgIUCyABEAoMBwsgAUEANgIgDA0LIAAgCWotAABBKUcNCCADKAIIIABHDQggASgCKCIDIAEoAiwiBUcEQCADQQM2AgALIAEgBTYCKAwICyAEBEAgBEEBayEEIAEoAiQiBUEATA0KIAQtAOCBBEEFRw0KIAVBAnRBkIIFaigCACIDKAIIQX9GBEAgAyAAQQFqNgIICyABIAVBAWs2AiQgAyACQQFqNgIQDAoLIAFBADYCIAwLCyAEQf//AEsNByAEQQE6AOCBBCAEQQJ0IAA2ApyCBiAEQQFqIQQMCAsgA0EBai0AACEDIAEgBDYCICABIAA2AhggASACNgIUAkACQAJAIANBKmsOBgECAgICAAILIAJBAWohAyABKAIQIAJKBEAgASgCDCICIANMBEAgASACIgM2AhQMCAsgASgCCCEFAkADQCADIAVq/QAAACIR/QwNDQ0NDQ0NDQ0NDQ0NDQ0N/SMgEf0MCgoKCgoKCgoKCgoKCgoKCv0j/VD9ZCIHDQEgA0EQaiIDIAJIDQALIAEgAiIDNgIUDAgLIAIgAyAHaGoiAyACIANIGyEDCyABIAM2AhQMBgsgAkECaiEDAkAgASgCECACQQFqSgRAAkAgAyABKAIMIgJODQAgASgCCCEFA0AgAyAFaiIH/QAAAP0MKioqKioqKioqKioqKioqKv0jIAdBAWr9AAAA/QwvLy8vLy8vLy8vLy8vLy8v/SP9Tv1kIgdFBEAgA0EQaiIDIAJIDQEMAgsLIAMgB2hqIgMgAkgNAgsgAiEDCyABIAM2AhQMBgsgASACIAMgAiADSBsiAzYCFCADIAVqLQAAQSpHDQUgASADQQFqIgM2AhQMBQsgARAYDAILIANBAmotAABB4QBHDQYgA0EDai0AAEHzAEcNBiADQQRqLQAAQfMARw0GIANBBWotAAAiAEEJSQ0GIABBgAFyQaABRyAAQQ5PcQ0GIAIEQCABIAJBAWsQF0UNBwsgAUEBOgBHDAYLIANBAmotAABB8ABHDQUgA0EDai0AAEHvAEcNBSADQQRqLQAAQfIARw0FIANBBWotAABB9ABHDQUCQCACRQRAQQAhAgwBCyABIAJBAWsQF0UNBgsgASAENgIgIAEgADYCGCABIAI2AhQgARAVCyABKAIgIQQgASgCFCEDCyADIQALIANBAWoiAiAGSA0DDAULIARB//8ASw0AIARBBkECIAEtAEcbOgDggQQgBEECdCAANgKcggYgAUEAOgBHIARBAWohBAwBCwsLIAEgBDYCIAsgASAANgIYIAEgAjYCFCABQQE6AEggASABKAIUNgIcIAEgASgCEEEBajYCFAwBCyABIAQ2AiAgASAANgIYIAEgAjYCFAsgASgCOCECIAEtAEUhBCABLQBEIQMgASgCHCEAIAEoAjwhBiABKAIgDQAgAS0ASEEBcQ0AQQAhCUGYggYgBjYCACABKAIkDQFB9IEFIAI2AgBB8IEFIAg2AgBB7IEFIAQ2AgBB6IEFIAM2AgBB5IEFIAA2AgBB4IEFQQA2AgAgAiAITQ0CA0BBFCEAAkAgCCgCAEECRg0AQSQhACAIKAIgRQ0AIAgoAgQhBAJAAn8gCCgCFEF/RgRAIAgoAggMAQsgBEEBaiEEIAgoAghBAWsLIgMgBEwEQEEBIQMMAQsgBCALaiECIAMgBGshBANAIAItAABB3ABHBEBBASEDIAJBAWohAiAEQQFrIgQNAQwCCwtBAyEDCyAIIAM2AiAgASgCOCECCyACIAAgCGoiCEsNAAsMAgtBmIIGIAY2AgALQfSBBSACNgIAQfCBBSAINgIAQeSBBSAANgIAQQEhCUHggQVBATYCAEHsgQUgBEH/AXE2AgBB6IEFIANB/wFxNgIACyABQYABaiQAIAkLkgEBAn9BlIIGKAIAIgJFBEBBlIIGPwBBEHQiAjYCAAtBkIIFKAIAIgEgAE9BACABG0UEQEGQggVBgP8DIAFBA2xBAXYiASAAIAAgAUkbIgAgAEGA/wNNG0EHakF4cSIANgIAQZiCBiAAIAJqQYABahAANgIAQZCCBSgCACEBQZSCBigCACECC0H4gQUgATYCACACC+cCAgZ/A3sjAEEQayICJABBlIIGKAIAIQUgAv0M/wD/AP8A/wD/AP8A/wD/AP0LBAAgAv0ABAAhByAABH8DQCABIAVqIgRBEGr9AAAAIQggBP0AAAAhCSADIAVqIgZBEGogBEEgav0AAAAgB/2XAf0MAAAAAAAAAAAAAAAAAAAAAP2YAf0M/wD/AP8A/wD/AP8A/wD/AP2WASAEQTBq/QAAACAH/ZcB/QwAAAAAAAAAAAAAAAAAAAAA/ZgB/Qz/AP8A/wD/AP8A/wD/AP8A/ZYB/Wb9CwAAIAYgCSAH/ZcB/QwAAAAAAAAAAAAAAAAAAAAA/ZgB/Qz/AP8A/wD/AP8A/wD/AP8A/ZYBIAggB/2XAf0MAAAAAAAAAAAAAAAAAAAAAP2YAf0M/wD/AP8A/wD/AP8A/wD/AP2WAf1m/QsAACABQUBrIQEgA0EgaiIDIABJDQALIAAFQQALEBkhACACQRBqJAAgAAsGACAAEBkLgAICB38BeyABBEBBlIIGKAIAIQUDQCAEIAVqIQgCfwJAAn8CQAJAAn8gASAEQRBqIgNJBEAgCC0AAAwBCyAI/QAAACIJ/WRFDQEgCf0WAAsiBsBBAEgNASACIQNBAQwCCyACIAVqIAn9CwAAIAJBEGohAiADDAMLIAZB/wFxIgdBwAFJDQEgB0HCAUYEQEGgf0GAfyAIQQFqLQAAQaABRhshBiACIQNBAQwBC0GAASEGIAIgBWpBgAE6AAAgAkEBaiEDIAdB8AFJBEAgAyECIARBAWoMAwtBAgshByADIAVqIAY6AAAgAiAHaiECCyAEQQFqCyIEIAFJDQALCyAAEBkLC6gBBQBBiYAECwUKCgoKCgBBoIAECxAKDwAAAA8PAA8LDw8PDw0LAEG6gAQLBg8PDw8PDwBB24AECwQPAAsPAEH7gAQLZQ8PCw8AAQIDBAYFCAcAAAAAAAAAAIQAASAACAABAVFAQkBCAAFAAIEAAAA8AgAAAAAAAAAABwcHBwcHBwcPBwcHJxcHBwcHBwcHBzcPBwcHBwcHBwcPDw8PDw8PDw8PDw8PDw8P";
}
/** the string-copy module (build.mjs), base64 (browser.mjs: as text) */
function COPY8()         {
  return "AGFzbQEAAAABIwVedwFgAm9/AX9gA29/fwFkb2ADb2MAfwF/YAZvf39/f38AAmkEA2VudgZtZW1vcnkCAAAOd2FzbTpqcy1zdHJpbmcKY2hhckNvZGVBdAABDndhc206anMtc3RyaW5nCXN1YnN0cmluZwACDndhc206anMtc3RyaW5nEWludG9DaGFyQ29kZUFycmF5AAMDAgEEBgcBYwAB0HELBwkBBWNvcHk4AAMK+gcB9wcDAWMAA38BeyAE/RAhCiAFBEAgASEFIAEgAiABa0FwcWohBwNAIAEgB09FBEAgASADaiAAIAEQAK0gACABQQFqEACtQhCGhCAAIAFBAmoQAK1CIIYgACABQQNqEACtQjCGhIT9EiAAIAFBBGoQAK0gACABQQVqEACtQhCGhCAAIAFBBmoQAK1CIIYgACABQQdqEACtQjCGhIT9HgEgCv2XASAAIAFBCGoQAK0gACABQQlqEACtQhCGhCAAIAFBCmoQAK1CIIYgACABQQtqEACtQjCGhIT9EiAAIAFBDGoQAK0gACABQQ1qEACtQhCGhCAAIAFBDmoQAK1CIIYgACABQQ9qEACtQjCGhIT9HgEgCv2XAf1m/QsEACABQRBqIQEMAQsLIAEgAkkgAiAFa0EQT3EEQCACQRBrIgEgA2ogACABEACtIAAgAUEBahAArUIQhoQgACABQQJqEACtQiCGIAAgAUEDahAArUIwhoSE/RIgACABQQRqEACtIAAgAUEFahAArUIQhoQgACABQQZqEACtQiCGIAAgAUEHahAArUIwhoSE/R4BIAr9lwEgACABQQhqEACtIAAgAUEJahAArUIQhoQgACABQQpqEACtQiCGIAAgAUELahAArUIwhoSE/RIgACABQQxqEACtIAAgAUENahAArUIQhoQgACABQQ5qEACtQiCGIAAgAUEPahAArUIwhoSE/R4BIAr9lwH9Zv0LBAAPCwNAIAEgAk9FBEAgASADaiAEIAAgARAAIgUgBCAFSRs6AAAgAUEBaiEBDAELCw8LIwDRBEBBgIAE+wcAJAALIwAhBgNAIAEgAk9FBEAgAiABayIHQYCABEsEQEGAgAQhBwsgACABIAEgB2oQASAGQQAQAhogASADaiEJQQAhBSAHQXBxIQgDQCAFIAhPRQRAIAUgCWogBiAF+w0ArSAGIAVBAWr7DQCtQhCGhCAGIAVBAmr7DQCtQiCGIAYgBUEDavsNAK1CMIaEhP0SIAYgBUEEavsNAK0gBiAFQQVq+w0ArUIQhoQgBiAFQQZq+w0ArUIghiAGIAVBB2r7DQCtQjCGhIT9HgEgCv2XASAGIAVBCGr7DQCtIAYgBUEJavsNAK1CEIaEIAYgBUEKavsNAK1CIIYgBiAFQQtq+w0ArUIwhoSE/RIgBiAFQQxq+w0ArSAGIAVBDWr7DQCtQhCGhCAGIAVBDmr7DQCtQiCGIAYgBUEPavsNAK1CMIaEhP0eASAK/ZcB/Wb9CwQAIAVBEGohBQwBCwsDQCAFIAdPRQRAIAUgCWogBCAGIAX7DQAiCCAEIAhJGzoAACAFQQFqIQUMAQsLIAEgB2ohAQwBCwsL";
}
/** browser.mjs: the decoder of the text (rust/decode.wat), base64 */
function DECODER()         {
  return "";
}
// generated from index.mts by tools/ts-build.mjs; edit that file
