[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+simd128,+bulk-memory,+sign-ext,+mutable-globals,+nontrapping-fptoint", "-C", "link-arg=-zstack-size=65536"]
