// usage: node tools/gen_js_ident.mjs [path/to/esbuild-src]
// Regenerates src/js_ident.mts from internal/js_ast/unicode.go (the Unicode
// identifier tables) plus the hand-ported code of internal/js_ast/js_ident.go
// kept in this script. The tables are stored as base-36 deltas:
// lo0, hi0-lo0, lo1-hi0, hi1-lo1, ... (all Go ranges have Stride 1, which the
// generator verifies).
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";

const here = dirname(fileURLToPath(import.meta.url));
const srcRoot = process.argv[2] || resolve(tmpdir(), "esbuild-src");
const goText = readFileSync(resolve(srcRoot, "internal/js_ast/unicode.go"), "utf8");

const tables = {};
const re = /var (\w+) = &unicode\.RangeTable\{([\s\S]*?)\n\}/g;
let m;
while ((m = re.exec(goText))) {
  const name = m[1];
  const body = m[2];
  const ranges = [];
  const rr = /\{Lo: 0x([0-9a-f]+), Hi: 0x([0-9a-f]+), Stride: (\d+)\}/g;
  let r;
  while ((r = rr.exec(body))) {
    if (r[3] !== "1") throw new Error("unexpected stride " + r[3] + " in " + name);
    ranges.push([parseInt(r[1], 16), parseInt(r[2], 16)]);
  }
  for (let i = 1; i < ranges.length; i++) {
    if (ranges[i][0] <= ranges[i - 1][1]) throw new Error("unsorted ranges in " + name);
  }
  const deltas = [];
  let prev = 0;
  for (const [lo, hi] of ranges) {
    deltas.push((lo - prev).toString(36), (hi - lo).toString(36));
    prev = hi;
  }
  tables[name] = { count: ranges.length, enc: deltas.join(",") };
}

const expected = ["idStartES5AndESNext", "idContinueES5AndESNext", "idStartES5OrESNext", "idContinueES5OrESNext"];
for (const name of expected) if (!tables[name]) throw new Error("missing table " + name);
if (Object.keys(tables).length !== expected.length) throw new Error("unexpected tables: " + Object.keys(tables));

function wrap(s, width) {
  const lines = [];
  while (s.length > width) {
    let cut = s.lastIndexOf(",", width);
    if (cut <= 0) cut = width;
    lines.push(s.slice(0, cut + 1));
    s = s.slice(cut + 1);
  }
  lines.push(s);
  return lines.map((l) => '  "' + l + '"').join(" +\n");
}

let tableText = "";
for (const name of expected) {
  tableText += `// ${tables[name].count} ranges\nconst ${name}Enc =\n${wrap(tables[name].enc, 100)};\n`;
}

const out = `// Port of internal/js_ast/js_ident.go and internal/js_ast/unicode.go.
// GENERATED by tools/gen_js_ident.mjs from the esbuild Go source: do not edit
// by hand (edit the generator instead).
//
// Go strings iterated with "range" are WTF-8 there; here they are JS strings.
// A lone surrogate is never an identifier character in either representation.

// ---------------------------------------------------------------------------
// Unicode tables (unicode.go). Each table is a sorted list of inclusive
// [lo, hi] ranges (all Go ranges have Stride 1), encoded as base-36 deltas:
// lo0, hi0-lo0, lo1-hi0, hi1-lo1, ...

${tableText}
// A decoded table: a bitmap for the BMP plus sorted astral ranges. Tables are
// decoded lazily on the first non-ASCII query.
class IdentTable {
  declare enc: string;
  declare bmp: Uint32Array | null;
  declare astral: Int32Array | null;
  constructor(enc: string) {
    this.enc = enc;
    this.bmp = null; // Uint32Array bitmap of 0x10000 bits
    this.astral = null; // Int32Array [lo0, hi0, lo1, hi1, ...] for ranges above 0xFFFF
  }

  init() {
    const parts = this.enc.split(",");
    const bmp = new Uint32Array(0x10000 >>> 5);
    const astral = [];
    let prev = 0;
    for (let k = 0; k < parts.length; k += 2) {
      const lo = prev + parseInt(parts[k], 36);
      const hi = lo + parseInt(parts[k + 1], 36);
      prev = hi;
      const bmpHi = hi > 0xffff ? 0xffff : hi;
      for (let c = lo; c <= bmpHi; c++) bmp[c >>> 5] |= 1 << (c & 31);
      if (hi > 0xffff) astral.push(lo > 0xffff ? lo : 0x10000, hi);
    }
    this.bmp = bmp;
    this.astral = Int32Array.from(astral);
  }

  // Equivalent to Go's unicode.Is(table, codePoint)
  has(c) {
    if (this.bmp === null) this.init();
    if (c < 0) return false;
    if (c <= 0xffff) return (this.bmp[c >>> 5] & (1 << (c & 31))) !== 0;
    const a = this.astral;
    let lo = 0;
    let hi = (a.length >>> 1) - 1;
    while (lo <= hi) {
      const mid = (lo + hi) >>> 1;
      if (c < a[mid * 2]) hi = mid - 1;
      else if (c > a[mid * 2 + 1]) lo = mid + 1;
      else return true;
    }
    return false;
  }
}

const idStartES5AndESNext = new IdentTable(idStartES5AndESNextEnc);
const idContinueES5AndESNext = new IdentTable(idContinueES5AndESNextEnc);
const idStartES5OrESNext = new IdentTable(idStartES5OrESNextEnc);
const idContinueES5OrESNext = new IdentTable(idContinueES5OrESNextEnc);

// ---------------------------------------------------------------------------
// js_ident.go

// ASCII classification: 1 = identifier start (and continue), 2 = continue only
const asciiIdent = new Uint8Array(128);
for (let c = 97; c <= 122; c++) asciiIdent[c] = 1;
for (let c = 65; c <= 90; c++) asciiIdent[c] = 1;
asciiIdent[95] = 1; // _
asciiIdent[36] = 1; // $
for (let c = 48; c <= 57; c++) asciiIdent[c] = 2;

export function isIdentifier(text) {
  const n = text.length;
  if (n === 0) return false;
  for (let i = 0; i < n; i++) {
    let c = text.charCodeAt(i);
    if (c >= 0xd800 && c <= 0xdbff && i + 1 < n) {
      const c2 = text.charCodeAt(i + 1);
      if (c2 >= 0xdc00 && c2 <= 0xdfff) {
        c = ((c - 0xd800) << 10) + (c2 - 0xdc00) + 0x10000;
        if (i === 0) {
          if (!isIdentifierStart(c)) return false;
        } else if (!isIdentifierContinue(c)) return false;
        i++;
        continue;
      }
    }
    if (i === 0) {
      if (!isIdentifierStart(c)) return false;
    } else if (!isIdentifierContinue(c)) return false;
  }
  return true;
}

export function isIdentifierES5AndESNext(text) {
  const n = text.length;
  if (n === 0) return false;
  for (let i = 0; i < n; i++) {
    let c = text.charCodeAt(i);
    if (c >= 0xd800 && c <= 0xdbff && i + 1 < n) {
      const c2 = text.charCodeAt(i + 1);
      if (c2 >= 0xdc00 && c2 <= 0xdfff) {
        c = ((c - 0xd800) << 10) + (c2 - 0xdc00) + 0x10000;
        if (i === 0) {
          if (!isIdentifierStartES5AndESNext(c)) return false;
        } else if (!isIdentifierContinueES5AndESNext(c)) return false;
        i++;
        continue;
      }
    }
    if (i === 0) {
      if (!isIdentifierStartES5AndESNext(c)) return false;
    } else if (!isIdentifierContinueES5AndESNext(c)) return false;
  }
  return true;
}

// Note: Go decodes the text as UTF-8 here, so a lone surrogate (3 bytes of
// WTF-8) becomes three U+FFFD runes and therefore three "_" characters.
export function forceValidIdentifier(prefix, text) {
  let sb = "";

  // Private identifiers must be prefixed by "#"
  if (prefix !== "") sb += prefix;

  const n = text.length;
  let i = 0;
  let isFirst = true;
  while (isFirst || i < n) {
    let c;
    let width = 1;
    if (i >= n) {
      c = 0xfffd; // utf8.DecodeRuneInString("") returns RuneError
      width = 0;
    } else {
      c = text.charCodeAt(i);
      if (c >= 0xd800 && c <= 0xdfff) {
        const c2 = i + 1 < n ? text.charCodeAt(i + 1) : 0;
        if (c <= 0xdbff && c2 >= 0xdc00 && c2 <= 0xdfff) {
          c = ((c - 0xd800) << 10) + (c2 - 0xdc00) + 0x10000;
          width = 2;
        } else {
          // Lone surrogate: three invalid UTF-8 bytes in Go
          sb += "___";
          i++;
          isFirst = false;
          continue;
        }
      }
    }
    i += width;
    const ok = isFirst ? isIdentifierStart(c) : isIdentifierContinue(c);
    isFirst = false;
    if (ok) sb += width === 2 ? text.slice(i - 2, i) : String.fromCharCode(c);
    else sb += "_";
  }

  return sb;
}

// This does "IsIdentifier(UTF16ToString(text))" without any allocations
export function isIdentifierUTF16(text) {
  return isIdentifier(text);
}

// This does "IsIdentifierES5AndESNext(UTF16ToString(text))" without any allocations
export function isIdentifierES5AndESNextUTF16(text) {
  return isIdentifierES5AndESNext(text);
}

export function isIdentifierStart(codePoint) {
  if (codePoint < 0x80) return codePoint >= 0 && asciiIdent[codePoint] === 1;

  // All ASCII identifier start code points are listed above
  return idStartES5OrESNext.has(codePoint);
}

export function isIdentifierContinue(codePoint) {
  if (codePoint < 0x80) return codePoint >= 0 && asciiIdent[codePoint] !== 0;

  // ZWNJ and ZWJ are allowed in identifiers
  if (codePoint === 0x200c || codePoint === 0x200d) return true;

  return idContinueES5OrESNext.has(codePoint);
}

export function isIdentifierStartES5AndESNext(codePoint) {
  if (codePoint < 0x80) return codePoint >= 0 && asciiIdent[codePoint] === 1;

  // All ASCII identifier start code points are listed above
  return idStartES5AndESNext.has(codePoint);
}

export function isIdentifierContinueES5AndESNext(codePoint) {
  if (codePoint < 0x80) return codePoint >= 0 && asciiIdent[codePoint] !== 0;

  // ZWNJ and ZWJ are allowed in identifiers
  if (codePoint === 0x200c || codePoint === 0x200d) return true;

  return idContinueES5AndESNext.has(codePoint);
}

// See the "White Space Code Points" table in the ECMAScript standard
export function isWhitespace(codePoint) {
  switch (codePoint) {
    case 0x0009: // character tabulation
    case 0x000b: // line tabulation
    case 0x000c: // form feed
    case 0x0020: // space
    case 0x00a0: // no-break space

    // Unicode "Space_Separator" code points
    case 0x1680: // ogham space mark
    case 0x2000: // en quad
    case 0x2001: // em quad
    case 0x2002: // en space
    case 0x2003: // em space
    case 0x2004: // three-per-em space
    case 0x2005: // four-per-em space
    case 0x2006: // six-per-em space
    case 0x2007: // figure space
    case 0x2008: // punctuation space
    case 0x2009: // thin space
    case 0x200a: // hair space
    case 0x202f: // narrow no-break space
    case 0x205f: // medium mathematical space
    case 0x3000: // ideographic space

    case 0xfeff: // zero width non-breaking space
      return true;

    default:
      return false;
  }
}
`;

const target = resolve(here, "../src/js_ident.mts"); // (then run tools/ts-build.mjs at the repository root)
writeFileSync(target, out);
console.log("wrote " + target);
for (const name of expected) console.log(`  ${name}: ${tables[name].count} ranges, ${tables[name].enc.length} chars`);
