// usage: node tools/gen_compat.mjs [path/to/esbuild-src]
// Generates src/compat.mts (the JavaScript half of internal/compat: engines,
// JSFeature, the version tables and UnsupportedJSFeatures) from
// internal/compat/js_table.go and compat.go. CSS features are not ported.
// (Then run tools/ts-build.mjs at the repository root.)
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";

const esbuildSrc = process.argv[2] || join(tmpdir(), "esbuild-src");
const goFile = join(esbuildSrc, "internal", "compat", "js_table.go");
const outFile = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "compat.mts");
const go = readFileSync(goFile, "utf8").replace(/\r/g, "");

function block(start, end = "\n)\n") {
  const i = go.indexOf(start);
  if (i < 0) throw new Error("not found: " + start);
  const j = go.indexOf(end, i + start.length);
  return go.slice(i + start.length, j);
}

// Engines ("iota" order)
const engines = block("type Engine uint8\n\nconst (\n")
  .split("\n")
  .map((l) => l.trim())
  .filter(Boolean)
  .map((l) => l.split(" ")[0]);
if (engines[0] !== "Chrome" || engines.length !== 12) throw new Error("unexpected engines: " + engines);
const engineNames = {};
for (const m of go.matchAll(/case (\w+):\n\t\treturn "(\w+)"/g)) engineNames[m[1]] = m[2];
const browsers = go.match(/func \(e Engine\) IsBrowser\(\) bool \{\n\tswitch e \{\n\tcase ([^:]+):/)[1].split(", ");

// JSFeature ("1 << iota" order)
const features = block("type JSFeature uint64\n\nconst (\n")
  .split("\n")
  .map((l) => l.trim())
  .filter(Boolean)
  .map((l) => l.split(" ")[0]);
if (features[0] !== "ArbitraryModuleNamespaceNames" || features.length > 64) throw new Error("unexpected features");
const stringToFeature = [];
for (const m of block("var StringToJSFeature = map[string]JSFeature{\n", "\n}\n").matchAll(/"([^"]+)":\s+(\w+),/g)) {
  stringToFeature.push([m[1], m[2]]);
}
if (stringToFeature.length !== features.length) throw new Error("StringToJSFeature size");

// jsTable
const table = block("var jsTable = map[JSFeature]map[Engine][]versionRange{\n", "\n}\n\n");
const rows = [];
{
  const re = /^\t(\w+): \{(\}|\n([\s\S]*?)\n\t\}),$/gm;
  let m;
  while ((m = re.exec(table)) !== null) {
    const feature = m[1];
    const body = m[3] || "";
    const perEngine = [];
    for (const line of body.split("\n")) {
      const t = line.trim();
      if (t === "" || t.startsWith("//")) continue;
      const em = t.match(/^(\w+):\s+\{(.*)\},$/);
      if (!em) throw new Error("bad line: " + t);
      const ranges = [];
      for (const r of em[2].matchAll(/\{start: v\{(\d+), (\d+), (\d+)\}(?:, end: v\{(\d+), (\d+), (\d+)\})?\}/g)) {
        ranges.push(r[4] === undefined ? [+r[1], +r[2], +r[3]] : [+r[1], +r[2], +r[3], +r[4], +r[5], +r[6]]);
      }
      if (ranges.length === 0) throw new Error("no ranges: " + t);
      perEngine.push([em[1], ranges]);
    }
    rows.push([feature, perEngine]);
  }
}
if (rows.length !== features.length) throw new Error(`jsTable has ${rows.length} rows, expected ${features.length}`);

let out = `// Port of the JavaScript half of internal/compat (compat.go, js_table.go).
//
// GENERATED by tools/gen_compat.mjs from the Go source. Do not edit by hand.
//
// compat.JSFeature is a uint64 bit set in Go ("1 << iota"). JS numbers cannot
// hold 64 bits, so a set is an immutable JSFeature object with two 32-bit
// halves: bit i of the Go value is bit i of "lo" (i < 32) or bit i-32 of "hi".
// The feature constants below are single-bit sets. Go's
// "features.Has(compat.X)" is "jsFeatureHas(features, X)", "a | b" is
// "jsFeatureOr(a, b)", and the empty set (Go's 0) is "JSFeatureNone".
import {
  SymbolPrivateField,
  SymbolPrivateMethod,
  SymbolPrivateGet,
  SymbolPrivateSet,
  SymbolPrivateGetSetPair,
  SymbolPrivateStaticField,
  SymbolPrivateStaticMethod,
  SymbolPrivateStaticGet,
  SymbolPrivateStaticSet,
  SymbolPrivateStaticGetSetPair,
} from "./ast.mjs";

export class JSFeature {
  declare lo: number;
  declare hi: number;
  constructor(lo: number, hi: number) {
    this.lo = lo | 0;
    this.hi = hi | 0;
  }
  toString() {
    return this.hi + ":" + this.lo;
  }
}

function bit(i: number): JSFeature {
  return Object.freeze(i < 32 ? new JSFeature(1 << i, 0) : new JSFeature(0, 1 << (i - 32)));
}

export const JSFeatureNone = Object.freeze(new JSFeature(0, 0));

// Go: func (features JSFeature) Has(feature JSFeature) bool
export function jsFeatureHas(features: JSFeature, feature: JSFeature): boolean {
  return (features.lo & feature.lo) !== 0 || (features.hi & feature.hi) !== 0;
}

// Go: a | b
export function jsFeatureOr(a: JSFeature, b: JSFeature): JSFeature {
  const lo = a.lo | b.lo;
  const hi = a.hi | b.hi;
  if (lo === a.lo && hi === a.hi) return a;
  return Object.freeze(new JSFeature(lo, hi));
}

// Go: a == b
export function jsFeatureEqual(a: JSFeature, b: JSFeature): boolean {
  return a.lo === b.lo && a.hi === b.hi;
}

export function jsFeatureIsEmpty(a: JSFeature): boolean {
  return a.lo === 0 && a.hi === 0;
}

// Go: func (features JSFeature) ApplyOverrides(overrides JSFeature, mask JSFeature) JSFeature
export function jsFeatureApplyOverrides(features: JSFeature, overrides: JSFeature, mask: JSFeature): JSFeature {
  return Object.freeze(new JSFeature((features.lo & ~mask.lo) | (overrides.lo & mask.lo), (features.hi & ~mask.hi) | (overrides.hi & mask.hi)));
}

// Engine
`;
engines.forEach((e, i) => (out += `export const ${e} = ${i};\n`));
out += `\n// Go: func (e Engine) String() string\nexport function engineString(e: number): string {\n  switch (e) {\n`;
for (const e of engines) out += `    case ${e}:\n      return ${JSON.stringify(engineNames[e])};\n`;
out += `  }\n  return "";\n}\n\n// Go: func (e Engine) IsBrowser() bool\nexport function engineIsBrowser(e: number): boolean {\n  switch (e) {\n`;
for (const e of browsers) out += `    case ${e}:\n`;
out += `      return true;\n  }\n  return false;\n}\n\n// JSFeature\n`;
features.forEach((f, i) => (out += `export const ${f} = bit(${i});\n`));
out += `\nexport const StringToJSFeature: Map<string, JSFeature> = new Map([\n`;
for (const [s, f] of stringToFeature) out += `  [${JSON.stringify(s)}, ${f}],\n`;
out += `]);\n\n// Go: jsTable (feature -> engine -> version ranges). A range is\n// [major, minor, patch] (no end) or [major, minor, patch, endMajor, endMinor, endPatch].\nconst jsTable: [JSFeature, [number, number[][]][]][] = [\n`;
for (const [feature, perEngine] of rows) {
  out += `  [${feature}, [${perEngine.map(([e, ranges]) => `[${e}, ${JSON.stringify(ranges)}]`).join(", ")}]],\n`;
}
out += `];

// Go: type Semver struct { Parts []int; PreRelease string }
export class Semver {
  declare parts: number[];
  declare preRelease: string;
  constructor(parts: number[] = [], preRelease = "") {
    this.parts = parts;
    this.preRelease = preRelease;
  }
}

// Go: func compareVersions(a v, b Semver) int. "a" is [major, minor, patch]
// at offset "i" of a range.
function compareVersions(a: number[], i: number, b: Semver): number {
  let diff = a[i];
  if (b.parts.length > 0) diff -= b.parts[0];
  if (diff === 0) {
    diff = a[i + 1];
    if (b.parts.length > 1) diff -= b.parts[1];
  }
  if (diff === 0) {
    diff = a[i + 2];
    if (b.parts.length > 2) diff -= b.parts[2];
  }
  if (diff === 0 && b.preRelease.length !== 0) {
    return 1; // "1.0.0" > "1.0.0-alpha"
  }
  return diff;
}

function splitOffNextPreReleasePart(text: string): [string, string] {
  const i = text.indexOf(".");
  if (i !== -1) return [text.slice(0, i), text.slice(i + 1)];
  return [text, ""];
}

// Go: strconv.Atoi of a string of ASCII digits ("ok" is false on overflow)
function preReleasePartToNumber(text: string): [number, boolean] {
  for (let i = 0; i < text.length; i++) {
    const c = text.charCodeAt(i);
    if (c < 48 || c > 57) return [0, false];
  }
  if (text === "") return [0, false];
  const n = Number(text);
  if (n > 9223372036854775807) return [0, false];
  return [n, true];
}

// Go: func CompareSemver(a Semver, b Semver) int
export function compareSemver(a: Semver, b: Semver): number {
  const an = a.parts.length;
  const bn = b.parts.length;
  let n = an;
  if (bn > n) n = bn;
  for (let i = 0; i < n; i++) {
    let ai = 0;
    let bi = 0;
    if (i < an) ai = a.parts[i];
    if (i < bn) bi = b.parts[i];
    if (ai !== bi) return ai - bi;
  }
  if ((a.preRelease !== "") !== (b.preRelease !== "")) {
    return b.preRelease.length - a.preRelease.length;
  }
  let a_tail = a.preRelease.startsWith("-") ? a.preRelease.slice(1) : a.preRelease;
  let b_tail = b.preRelease.startsWith("-") ? b.preRelease.slice(1) : b.preRelease;
  while (a_tail !== "" && b_tail !== "") {
    let a_head: string, b_head: string;
    [a_head, a_tail] = splitOffNextPreReleasePart(a_tail);
    [b_head, b_tail] = splitOffNextPreReleasePart(b_tail);
    if (a_head === b_head) continue;
    const [a_num, a_isnum] = preReleasePartToNumber(a_head);
    const [b_num, b_isnum] = preReleasePartToNumber(b_head);
    if (!a_isnum && !b_isnum) {
      // Lexicographic comparison for non-numbers (ASCII, so UTF-16 order is byte order)
      return a_head < b_head ? -1 : 1;
    } else if (a_isnum && b_isnum) {
      if (a_num !== b_num) return a_num - b_num;
      // Compare lengths for different text but equal numbers (e.g. "0" vs. "00")
      return a_head.length - b_head.length;
    } else {
      return a_isnum ? -1 : 1;
    }
  }
  return a_tail.length - b_tail.length;
}

// Go: func (v Semver) String() string
export function semverString(v: Semver): string {
  return v.parts.join(".") + v.preRelease;
}

// Go: func isVersionSupported(ranges []versionRange, version Semver) bool
function isVersionSupported(ranges: number[][], version: Semver): boolean {
  for (let i = 0; i < ranges.length; i++) {
    const r = ranges[i];
    if (compareVersions(r, 0, version) <= 0 && (r.length === 3 || compareVersions(r, 3, version) > 0)) {
      return true;
    }
  }
  return false;
}

// Go: func UnsupportedJSFeatures(constraints map[Engine]Semver) (unsupported JSFeature)
// Return all features that are not available in at least one environment
export function unsupportedJSFeatures(constraints: Map<number, Semver>): JSFeature {
  let lo = 0;
  let hi = 0;
  for (let i = 0; i < jsTable.length; i++) {
    const [feature, engines] = jsTable[i];
    if (feature === InlineScript) {
      continue; // This is purely user-specified
    }
    for (const [engine, version] of constraints) {
      let versionRanges: number[][] | null = null;
      for (let j = 0; j < engines.length; j++) {
        if (engines[j][0] === engine) {
          versionRanges = engines[j][1];
          break;
        }
      }
      if (versionRanges === null || !isVersionSupported(versionRanges, version)) {
        lo |= feature.lo;
        hi |= feature.hi;
      }
    }
  }
  return lo === 0 && hi === 0 ? JSFeatureNone : Object.freeze(new JSFeature(lo, hi));
}

// Go: func SymbolFeature(kind ast.SymbolKind) JSFeature
export function symbolFeature(kind: number): JSFeature {
  switch (kind) {
    case SymbolPrivateField:
      return ClassPrivateField;
    case SymbolPrivateMethod:
      return ClassPrivateMethod;
    case SymbolPrivateGet:
    case SymbolPrivateSet:
    case SymbolPrivateGetSetPair:
      return ClassPrivateAccessor;
    case SymbolPrivateStaticField:
      return ClassPrivateStaticField;
    case SymbolPrivateStaticMethod:
      return ClassPrivateStaticMethod;
    case SymbolPrivateStaticGet:
    case SymbolPrivateStaticSet:
    case SymbolPrivateStaticGetSetPair:
      return ClassPrivateStaticAccessor;
    default:
      return JSFeatureNone;
  }
}
`;
writeFileSync(outFile, out);
console.log(`wrote ${outFile}: ${engines.length} engines, ${features.length} features, ${rows.length} table rows`);
