// usage: node tools/gen_runtime.mjs [path/to/esbuild-src]
// Generates src/runtime.mts from internal/runtime/runtime.go by extracting the
// Go raw string literals of Source() verbatim (Go drops '\r' from raw strings).
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";

const esbuildSrc = process.argv[2] || join(tmpdir(), "esbuild-src");
const goFile = join(esbuildSrc, "internal", "runtime", "runtime.go");
const outFile = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "runtime.mts"); // (then run tools/ts-build.mjs at the repository root)

const go = readFileSync(goFile, "utf8");
const start = go.indexOf("func Source(unsupportedJSFeatures compat.JSFeature) logger.Source {");
const end = go.indexOf("return logger.Source{", start);
if (start < 0 || end < 0) throw new Error("Source() not found");
const body = go.slice(go.indexOf("text := `", start), end);

// Extract raw strings in order
const chunks = [];
for (let i = 0; i < body.length; i++) {
  if (body[i] === "`") {
    const j = body.indexOf("`", i + 1);
    if (j < 0) throw new Error("unterminated raw string");
    chunks.push(body.slice(i + 1, j).replace(/\r/g, ""));
    i = j;
  }
}
if (chunks.length !== 19) throw new Error(`expected 19 raw strings, found ${chunks.length}`);

// Check the control flow between the chunks is what the template below assumes
const conditions = [];
{
  const re = /if (!?unsupportedJSFeatures\.Has\(compat\.\w+\)(?: && !unsupportedJSFeatures\.Has\(compat\.\w+\))*) \{/g;
  let m;
  while ((m = re.exec(body)) !== null) conditions.push(m[1]);
}
const expectedConditions = [
  "!unsupportedJSFeatures.Has(compat.ForOf)",
  "!unsupportedJSFeatures.Has(compat.ForOf)",
  "!unsupportedJSFeatures.Has(compat.ForOf) && !unsupportedJSFeatures.Has(compat.ConstAndLet)",
  "!unsupportedJSFeatures.Has(compat.ObjectExtensions) && !unsupportedJSFeatures.Has(compat.ObjectAccessors)",
  "!unsupportedJSFeatures.Has(compat.ObjectAccessors)",
  "!unsupportedJSFeatures.Has(compat.ObjectAccessors)",
];
if (JSON.stringify(conditions) !== JSON.stringify(expectedConditions)) {
  throw new Error("unexpected conditions: " + JSON.stringify(conditions));
}
if ((body.replace(/`[^`]*`/g, "``").match(/\} else \{/g) || []).length !== 6) throw new Error("unexpected else count");

for (const chunk of chunks) {
  for (let i = 0; i < chunk.length; i++) {
    const c = chunk.charCodeAt(i);
    if (c > 0x7e || (c < 0x20 && c !== 9 && c !== 10)) throw new Error(`non-ASCII/control character U+${c.toString(16)} in runtime text`);
  }
}

function lit(s) {
  return "`" + s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";
}

const out = `// Port of internal/runtime/runtime.go.
//
// GENERATED by tools/gen_runtime.mjs from the Go source (the runtime text is
// copied verbatim from Go's raw string literals). Do not edit by hand.
//
// This is esbuild's runtime code. It contains helper functions that are
// automatically injected into output files to implement certain features. For
// example, the "**" operator is replaced with a call to "__pow" when targeting
// ES2015. Tree shaking automatically removes unused code from the runtime.
import { Path, PrettyPaths, Source } from "./logger.mjs";

// The runtime source is always at a special index. The index is always zero
// but this constant is always used instead to improve readability and ensure
// all code that references this index can be discovered easily.
export const SourceIndex = 0;

// Bit positions of the compat.JSFeature values used below ("1 << iota" order
// in internal/compat/js_table.go). The fast path always passes 0.
const ConstAndLet = 17;
const ForOf = 25;
const ObjectAccessors = 43;
const ObjectExtensions = 44;

// compat.JSFeature.Has. "features" is a number or a bigint bit set.
function has(features, bit) {
  if (!features) return false;
  if (typeof features === "bigint") return ((features >> BigInt(bit)) & 1n) !== 0n;
  return Math.floor(features / 2 ** bit) % 2 === 1;
}

const textCache = new Map();

function sourceText(unsupportedJSFeatures) {
  // Note: These helper functions used to be named similar things to the helper
  // functions from the TypeScript compiler. However, people sometimes use these
  // two projects in combination and TypeScript's implementation of these helpers
  // causes name collisions. See runtime.go for details.
  let text = ${lit(chunks[0])};

  // Avoid "of" when not using ES6
  if (!has(unsupportedJSFeatures, ForOf)) {
    text += ${lit(chunks[1])};
  } else {
    text += ${lit(chunks[2])};
  }

  text += ${lit(chunks[3])};

  // Avoid "of" when not using ES6
  if (!has(unsupportedJSFeatures, ForOf)) {
    text += ${lit(chunks[4])};
  } else {
    text += ${lit(chunks[5])};
  }

  text += ${lit(chunks[6])};

  // Avoid "let" when not using ES6
  if (!has(unsupportedJSFeatures, ForOf) && !has(unsupportedJSFeatures, ConstAndLet)) {
    text += ${lit(chunks[7])};
  } else {
    text += ${lit(chunks[8])};
  }

  text += ${lit(chunks[9])};

  // Avoid object extensions when not using ES6
  if (!has(unsupportedJSFeatures, ObjectExtensions) && !has(unsupportedJSFeatures, ObjectAccessors)) {
    text += ${lit(chunks[10])};
  } else {
    text += ${lit(chunks[11])};
  }

  text += ${lit(chunks[12])};

  if (!has(unsupportedJSFeatures, ObjectAccessors)) {
    text += ${lit(chunks[13])};
  } else {
    text += ${lit(chunks[14])};
  }

  text += ${lit(chunks[15])};

  if (!has(unsupportedJSFeatures, ObjectAccessors)) {
    text += ${lit(chunks[16])};
  } else {
    text += ${lit(chunks[17])};
  }

  text += ${lit(chunks[18])};

  return text;
}

// Go: runtime.Source(unsupportedJSFeatures). Returns a fresh logger.Source
// each time (the text itself is cached per feature set).
export function source(unsupportedJSFeatures) {
  const key = typeof unsupportedJSFeatures === "bigint" ? unsupportedJSFeatures : BigInt(unsupportedJSFeatures || 0);
  let text = textCache.get(key);
  if (text === undefined) {
    text = sourceText(unsupportedJSFeatures);
    textCache.set(key, text);
  }
  return new Source(new PrettyPaths("<runtime>", "<runtime>"), "runtime", text, new Path("<runtime>"), SourceIndex);
}
`;

writeFileSync(outFile, out);
console.log(`wrote ${outFile} (${chunks.length} raw strings)`);
