// usage: node tools/gen_compat_css.mjs [path/to/esbuild-src]
// Generates src/compat_css.mts (the CSS half of internal/compat: CSSFeature,
// StringToCSSFeature, UnsupportedCSSFeatures, CSSPrefix and CSSPrefixData)
// from internal/compat/css_table.go.
// (Then run tools/ts-build.mjs at the repository root.)
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";

const esbuildSrc = process.argv[2] || join(tmpdir(), "esbuild-src");
const goFile = join(esbuildSrc, "internal", "compat", "css_table.go");
const outFile = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "compat_css.mts");
const go = readFileSync(goFile, "utf8").replace(/\r/g, "");

function block(start, end = "\n)\n") {
  const i = go.indexOf(start);
  if (i < 0) throw new Error("not found: " + start);
  const j = go.indexOf(end, i + start.length);
  return go.slice(i + start.length, j);
}

// CSSFeature ("1 << iota" order)
const features = block("type CSSFeature uint16\n\nconst (\n")
  .split("\n")
  .map((l) => l.trim())
  .filter(Boolean)
  .map((l) => l.split(" ")[0]);
if (features[0] !== "ColorFunctions" || features.length > 16) throw new Error("unexpected features");
const stringToFeature = [];
for (const m of block("var StringToCSSFeature = map[string]CSSFeature{\n", "\n}\n").matchAll(/"([^"]+)":\s+(\w+),/g)) {
  stringToFeature.push([m[1], m[2]]);
}
if (stringToFeature.length !== features.length) throw new Error("StringToCSSFeature size");

// cssTable
const table = block("var cssTable = map[CSSFeature]map[Engine][]versionRange{\n", "\n}\n\n");
const rows = [];
{
  const re = /^\t(\w+): \{(\}|\n([\s\S]*?)\n\t\}),$/gm;
  let m;
  while ((m = re.exec(table)) !== null) {
    const feature = m[1];
    const body = m[3] || "";
    const perEngine = [];
    for (const line of body.split("\n")) {
      const t = line.trim();
      if (t === "" || t.startsWith("//")) continue;
      const em = t.match(/^(\w+):\s+\{(.*)\},$/);
      if (!em) throw new Error("bad line: " + t);
      const ranges = [];
      for (const r of em[2].matchAll(/\{start: v\{(\d+), (\d+), (\d+)\}(?:, end: v\{(\d+), (\d+), (\d+)\})?\}/g)) {
        ranges.push(r[4] === undefined ? [+r[1], +r[2], +r[3]] : [+r[1], +r[2], +r[3], +r[4], +r[5], +r[6]]);
      }
      if (ranges.length === 0) throw new Error("no ranges: " + t);
      perEngine.push([em[1], ranges]);
    }
    rows.push([feature, perEngine]);
  }
}
if (rows.length !== features.length) throw new Error("cssTable size " + rows.length);

// CSSPrefix ("1 << iota" order, then NoPrefix = 0)
const prefixes = block("type CSSPrefix uint8\n\nconst (\n")
  .split("\n")
  .map((l) => l.trim())
  .filter((l) => l !== "" && !l.startsWith("NoPrefix"))
  .map((l) => l.split(" ")[0]);
if (prefixes[0] !== "KhtmlPrefix") throw new Error("unexpected prefixes");

// cssPrefixTable
const prefixTable = block("var cssPrefixTable = map[css_ast.D][]prefixData{\n", "\n}\n\n");
const prefixRows = [];
{
  const re = /^\tcss_ast\.(\w+): \{\n([\s\S]*?)\n\t\},$/gm;
  let m;
  while ((m = re.exec(prefixTable)) !== null) {
    const items = [];
    for (const line of m[2].split("\n")) {
      const t = line.trim();
      if (t === "") continue;
      const im = t.match(/^\{engine: (\w+), prefix: (\w+)(?:, withoutPrefix: v\{(\d+), (\d+), (\d+)\})?\},$/);
      if (!im) throw new Error("bad prefix line: " + t);
      items.push([im[1], im[2], im[3] === undefined ? [0, 0, 0] : [+im[3], +im[4], +im[5]]]);
    }
    prefixRows.push([m[1], items]);
  }
}
if (prefixRows.length === 0) throw new Error("no prefix rows");

const engines = new Set();
for (const [, perEngine] of rows) for (const [e] of perEngine) engines.add(e);
for (const [, items] of prefixRows) for (const [e] of items) engines.add(e);
const decls = prefixRows.map((r) => r[0]);

let out = `// Generated by tools/gen_compat_css.mjs from esbuild's internal/compat/css_table.go.
// Do not edit by hand.
//
// compat.CSSFeature is a uint16 bit set in Go: a number here. CSSPrefix is a
// bit set too. CSSPrefixData returns a Map<D, CSSPrefix> or null (Go: nil).
import { ${[...engines].sort().join(", ")}, engineIsBrowser } from "./compat.mjs";
import type { Semver } from "./compat.mjs";
import { ${decls.join(", ")} } from "./css_ast.mjs";

// CSSFeature
${features.map((f, i) => `export const ${f} = ${1 << i};`).join("\n")}

export const StringToCSSFeature: Map<string, number> = new Map([
${stringToFeature.map(([s, f]) => `  [${JSON.stringify(s)}, ${f}],`).join("\n")}
]);

// Go: func (features CSSFeature) Has(feature CSSFeature) bool
export function cssFeatureHas(features: number, feature: number): boolean {
  return (features & feature) !== 0;
}

// Go: func (features CSSFeature) ApplyOverrides(overrides CSSFeature, mask CSSFeature) CSSFeature
export function cssFeatureApplyOverrides(features: number, overrides: number, mask: number): number {
  return (features & ~mask) | (overrides & mask);
}

// [feature, [[engine, [[start major, minor, patch(, end major, minor, patch)], ...]], ...]]
const cssTable: [number, [number, number[][]][]][] = [
${rows.map(([f, pe]) => `  [${f}, [${pe.map(([e, r]) => `[${e}, ${JSON.stringify(r)}]`).join(", ")}]],`).join("\n")}
];

// Go: func compareVersions(a v, b Semver) int. "a" is [major, minor, patch]
// at offset "i".
function compareVersions(a: number[], i: number, b: Semver): number {
  let diff = a[i];
  if (b.parts.length > 0) diff -= b.parts[0];
  if (diff === 0) {
    diff = a[i + 1];
    if (b.parts.length > 1) diff -= b.parts[1];
  }
  if (diff === 0) {
    diff = a[i + 2];
    if (b.parts.length > 2) diff -= b.parts[2];
  }
  if (diff === 0 && b.preRelease.length !== 0) {
    return 1; // "1.0.0" > "1.0.0-alpha"
  }
  return diff;
}

// Go: func isVersionSupported(ranges []versionRange, version Semver) bool
function isVersionSupported(ranges: number[][], version: Semver): boolean {
  for (let i = 0; i < ranges.length; i++) {
    const r = ranges[i];
    if (compareVersions(r, 0, version) <= 0 && (r.length === 3 || compareVersions(r, 3, version) > 0)) {
      return true;
    }
  }
  return false;
}

// Go: func UnsupportedCSSFeatures(constraints map[Engine]Semver) (unsupported CSSFeature)
// Return all features that are not available in at least one environment
export function unsupportedCSSFeatures(constraints: Map<number, Semver>): number {
  let unsupported = 0;
  for (let i = 0; i < cssTable.length; i++) {
    const feature = cssTable[i][0];
    const engines = cssTable[i][1];
    if (feature === InlineStyle) {
      continue; // This is purely user-specified
    }
    for (const [engine, version] of constraints) {
      if (!engineIsBrowser(engine)) {
        // Specifying "--target=es2020" shouldn't affect CSS
        continue;
      }
      let versionRanges: number[][] | null = null;
      for (let j = 0; j < engines.length; j++) {
        if (engines[j][0] === engine) {
          versionRanges = engines[j][1];
          break;
        }
      }
      if (versionRanges === null || !isVersionSupported(versionRanges, version)) {
        unsupported |= feature;
      }
    }
  }
  return unsupported;
}

// CSSPrefix
${prefixes.map((p, i) => `export const ${p} = ${1 << i};`).join("\n")}
export const NoPrefix = 0;

// [D, [[engine, prefix, withoutPrefix ([0, 0, 0] for Go's v{})], ...]]
const cssPrefixTable: [number, [number, number, number[]][]][] = [
${prefixRows.map(([d, items]) => `  [${d}, [${items.map(([e, p, v]) => `[${e}, ${p}, ${JSON.stringify(v)}]`).join(", ")}]],`).join("\n")}
];

// Go: func CSSPrefixData(constraints map[Engine]Semver) (entries map[css_ast.D]CSSPrefix)
export function cssPrefixData(constraints: Map<number, Semver>): Map<number, number> | null {
  let entries: Map<number, number> | null = null;
  for (let i = 0; i < cssPrefixTable.length; i++) {
    const property = cssPrefixTable[i][0];
    const items = cssPrefixTable[i][1];
    let prefixes = NoPrefix;
    for (const [engine, version] of constraints) {
      if (!engineIsBrowser(engine)) {
        // Specifying "--target=es2020" shouldn't affect CSS
        continue;
      }
      for (let j = 0; j < items.length; j++) {
        const item = items[j];
        const v = item[2];
        if (item[0] === engine && ((v[0] === 0 && v[1] === 0 && v[2] === 0) || compareVersions(v, 0, version) > 0)) {
          prefixes |= item[1];
        }
      }
    }
    if (prefixes !== NoPrefix) {
      if (entries === null) {
        entries = new Map();
      }
      entries.set(property, prefixes);
    }
  }
  return entries;
}
`;
writeFileSync(outFile, out);
console.log(`wrote ${outFile}: ${features.length} features, ${prefixRows.length} prefixed properties`);
