// usage: node tools/gen_unicode_tables.mjs [path/to/go/src/unicode/tables.go]
// Regenerates src/unicode_tables.mts from Go's unicode tables (Unicode 15.0.0
// in go1.26.5, which esbuild 0.28.2 is built with; default path:
// <os tmpdir>/gosrc/src/unicode/tables.go, from
// https://raw.githubusercontent.com/golang/go/go1.26.5/src/unicode/tables.go).
// Only what Go's regexp/syntax uses: Categories, Scripts, FoldCategory,
// FoldScript, CategoryAliases, CaseRanges, asciiFold and caseOrbit.
//
// A range table is a string of ranges joined by ",": each range is
// base36(lo - previous hi) [":" base36(hi - lo)] ["/" base36(stride)] (the
// length is left out when 0, the stride when 1). R16 and R32 are one list
// (every R16 range is below every R32 range).
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";

const here = dirname(fileURLToPath(import.meta.url));
const file = process.argv[2] || resolve(tmpdir(), "gosrc/src/unicode/tables.go");
const go = readFileSync(file, "utf8");
const version = /const Version = "([^"]+)"/.exec(go)[1];
if (version !== "15.0.0") throw new Error("expected Unicode 15.0.0 (go1.26.5), found " + version);

// var _X = &RangeTable{ ... } and var foldX = &RangeTable{ ... }
const tables = new Map();
for (const m of go.matchAll(/^var (\w+) = &RangeTable\{\n([\s\S]*?)\n\}/gm)) {
  const ranges = [];
  for (const r of m[2].matchAll(/\{0x([0-9a-f]+), 0x([0-9a-f]+), (\d+)\}/g)) ranges.push([parseInt(r[1], 16), parseInt(r[2], 16), +r[3]]);
  tables.set(m[1], ranges);
}
// X = _X aliases
const alias = new Map();
for (const m of go.matchAll(/^\t(\w+)\s+= (_\w+)( |$)/gm)) alias.set(m[1], m[2]);
const table = (name) => {
  const t = tables.get(name) || tables.get(alias.get(name));
  if (!t) throw new Error("missing table " + name);
  return t;
};
const mapOf = (varName, valueRe) => {
  const body = new RegExp("^var " + varName + " = map\\[string\\]\\*?\\w+\\{\\n([\\s\\S]*?)\\n\\}", "m").exec(go)[1];
  const entries = [];
  for (const m of body.matchAll(valueRe)) entries.push([m[1], m[2]]);
  return entries;
};

function encode(ranges) {
  let prev = 0;
  const out = [];
  for (const [lo, hi, stride] of ranges) {
    if (lo < prev) throw new Error("unsorted ranges");
    let s = (lo - prev).toString(36);
    if (hi !== lo) s += ":" + (hi - lo).toString(36);
    if (stride !== 1) s += "/" + stride.toString(36);
    out.push(s);
    prev = hi;
  }
  return out.join(",");
}

const entryRe = /"(\w+)":\s+(\w+),/g;
const categories = mapOf("Categories", entryRe);
const scripts = mapOf("Scripts", entryRe);
const foldCategory = mapOf("FoldCategory", entryRe);
const foldScript = mapOf("FoldScript", entryRe);
const categoryAliases = mapOf("CategoryAliases", /"(\w+)":\s+"(\w+)",/g);

// CaseRanges: [lo, hi, upper, lower, title], UpperLower = MaxRune + 1
const caseBody = /^var _CaseRanges = \[\]CaseRange\{\n([\s\S]*?)\n\}/m.exec(go)[1];
const caseRanges = [];
const UL = 0x110000;
for (const m of caseBody.matchAll(/\{0x([0-9A-F]+), 0x([0-9A-F]+), d\{([^}]*)\}\}/g)) {
  const d = m[3].split(",").map((x) => (x.trim() === "UpperLower" ? UL : +x.trim()));
  caseRanges.push([parseInt(m[1], 16), parseInt(m[2], 16), ...d]);
}
const asciiFold = [...(/^var asciiFold = \[MaxASCII \+ 1\]uint16\{\n([\s\S]*?)\n\}/m.exec(go)[1]).matchAll(/0x([0-9A-F]+)/g)].map((m) => parseInt(m[1], 16));
if (asciiFold.length !== 128) throw new Error("asciiFold");
const caseOrbit = [...(/^var caseOrbit = \[\]foldPair\{\n([\s\S]*?)\n\}/m.exec(go)[1]).matchAll(/\{0x([0-9A-F]+), 0x([0-9A-F]+)\}/g)].map((m) => [parseInt(m[1], 16), parseInt(m[2], 16)]);

const lit = (entries) => "{\n" + entries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n") + "\n}";
let out = `// Generated by tools/gen_unicode_tables.mjs from Go's unicode/tables.go
// (Unicode ${version}, go1.26.5): the tables Go's regexp/syntax uses. See the
// generator for the encoding. Do not edit.

// Categories, Scripts, FoldCategory, FoldScript: name -> encoded range table
export const CATEGORIES: Record<string, string> = ${lit(categories.map(([k, v]) => [k, encode(table(v))]))};
export const SCRIPTS: Record<string, string> = ${lit(scripts.map(([k, v]) => [k, encode(table(v))]))};
export const FOLD_CATEGORY: Record<string, string> = ${lit(foldCategory.map(([k, v]) => [k, encode(table(v))]))};
export const FOLD_SCRIPT: Record<string, string> = ${lit(foldScript.map(([k, v]) => [k, encode(table(v))]))};
export const CATEGORY_ALIASES: Record<string, string> = ${lit(categoryAliases)};
// CaseRanges: lo, hi - lo, upper, lower, title deltas (base 36, "u" for UpperLower), ";" between ranges
export const CASE_RANGES = ${JSON.stringify(caseRanges.map(([lo, hi, u, l, t]) => [lo, hi - lo, u, l, t].map((x) => (x === UL ? "u" : x.toString(36))).join(",")).join(";"))};
// asciiFold[0..127]
export const ASCII_FOLD = ${JSON.stringify(asciiFold)};
// caseOrbit: from, to pairs
export const CASE_ORBIT = ${JSON.stringify(caseOrbit.flat())};
`;
writeFileSync(resolve(here, "../src/unicode_tables.mts"), out);
console.log(`src/unicode_tables.mts: ${categories.length} categories, ${scripts.length} scripts, ${caseRanges.length} case ranges, ${(out.length / 1024).toFixed(0)} KB`);
