// Generates regexp.mjs from acorn 8.18.0 (node_modules): acorn's regular
// expression validator (regexp.js + unicode-property-data.js), the same code
// with the parser and state objects turned into module-level variables and
// functions, so that a minifier can shorten every name:
//   pp$1.regexp_x = function(state, a) {...}   ->  function regexp_x(a) {...}
//   this.regexp_x(state, a)                    ->  regexp_x(a)
//   state.field / state.method(...)            ->  r_field / r_method(...)
//   this.options.ecmaVersion                   ->  ecmaVersion
//   this.raise(pos, msg), state.raise(msg)     ->  the parser's raise(pos, msg)
// The Unicode property tables are built on first use instead of at load.
// Entry point: validateRegExp(ecmaVersion, raise, start, pattern, flags).
//   node packages/fast-acorn/tools/gen-regexp.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as acorn from "acorn";
import MagicString from "magic-string";

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(join(here, "../../../package.json"));
const acornDir = dirname(require.resolve("acorn/package.json"));
const pkg = JSON.parse(readFileSync(join(acornDir, "package.json"), "utf8"));
if (pkg.version !== "8.18.0") throw new Error("expected acorn 8.18.0, found " + pkg.version);
const full = readFileSync(join(acornDir, "dist/acorn.mjs"), "utf8");

const BEGIN = '// This file was generated by "bin/generate-unicode-script-values.js". Do not modify manually!';
const END = "// Object type used to represent tokens.";
const b = full.indexOf(BEGIN), e = full.indexOf(END);
if (b < 0 || e < b) throw new Error("regexp section not found");
const src = full.slice(b, e);
const ast = acorn.parse(src, { ecmaVersion: "latest", sourceType: "script" });
const ms = new MagicString(src);

// pp$1 methods and RegExpValidationState's fields / methods
const methods = new Set();
const stateMethods = new Set();
const stateFields = new Set();
for (const st of ast.body) {
  if (st.type !== "ExpressionStatement" || st.expression.type !== "AssignmentExpression") continue;
  const l = st.expression.left;
  if (l.type === "MemberExpression" && l.object.type === "Identifier" && l.object.name === "pp$1") methods.add(l.property.name);
  if (l.type === "MemberExpression" && l.object.type === "MemberExpression" && l.object.object.name === "RegExpValidationState") stateMethods.add(l.property.name);
}
for (const st of ast.body) {
  if (st.type === "VariableDeclaration" && st.declarations[0].id.name === "RegExpValidationState") {
    for (const s of st.declarations[0].init.body.body) {
      if (s.type === "ExpressionStatement" && s.expression.type === "AssignmentExpression" && s.expression.left.type === "MemberExpression") stateFields.add(s.expression.left.property.name);
    }
  }
}
stateFields.delete("parser");
if (methods.size < 50 || stateMethods.size < 8 || stateFields.size < 15) throw new Error("unexpected regexp.js structure");

function walk(n, parent, fn) {
  if (!n || typeof n.type !== "string") return;
  if (fn(n, parent) === false) return;
  for (const k in n) {
    const v = n[k];
    if (Array.isArray(v)) for (const c of v) walk(c, n, fn);
    else if (v && typeof v.type === "string") walk(v, n, fn);
  }
}
const isThis = (n) => n.type === "ThisExpression";
const isId = (n, name) => n.type === "Identifier" && (name === undefined || n.name === name);

// remove the leading `state` argument of calls / parameter of functions
function dropFirstArg(node, args) {
  if (args.length === 0) throw new Error("no argument to drop at " + node.start);
  if (args.length > 1) ms.remove(args[0].start, args[1].start);
  else ms.remove(args[0].start, args[0].end);
}

const skip = new Set();
for (const st of ast.body) {
  // var pp$1 = Parser.prototype;
  if (st.type === "VariableDeclaration" && st.declarations[0].id.name === "pp$1") {
    ms.remove(st.start, st.end);
    skip.add(st);
    continue;
  }
  // the RegExpValidationState constructor -> module variables
  if (st.type === "VariableDeclaration" && st.declarations[0].id.name === "RegExpValidationState") {
    ms.overwrite(st.start, st.end, "var " + [...stateFields].map((f) => "r_" + f).join(", ") + ";\nr_backReferenceNames = [];");
    skip.add(st);
    continue;
  }
  // the eager Unicode data build loop -> removed (built on demand)
  if (st.type === "ForStatement" && src.slice(st.start, st.end).includes("buildUnicodeData")) {
    ms.remove(st.start, st.end);
    skip.add(st);
    continue;
  }
  if (st.type === "ExpressionStatement" && st.expression.type === "AssignmentExpression") {
    const l = st.expression.left, fnNode = st.expression.right;
    // pp$1.x = function(state, ...) -> function x(...)
    if (l.type === "MemberExpression" && isId(l.object, "pp$1")) {
      ms.overwrite(st.start, fnNode.start, "");
      ms.overwrite(fnNode.start, fnNode.start + "function".length, "function " + l.property.name);
      if (!fnNode.params.length || !isId(fnNode.params[0], "state")) throw new Error("expected state parameter: " + l.property.name);
      dropFirstArg(fnNode, fnNode.params);
      if (src[st.end - 1] === ";") ms.remove(st.end - 1, st.end);
    }
    // RegExpValidationState.prototype.x = function x(...) -> function r_x(...)
    else if (l.type === "MemberExpression" && l.object.type === "MemberExpression" && isId(l.object.object, "RegExpValidationState")) {
      ms.overwrite(st.start, fnNode.start, "");
      if (fnNode.id) ms.overwrite(fnNode.id.start, fnNode.id.end, "r_" + l.property.name);
      else ms.appendLeft(fnNode.start + "function".length, " r_" + l.property.name);
      if (src[st.end - 1] === ";") ms.remove(st.end - 1, st.end);
    }
  }
}

walk(ast, null, (n) => {
  if (skip.has(n)) return false;
  // this.options.ecmaVersion / this.parser.options.ecmaVersion -> ecmaVersion
  const isParserOpts = (o) => o.type === "MemberExpression" && o.property.name === "options" && (isThis(o.object) || (o.object.type === "MemberExpression" && isThis(o.object.object) && o.object.property.name === "parser"));
  if (n.type === "MemberExpression" && isParserOpts(n.object) && n.property.name === "ecmaVersion") {
    ms.overwrite(n.start, n.end, "ecmaVersion");
    return false;
  }
  // this.parser.raiseRecoverable(this.start, msg) (in state.raise) -> raise(r_start, msg)
  if (n.type === "CallExpression" && n.callee.type === "MemberExpression" && n.callee.object.type === "MemberExpression" && isThis(n.callee.object.object) && n.callee.object.property.name === "parser") {
    ms.overwrite(n.callee.start, n.callee.end, "raise");
    for (const a of n.arguments) walkThis(a);
    return false;
  }
  if (n.type === "CallExpression" && n.callee.type === "MemberExpression" && !n.callee.computed) {
    const obj = n.callee.object, name = n.callee.property.name;
    // this.regexp_x(state, ...) -> regexp_x(...)
    if (isThis(obj) && methods.has(name)) {
      ms.remove(obj.start, n.callee.property.start);
      if (!isId(n.arguments[0], "state")) throw new Error("expected state argument at " + n.start);
      dropFirstArg(n, n.arguments);
      return;
    }
    // this.raise(pos, msg) -> raise(pos, msg)
    if (isThis(obj) && name === "raise") {
      ms.remove(obj.start, n.callee.property.start);
      return;
    }
    // state.m(...) -> r_m(...)
    if (isId(obj, "state") && stateMethods.has(name)) {
      ms.overwrite(obj.start, n.callee.property.end, "r_" + name);
      return;
    }
    // this.m(...) inside the state's own methods -> r_m(...)
    if (isThis(obj) && stateMethods.has(name)) {
      ms.overwrite(obj.start, n.callee.property.end, "r_" + name);
      return;
    }
  }
  // state.field / this.field (inside state methods) -> r_field
  if (n.type === "MemberExpression" && !n.computed && (isId(n.object, "state") || isThis(n.object)) && stateFields.has(n.property.name)) {
    if (n.property.name === "unicodeProperties") ms.overwrite(n.start, n.end, "unicodeProperties()");
    else ms.overwrite(n.start, n.end, "r_" + n.property.name);
    return false;
  }
});
function walkThis(a) {
  walk(a, null, (n) => {
    if (n.type === "MemberExpression" && !n.computed && isThis(n.object) && stateFields.has(n.property.name)) {
      ms.overwrite(n.start, n.end, "r_" + n.property.name);
      return false;
    }
  });
}

let out = ms.toString();
// anything left that still refers to the parser or a state object is a bug
walk(acorn.parse(out, { ecmaVersion: "latest", sourceType: "script" }), null, (n) => {
  const bad =
    (n.type === "Identifier" && (n.name === "state" || n.name === "pp$1" || n.name === "Parser")) ||
    (n.type === "MemberExpression" && isThis(n.object) && n.property.name !== "parent" && n.property.name !== "base");
  if (bad) throw new Error("leftover at: " + out.slice(Math.max(0, n.start - 120), n.end + 40));
});

const header = `// Generated by tools/gen-regexp.mjs from acorn ${pkg.version} (MIT, Marijn Haverbeke and contributors). Do not edit.
// acorn's regular expression validator with its parser / state objects
// turned into module-level variables and functions (see the tool).
import { isIdentifierStart, isIdentifierChar } from "./shared.mjs";

var ecmaVersion = 0, raise = null;
var hasOwn = Object.hasOwn || function (obj, propName) { return Object.prototype.hasOwnProperty.call(obj, propName) };
var regexpCache = Object.create(null);
function wordsRegexp(words) {
  return regexpCache[words] || (regexpCache[words] = new RegExp("^(?:" + words.replace(/ /g, "|") + ")$"))
}
function codePointToString(code) {
  if (code <= 0xFFFF) { return String.fromCharCode(code) }
  code -= 0x10000;
  return String.fromCharCode((code >> 10) + 0xD800, (code & 1023) + 0xDC00)
}
function unicodeProperties() {
  var v = ecmaVersion >= 14 ? 14 : ecmaVersion;
  if (!data[v]) { buildUnicodeData(v); }
  return data[v]
}

`;
const footer = `
// Validate a regular expression literal like acorn's readRegexp does
// (RegExpValidationState + validateRegExpFlags + validateRegExpPattern);
// errors go to raise(pos, message).
export function validateRegExp(ecma, raiseFn, start, pattern, flags) {
  ecmaVersion = ecma;
  raise = raiseFn;
  r_validFlags = "gim" + (ecma >= 6 ? "uy" : "") + (ecma >= 9 ? "s" : "") + (ecma >= 13 ? "d" : "") + (ecma >= 15 ? "v" : "");
  r_reset(start, pattern, flags);
  validateRegExpFlags();
  validateRegExpPattern();
}
`;
writeFileSync(join(here, "../src/regexp.mjs"), header + out.replace(/\n{3,}/g, "\n\n") + footer);
console.log(`wrote regexp.mjs: ${methods.size} validator functions, ${stateMethods.size} state methods, ${stateFields.size} state fields`);
