// Generates ident-data.mts from acorn 8.18.0 (node_modules): acorn's
// identifier tables (nonASCIIidentifierStartChars / nonASCIIidentifierChars,
// astralIdentifierStartCodes / astralIdentifierCodes) as one compact string
// of code point ranges, decoded by shared.mts. Checks that the decoded
// ranges give exactly acorn's isIdentifierStart / isIdentifierChar for every
// code point.   node packages/fast-acorn/tools/gen-ident.mjs
// (then node tools/ts-build.mjs for ident-data.mjs)
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(join(here, "../../../package.json"));
const acornDir = dirname(require.resolve("acorn/package.json"));
const pkg = JSON.parse(readFileSync(join(acornDir, "package.json"), "utf8"));
if (pkg.version !== "8.18.0") throw new Error("expected acorn 8.18.0, found " + pkg.version);
const src = readFileSync(join(acornDir, "dist/acorn.mjs"), "utf8");
const grab = (name) => {
  const m = src.match(new RegExp("var " + name + " = ([^;]*);"));
  if (!m) throw new Error("not found: " + name);
  return new Function("return " + m[1])();
};
const astralIdentifierCodes = grab("astralIdentifierCodes");
const astralIdentifierStartCodes = grab("astralIdentifierStartCodes");
const nonASCIIidentifierChars = grab("nonASCIIidentifierChars");
const nonASCIIidentifierStartChars = grab("nonASCIIidentifierStartChars");

// BMP class string -> sorted, merged [lo, hi] ranges
function classRanges(cls) {
  const re = new RegExp("[" + cls + "]");
  const out = [];
  for (let c = 0; c <= 0xffff; c++) {
    if (!re.test(String.fromCharCode(c))) continue;
    if (out.length && out[out.length - 1][1] === c - 1) out[out.length - 1][1] = c;
    else out.push([c, c]);
  }
  return out;
}
// acorn's astral encoding: from 0x10000, pairs (gap, size); a range is [pos, pos + size]
function astralRanges(set) {
  const out = [];
  let pos = 0x10000;
  for (let i = 0; i < set.length; i += 2) {
    pos += set[i];
    const lo = pos;
    pos += set[i + 1];
    out.push([lo, pos]);
  }
  return out;
}
const bmpStart = classRanges(nonASCIIidentifierStartChars);
// (acorn's part set is start + chars: only the chars list is stored)
const bmpChars = classRanges(nonASCIIidentifierChars);
const bmpPart = classRanges(nonASCIIidentifierStartChars + nonASCIIidentifierChars);
const astStart = astralRanges(astralIdentifierStartCodes);
const astPart = astralRanges(astralIdentifierCodes);

// Encoding: each list is (count, then per range: gap from the previous
// range's end, length) as base-45 varints over printable ASCII (no quote or
// backslash): digits 0..44 end a number, 45..89 continue it.
const ALPHA = [];
for (let c = 35; c < 127 && ALPHA.length < 90; c++) if (c !== 92) ALPHA.push(String.fromCharCode(c));
function enc(n) {
  if (n < 0 || !Number.isInteger(n)) throw new Error("bad number " + n);
  const digits = [n % 45];
  n = Math.floor(n / 45);
  while (n > 0) {
    digits.push(45 + (n % 45));
    n = Math.floor(n / 45);
  }
  return digits.reverse().map((d) => ALPHA[d]).join("");
}
function encList(ranges, base) {
  let s = enc(ranges.length), prev = base;
  for (const [lo, hi] of ranges) {
    s += enc(lo - prev) + enc(hi - lo);
    prev = hi;
  }
  return s;
}
const data = encList(bmpStart, 0) + encList(bmpChars, 0) + encList(astStart, 0x10000) + encList(astPart, 0x10000);

// ---- check: decode like shared.mts and compare with acorn for every code point
function decode(s) {
  let i = 0;
  const num = () => {
    let n = 0, d;
    while ((d = s.charCodeAt(i++) - 35 - (s.charCodeAt(i - 1) > 92 ? 1 : 0)) >= 45) n = n * 45 + d - 45;
    return n * 45 + d;
  };
  const lists = [];
  for (let k = 0; k < 4; k++) {
    const n = num(), out = [];
    let prev = k < 2 ? 0 : 0x10000;
    for (let j = 0; j < n; j++) {
      const lo = prev + num();
      prev = lo + num();
      out.push([lo, prev]);
    }
    lists.push(out);
  }
  return lists;
}
const dec = decode(data);
const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);
if (!same(dec, [bmpStart, bmpChars, astStart, astPart])) throw new Error("decode mismatch");
const acorn = await import("acorn");
const inR = (rs, c) => rs.some(([lo, hi]) => c >= lo && c <= hi);
for (let c = 0; c <= 0x10ffff; c++) {
  const s = c < 0x80 ? acorn.isIdentifierStart(c, true) : c <= 0xffff ? c >= 0xaa && inR(bmpStart, c) : inR(astStart, c);
  const p = c < 0x80 ? acorn.isIdentifierChar(c, true) : c <= 0xffff ? c >= 0xaa && inR(bmpPart, c) : inR(astStart, c) || inR(astPart, c);
  if (s !== acorn.isIdentifierStart(c, true) || p !== acorn.isIdentifierChar(c, true)) throw new Error("mismatch at " + c.toString(16));
}

const out = `// Generated by tools/gen-ident.mjs from acorn ${pkg.version} (MIT). Do not edit.
// acorn's identifier tables (BMP start / BMP part-only, astral start /
// astral part) as ranges: per list a count, then per range the gap from the
// previous range's end and its length, as base-45 varints (see shared.mts).
export const IDENT_DATA = ${JSON.stringify(data)};
`;
writeFileSync(join(here, "../src/ident-data.mts"), out);
console.log(`wrote ident-data.mts: ${data.length} chars (ranges: ${bmpStart.length} ${bmpChars.length} ${astStart.length} ${astPart.length})`);
