// Generated by tools/gen-jsx-data.mjs from acorn-jsx 5.3.2 (MIT). Do not edit.
// What recognises the genuine acorn-jsx plugin class (see jsx-detect.mts).

// the class's source text: hash and length
export const JSX_CLASS = [442820490339230, 12575];
// the prototype's methods (besides the constructor)
export const JSX_METHODS = "jsx_readToken jsx_readNewLine jsx_readString jsx_readEntity jsx_readWord jsx_parseIdentifier jsx_parseNamespacedName jsx_parseElementName jsx_parseAttributeValue jsx_parseEmptyExpression jsx_parseExpressionContainer jsx_parseAttribute jsx_parseOpeningElementAt jsx_parseClosingElementAt jsx_parseElementAt jsx_parseText jsx_parseElement parseExprAtom readToken updateContext";
// hashes of jsxTagStart's and jsxTagEnd's updateContext sources
export const JSX_UPDATE_CONTEXT = [2615728569792015, 8513977705428465];
// generated from jsx-data.mts by tools/ts-build.mjs; edit that file
