// generated by build.mjs from esm/_fast.js — do not edit
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  FAST: () => FAST,
  defineFast: () => defineFast,
  fastDigestInto: () => fastDigestInto,
  fastHasher: () => fastHasher,
  fastPbkdf2: () => fastPbkdf2,
  fastPbkdf2Async: () => fastPbkdf2Async,
  fastPrf: () => fastPrf,
  fastScrypt: () => fastScrypt,
  fastScryptRun: () => fastScryptRun,
  fastScryptRunAsync: () => fastScryptRunAsync,
  fastUpdate: () => fastUpdate,
  scratchIsClean: () => scratchIsClean,
  wasmActive: () => wasmActive
});
module.exports = __toCommonJS(stdin_exports);
var import_fastwasm = __toESM(require("./_fastwasm.js"));
var import_utils = require("./utils.js");
const FAST = /* @__PURE__ */ Symbol("fast-noble-hashes");
const A_SHA256 = 0, A_SHA512 = 1, A_SHA1 = 2, A_MD5 = 3;
function b64decode(s) {
  if (typeof Buffer === "function") return new Uint8Array(Buffer.from(s, "base64"));
  if (typeof Uint8Array.fromBase64 === "function") return Uint8Array.fromBase64(s);
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
let MOD = null;
let W = null;
let m8, m32, ioView, IO, FIN, OUT, ST, ST2, U, T, CAP, ST32, ST232;
function initWasm(mod) {
  const w = new WebAssembly.Instance(mod, {}).exports;
  m8 = new Uint8Array(w.memory.buffer);
  m32 = new Int32Array(w.memory.buffer);
  IO = w.offset(0);
  FIN = w.offset(1);
  OUT = w.offset(2);
  ST = w.offset(3);
  ST2 = w.offset(4);
  U = w.offset(5);
  T = w.offset(6);
  CAP = w.offset(7);
  ST32 = ST >> 2;
  ST232 = ST2 >> 2;
  ioView = m8.subarray(IO, IO + CAP);
  MOD = mod;
  W = w;
}
/* @__PURE__ */ (() => {
  let bytes = null;
  try {
    if (typeof WebAssembly !== "object") return;
    bytes = b64decode(import_fastwasm.default);
    initWasm(new WebAssembly.Module(bytes));
  } catch (e) {
    W = null;
    if (bytes) WebAssembly.compile(bytes).then(initWasm, () => {
    });
  }
})();
const L8 = {
  save(h, m, i) {
    m[i] = h.A;
    m[i + 1] = h.B;
    m[i + 2] = h.C;
    m[i + 3] = h.D;
    m[i + 4] = h.E;
    m[i + 5] = h.F;
    m[i + 6] = h.G;
    m[i + 7] = h.H;
  },
  load(h, m, i) {
    h.A = m[i];
    h.B = m[i + 1];
    h.C = m[i + 2];
    h.D = m[i + 3];
    h.E = m[i + 4];
    h.F = m[i + 5];
    h.G = m[i + 6];
    h.H = m[i + 7];
  }
};
const L5 = {
  save(h, m, i) {
    m[i] = h.A;
    m[i + 1] = h.B;
    m[i + 2] = h.C;
    m[i + 3] = h.D;
    m[i + 4] = h.E;
  },
  load(h, m, i) {
    h.A = m[i];
    h.B = m[i + 1];
    h.C = m[i + 2];
    h.D = m[i + 3];
    h.E = m[i + 4];
  }
};
const L4 = {
  save(h, m, i) {
    m[i] = h.A;
    m[i + 1] = h.B;
    m[i + 2] = h.C;
    m[i + 3] = h.D;
  },
  load(h, m, i) {
    h.A = m[i];
    h.B = m[i + 1];
    h.C = m[i + 2];
    h.D = m[i + 3];
  }
};
const L64 = {
  save(h, m, i) {
    m[i] = h.Al;
    m[i + 1] = h.Ah;
    m[i + 2] = h.Bl;
    m[i + 3] = h.Bh;
    m[i + 4] = h.Cl;
    m[i + 5] = h.Ch;
    m[i + 6] = h.Dl;
    m[i + 7] = h.Dh;
    m[i + 8] = h.El;
    m[i + 9] = h.Eh;
    m[i + 10] = h.Fl;
    m[i + 11] = h.Fh;
    m[i + 12] = h.Gl;
    m[i + 13] = h.Gh;
    m[i + 14] = h.Hl;
    m[i + 15] = h.Hh;
  },
  load(h, m, i) {
    h.Al = m[i];
    h.Ah = m[i + 1];
    h.Bl = m[i + 2];
    h.Bh = m[i + 3];
    h.Cl = m[i + 4];
    h.Ch = m[i + 5];
    h.Dl = m[i + 6];
    h.Dh = m[i + 7];
    h.El = m[i + 8];
    h.Eh = m[i + 9];
    h.Fl = m[i + 10];
    h.Fh = m[i + 11];
    h.Gl = m[i + 12];
    h.Gh = m[i + 13];
    h.Hl = m[i + 14];
    h.Hh = m[i + 15];
  }
};
function defineFast(cls, kind) {
  const [alg, layout] = kind === "sha256" ? [A_SHA256, L8] : kind === "sha512" ? [A_SHA512, L64] : kind === "sha1" ? [A_SHA1, L5] : [A_MD5, L4];
  const t = new cls();
  Object.defineProperty(cls.prototype, FAST, {
    value: {
      alg,
      ctor: cls,
      save: layout.save,
      load: layout.load,
      bl: t.blockLen,
      ol: t.outputLen,
      po: t.padOffset,
      le: t.isLE
    }
  });
}
function usable(h, k) {
  return h.blockLen === k.bl && h.outputLen === k.ol && h.padOffset === k.po && h.isLE === k.le;
}
function bitsLo(len) {
  return len * 8 >>> 0;
}
function bitsHi(len) {
  return Math.floor(len * 8 / 4294967296) >>> 0;
}
const ioAt = [];
const outAt = [];
function ioFrom(i) {
  return ioAt[i] || (ioAt[i] = m8.subarray(IO + i, IO + CAP));
}
function outView(n) {
  return outAt[n] || (outAt[n] = m8.subarray(OUT, OUT + n));
}
function finView(bl) {
  var _a;
  return outAt[_a = 1e3 + bl] || (outAt[_a] = m8.subarray(FIN, FIN + bl));
}
function ioBlock(bl) {
  var _a;
  return outAt[_a = 2e3 + bl] || (outAt[_a] = m8.subarray(IO, IO + bl));
}
let encoder = null;
function fastUpdate(h, data, k) {
  if (W === null || !usable(h, k)) return false;
  if (typeof data === "string") {
    if (data.length * 3 <= CAP - k.bl) return updateString(h, data, k);
    data = (0, import_utils.utf8ToBytes)(data);
  } else (0, import_utils.abytes)(data);
  const len = data.length;
  const bl = k.bl;
  const bpos = h.pos;
  const buffer = h.buffer;
  if (bpos + len < bl) {
    buffer.set(data, bpos);
    h.pos = bpos + len;
    h.length += len;
    return true;
  }
  k.save(h, m32, ST32);
  if (len <= CAP - bl) {
    if (bpos > 0) m8.set(buffer, IO);
    m8.set(data, IO + bpos);
    const total = bpos + len;
    const end2 = total - total % bl;
    if (bpos > 0) buffer.set(ioBlock(bl));
    for (let i = end2; i < total; i++) buffer[i - end2] = m8[IO + i];
    m8.fill(0, IO + end2, IO + total);
    W.blocks(k.alg, end2 / bl);
    h.pos = total - end2;
    h.length += len;
    k.load(h, m32, ST32);
    W.wipe();
    return true;
  }
  let dpos = 0;
  let io = 0;
  if (bpos > 0) {
    const take = bl - bpos;
    buffer.set(data.subarray(0, take), bpos);
    m8.set(buffer, IO);
    io = bl;
    dpos = take;
  }
  const end = len - (len - dpos) % bl;
  for (; ; ) {
    const n = Math.min(CAP - io, end - dpos);
    if (n > 0) {
      m8.set(n === len ? data : data.subarray(dpos, dpos + n), IO + io);
      io += n;
      dpos += n;
    }
    if (io > 0) W.blocks(k.alg, io / bl);
    io = 0;
    if (dpos >= end) break;
  }
  if (end < len) buffer.set(data.subarray(end), 0);
  h.pos = len - end;
  h.length += len;
  k.load(h, m32, ST32);
  W.wipe();
  return true;
}
function updateString(h, str, k) {
  const bl = k.bl;
  const bpos = h.pos;
  const buffer = h.buffer;
  for (let i = 0; i < bpos; i++) m8[IO + i] = buffer[i];
  encoder || (encoder = new TextEncoder());
  const n = encoder.encodeInto(str, ioFrom(bpos)).written;
  const total = bpos + n;
  if (total < bl) {
    for (let i = bpos; i < total; i++) buffer[i] = m8[IO + i];
    m8.fill(0, IO, IO + total);
    h.pos = total;
    h.length += n;
    return true;
  }
  k.save(h, m32, ST32);
  const end = total - total % bl;
  if (bpos > 0) buffer.set(ioBlock(bl));
  for (let i = end; i < total; i++) buffer[i - end] = m8[IO + i];
  m8.fill(0, IO + end, IO + total);
  W.blocks(k.alg, end / bl);
  h.pos = total - end;
  h.length += n;
  k.load(h, m32, ST32);
  W.wipe();
  return true;
}
function fastDigestInto(h, out, k) {
  if (W === null || !usable(h, k)) return false;
  const buffer = h.buffer;
  k.save(h, m32, ST32);
  m8.set(buffer, IO);
  const length = h.length;
  W.finish(k.alg, h.pos, bitsLo(length), bitsHi(length));
  buffer.set(finView(k.bl));
  k.load(h, m32, ST32);
  out.set(outView(k.ol));
  W.wipe();
  return true;
}
function hashBytes(alg, bl, data) {
  const len = data.length;
  let pos = 0;
  while (len - pos > CAP) {
    m8.set(data.subarray(pos, pos + CAP), IO);
    W.blocks(alg, CAP / bl);
    pos += CAP;
  }
  m8.set(pos === 0 ? data : data.subarray(pos), IO);
  W.finish(alg, len - pos, bitsLo(len), bitsHi(len));
}
function fastHasher(hashCons) {
  const hashC = (msg) => {
    if (W !== null) {
      let data = msg;
      if (typeof msg === "string") {
        if (msg.length * 3 <= CAP) {
          encoder || (encoder = new TextEncoder());
          const n = encoder.encodeInto(msg, ioView).written;
          m32.set(iv, ST32);
          W.finish(alg, n, bitsLo(n), bitsHi(n));
          const res2 = m8.slice(OUT, OUT + outputLen);
          W.wipe();
          return res2;
        }
        data = (0, import_utils.utf8ToBytes)(msg);
      } else (0, import_utils.abytes)(msg);
      m32.set(iv, ST32);
      hashBytes(alg, blockLen, data);
      const res = m8.slice(OUT, OUT + outputLen);
      W.wipe();
      return res;
    }
    return hashCons().update((0, import_utils.toBytes)(msg)).digest();
  };
  const tmp = hashCons();
  hashC.outputLen = tmp.outputLen;
  hashC.blockLen = tmp.blockLen;
  hashC.create = () => hashCons();
  const k = tmp[FAST];
  const { alg } = k;
  const { outputLen, blockLen } = tmp;
  const iv = new Int32Array(16);
  k.save(tmp, iv, 0);
  return hashC;
}
function fastPrf(PRF) {
  if (W === null) return void 0;
  const { iHash, oHash } = PRF;
  const k = iHash && iHash[FAST];
  if (k === void 0 || iHash.constructor !== k.ctor || oHash.constructor !== k.ctor) return void 0;
  const bl = iHash.blockLen;
  if (iHash.pos !== 0 || oHash.pos !== 0 || iHash.length !== bl || oHash.length !== bl) return void 0;
  if (iHash.finished || oHash.finished || iHash.destroyed || oHash.destroyed) return void 0;
  return k;
}
const PBKDF2_CHUNK = 1 << 30;
function pbkdf2Run(PRF, k, u, acc, iters) {
  const ol = u.length;
  k.save(PRF.iHash, m32, ST32);
  k.save(PRF.oHash, m32, ST232);
  m8.set(u, U);
  m8.set(acc, T);
  W.pbkdf2(k.alg, ol, iters);
  u.set(m8.subarray(U, U + ol));
  acc.set(m8.subarray(T, T + ol));
  W.wipe();
}
function fastPbkdf2(PRF, k, u, Ti, iters) {
  const acc = u.slice();
  for (let done = 0; done < iters; ) {
    const n = Math.min(PBKDF2_CHUNK, iters - done);
    pbkdf2Run(PRF, k, u, acc, n);
    done += n;
  }
  Ti.set(acc.subarray(0, Ti.length));
  acc.fill(0);
}
async function fastPbkdf2Async(PRF, k, u, Ti, iters, asyncTick) {
  const acc = u.slice();
  let done = 0;
  let step = 256;
  let ts = Date.now();
  while (done < iters) {
    const n = Math.min(step, iters - done);
    const t0 = Date.now();
    pbkdf2Run(PRF, k, u, acc, n);
    done += n;
    const spent = Date.now() - t0;
    if (spent < asyncTick / 4 && step < PBKDF2_CHUNK) step *= 2;
    const diff = Date.now() - ts;
    if (diff >= 0 && diff < asyncTick) continue;
    await (0, import_utils.nextTick)();
    ts += diff;
  }
  Ti.set(acc.subarray(0, Ti.length));
  acc.fill(0);
}
function fastScrypt(r, N, p) {
  if (MOD === null || N > 2 ** 31) return null;
  let w;
  try {
    w = new WebAssembly.Instance(MOD, {}).exports;
  } catch (e) {
    return null;
  }
  const b = w.scrypt_init(r, N, p);
  if (b === 0) return null;
  const bytes = 128 * r * p;
  return {
    /** copies B in */
    setB(B) {
      new Uint8Array(w.memory.buffer, b, bytes).set(B);
      w.scrypt_permute(0);
    },
    /** copies B out */
    getB(B) {
      w.scrypt_permute(1);
      B.set(new Uint8Array(w.memory.buffer, b, bytes));
    },
    steps: w.scrypt_steps,
    wipe: w.scrypt_wipe
  };
}
function scryptSlices(F, N, p, onProgress) {
  const steps = 2 * N;
  const total = steps * p;
  const per = Math.max(Math.floor(total / 1e4), 1);
  let cnt = 0;
  return () => {
    if (cnt >= total) return false;
    const pi = Math.floor(cnt / steps);
    const s = cnt - pi * steps;
    let e = steps;
    if (onProgress) {
      const next = Math.min((Math.floor(cnt / per) + 1) * per, total);
      e = Math.min(steps, s + (next - cnt));
    }
    return [pi, s, e, (n) => {
      cnt += n;
      if (onProgress && (!(cnt % per) || cnt === total)) onProgress(cnt / total);
    }];
  };
}
function fastScryptRun(F, B, N, p, onProgress) {
  try {
    F.setB(B);
    const next = scryptSlices(F, N, p, onProgress);
    for (let sl; sl = next(); ) {
      const [pi, s, e, done] = sl;
      F.steps(pi, s, e);
      done(e - s);
    }
    F.getB(B);
  } finally {
    F.wipe();
  }
}
async function fastScryptRunAsync(F, B, N, p, onProgress, asyncTick) {
  try {
    F.setB(B);
    const next = scryptSlices(F, N, p, onProgress);
    let step = 16;
    let ts = Date.now();
    for (let sl; sl = next(); ) {
      const [pi, s, e0, done] = sl;
      for (let s1 = s; s1 < e0; ) {
        const e = Math.min(e0, s1 + step);
        const t0 = Date.now();
        F.steps(pi, s1, e);
        if (Date.now() - t0 < asyncTick / 4) step *= 2;
        s1 = e;
        const diff = Date.now() - ts;
        if (diff >= 0 && diff < asyncTick) continue;
        await (0, import_utils.nextTick)();
        ts += diff;
      }
      done(e0 - s);
    }
    F.getB(B);
  } finally {
    F.wipe();
  }
}
function wasmActive() {
  return W !== null;
}
function scratchIsClean() {
  if (W === null) return true;
  for (let i = IO; i < T + 64; i++) if (m8[i] !== 0) return false;
  return true;
}
