// Builds the wasm of the package and writes it, base64, into the generated
// end of esm/_fast.ts (then regenerates esm/_fast.js with tools/ts-build.mjs
// and the CommonJS _fast.js from it):
//   COMMON, WASM_SHA256, WASM_SHA512, WASM_SHA1, WASM_MD5: the templates of
//     the hash family modules (wasm/kernels.mjs), which expand() in
//     esm/_fast.ts turns into the modules on first use;
//   WASM_SCRYPT: wasm/scrypt.wat, assembled and optimised with binaryen.
// Then checks every family module as expand() builds it (valid, digests and
// PBKDF2 against node:crypto) and writes the modules to wasm/target/ (for
// inspection; not shipped).
// usage: node packages/fast-noble-hashes/build.mjs
import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createHash, createHmac, pbkdf2Sync, scryptSync } from "node:crypto";
import { transformSync } from "esbuild";
import binaryen from "binaryen";
import * as KERNELS from "./wasm/kernels.mjs";

const here = dirname(fileURLToPath(import.meta.url));

function assemble(file, level, shrink) {
  const mod = binaryen.parseText(readFileSync(join(here, file), "utf8"));
  mod.setFeatures(binaryen.Features.All);
  if (!mod.validate()) throw new Error(`${file} does not validate`);
  binaryen.setOptimizeLevel(level);
  binaryen.setShrinkLevel(shrink);
  mod.optimize();
  mod.runPasses(["strip-debug", "strip-producers", "strip-target-features"]);
  const out = Buffer.from(mod.emitBinary());
  mod.dispose();
  return out;
}

const scrypt = assemble("wasm/scrypt.wat", 2, 2);
const family = (name) => [`WASM_${name}`, `the template of the ${name} module`, KERNELS.familyText(name)];
// (in the order that compresses best in a bundle with all of them: the order
// of declarations, which bundlers keep, changes brotli's result by ~50 bytes)
const ORDER = ["SHA256", "SHA512", "MD5", "SHA1", "COMMON", "SCRYPT"];
if (ORDER.filter((n) => n !== "SCRYPT" && n !== "COMMON").sort().join() !== Object.keys(KERNELS.FAMILIES).sort().join()) throw new Error("ORDER: not the families of wasm/kernels.mjs");
const blobs = ORDER.map((name) =>
  name === "SCRYPT"
    ? ["WASM_SCRYPT", "scrypt's ROMix (wasm/scrypt.wat)", scrypt]
    : name === "COMMON"
      ? ["COMMON", "the common template of the hash family modules (wasm/kernels.mjs)", KERNELS.commonText()]
      : family(name),
);
for (const [name, , bytes] of blobs) console.log(`${name}: ${bytes.length} bytes`);

// The text of the wasm (see bytes() in esm/_fast.ts): the characters are
// printable ASCII without `"` and backslash (93 of them, A[0..92]); byte b
// is the one character A[2 + i] if i = (b + SHIFT) & 255 is below 91, else
// the two A[(i - 91) / 93], A[(i - 91) % 93]. (With SHIFT 6 the frequent
// small opcodes and immediates and 0xfa..0xff are one character. A table
// of the most frequent bytes compressed worse, table included.)
const SHIFT = 6;
const ALPHABET = [];
for (let c = 32; c < 127; c++) if (c !== 34 && c !== 92) ALPHABET.push(String.fromCharCode(c));
const CODE = [];
for (let b = 0; b < 256; b++) {
  const i = (b + SHIFT) & 255;
  CODE[b] = i < 91 ? ALPHABET[2 + i] : ALPHABET[Math.floor((i - 91) / 93)] + ALPHABET[(i - 91) % 93];
}
const text = (b) => [...b].map((x) => CODE[x]).join("");
const texts = blobs.map(([n, doc, b]) => [n, doc, text(b)]);

// the generated end of esm/_fast.ts: everything after MARK
const MARK = "// generated by build.mjs from wasm/ (everything below this line)\n";
const tsFile = join(here, "esm/_fast.ts");
const ts = readFileSync(tsFile, "utf8");
if (!ts.includes(MARK)) throw new Error("esm/_fast.ts: marker line not found");
writeFileSync(tsFile, ts.slice(0, ts.indexOf(MARK) + MARK.length) + texts.map(([n, doc, t]) => `/** ${doc} */\nexport const ${n} = ${JSON.stringify(t)};\n`).join(""));
execSync(`"${process.execPath}" ${JSON.stringify(join(here, "../../tools/ts-build.mjs"))}`, { stdio: "inherit" });
const esm = readFileSync(join(here, "esm/_fast.js"), "utf8");
const { code } = transformSync(esm, { format: "cjs", target: "es2020", legalComments: "inline" });
writeFileSync(join(here, "_fast.js"), `// generated by build.mjs from esm/_fast.js — do not edit\n${code}`);
console.log("wrote esm/_fast.ts, esm/_fast.js, _fast.js");

// ---- checks: every family as expand() builds it
const fast = await import(pathToFileURL(join(here, "esm/_fast.js")).href + "?" + Date.now());
for (const [n, , b] of blobs) if (Buffer.compare(Buffer.from(fast.bytes(fast[n])), Buffer.from(b))) throw new Error(`${n}: the text does not decode to the bytes`);
for (let v = 49; v <= 50; v++) for (let j = 0; j < 64; j++) if (fast.MD5_X(v, j) !== KERNELS.FAMILIES.MD5.x(v, j)) throw new Error("MD5_X differs from wasm/kernels.mjs");
const MD5_K = Array.from({ length: 64 }, (_, i) => Math.floor(2 ** 32 * Math.abs(Math.sin(i + 1))));
const IV = {
  SHA256: [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19],
  SHA512: [0x6a09e667, 0xf3bcc908, 0xbb67ae85, 0x84caa73b, 0x3c6ef372, 0xfe94f82b, 0xa54ff53a, 0x5f1d36f1, 0x510e527f, 0xade682d1, 0x9b05688c, 0x2b3e6c1f, 0x1f83d9ab, 0xfb41bd6b, 0x5be0cd19, 0x137e2179],
  SHA1: [0x67452301, 0xefcdab89, 0x98badcfe, 0x10325476, 0xc3d2e1f0],
  MD5: [0x67452301, 0xefcdab89, 0x98badcfe, 0x10325476],
};
const K = { SHA256: fast.K(64), SHA512: fast.K(80), MD5: () => MD5_K.map(BigInt) };
const { MEM, CAP } = KERNELS;
const data = new Uint8Array(300000).map((_, i) => (i * 2654435761) >>> 24);
mkdirSync(join(here, "wasm/target"), { recursive: true });
for (const [name, { r, bl, po }] of Object.entries(KERNELS.FAMILIES)) {
  const f = fast.wasmFamily(fast[`WASM_${name}`], bl, po, r, K[name], name === "MD5" ? fast.MD5_X : undefined);
  const bytes = fast.expand(f);
  writeFileSync(join(here, `wasm/target/${name.toLowerCase()}.wasm`), bytes);
  const mod = binaryen.readBinary(bytes);
  mod.setFeatures(binaryen.Features.All);
  if (!mod.validate()) throw new Error(`${name}: the expanded module does not validate`);
  mod.dispose();
  const W = new WebAssembly.Instance(new WebAssembly.Module(bytes)).exports;
  const m8 = new Uint8Array(W.m.buffer), i32 = new Int32Array(W.m.buffer);
  if (f.k) new BigUint64Array(W.m.buffer, MEM.KB).set(f.k());
  const alg = name.toLowerCase(), ol = createHash(alg).digest().length;
  const hash = (d) => {
    i32.set(IV[name]);
    let pos = 0;
    for (let i = 0; i < d.length; i += CAP) {
      m8.set(d.subarray(i, i + CAP), MEM.IO);
      pos = W.u(pos, Math.min(CAP, d.length - i));
    }
    W.d(pos, d.length);
    const res = Buffer.from(m8.slice(MEM.O, MEM.O + ol)).toString("hex");
    W.z();
    return res;
  };
  for (const len of [0, 1, 55, 56, 63, 64, 111, 112, 127, 128, 1000, CAP - 1, CAP, CAP + 1, 300000]) {
    const d = data.subarray(0, len);
    if (hash(d) !== createHash(alg).update(d).digest("hex")) throw new Error(`${name}: wrong digest of ${len} bytes`);
  }
  // PBKDF2: the HMAC states after the key block, U1
  const key = data.subarray(0, 20), salt = data.subarray(100, 116), c = 1000;
  const pad = new Uint8Array(bl);
  pad.set(key);
  const keyed = (x) => {
    i32.set(IV[name]);
    m8.set(pad.map((v) => v ^ x), MEM.IO);
    W.u(0, bl);
    const st = i32.slice(0, 16);
    W.z();
    return st;
  };
  const is = keyed(0x36), os = keyed(0x5c);
  const u1 = createHmac(alg, key).update(Buffer.concat([salt, Buffer.from([0, 0, 0, 1])])).digest();
  i32.set(is);
  i32.set(os, 16);
  m8.set(u1, MEM.B);
  m8.set(u1, MEM.TT);
  W.p(ol, c - 1);
  const t = Buffer.from(m8.slice(MEM.TT, MEM.TT + ol)).toString("hex");
  W.z();
  if (t !== pbkdf2Sync(key, salt, c, ol, alg).toString("hex")) throw new Error(`${name}: wrong PBKDF2`);
  if (i32.subarray(0, MEM.KB >> 2).some((x) => x)) throw new Error(`${name}: memory not wiped`);
  console.log(`${name}: template ${fast[`WASM_${name}`].length} characters -> module ${bytes.length} bytes, ok`);
}
// scrypt (through the glue: it lays out and permutes the blocks)
{
  const [N, r, p] = [64, 3, 2];
  const B = new Uint8Array(pbkdf2Sync("pw", "salt", 1, 128 * r * p, "sha256"));
  fast.fastScrypt(fast.wasmFamily(fast.WASM_SCRYPT), B, r, N, p);
  if (pbkdf2Sync("pw", B, 1, 32, "sha256").toString("hex") !== scryptSync("pw", "salt", 32, { N, r, p }).toString("hex")) throw new Error("scrypt: wrong result");
  writeFileSync(join(here, "wasm/target/scrypt.wasm"), scrypt);
  console.log(`SCRYPT: ${scrypt.length} bytes, ok`);
}
