// Builds the wasm core and embeds it (base64) into _fastwasm.js (CommonJS)
// and esm/_fastwasm.js, and generates the CommonJS _fast.js from
// esm/_fast.js.
// usage: node packages/fast-noble-hashes/build.mjs [--no-opt] [--no-cargo]
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { transformSync } from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const crate = join(here, "rust");
if (!process.argv.includes("--no-cargo")) execSync("cargo build --release", { cwd: crate, stdio: "inherit" });
let bytes = readFileSync(join(crate, "target/wasm32-unknown-unknown/release/fasthashes.wasm"));
console.log("raw wasm:", bytes.length, "bytes");

if (!process.argv.includes("--no-opt")) {
  const { default: binaryen } = await import("binaryen");
  const mod = binaryen.readBinary(bytes);
  mod.setFeatures(binaryen.Features.All);
  binaryen.setOptimizeLevel(3);
  binaryen.setShrinkLevel(0);
  mod.optimize();
  bytes = Buffer.from(mod.emitBinary());
  console.log("wasm-opt -O3:", bytes.length, "bytes");
}

const b64 = JSON.stringify(bytes.toString("base64"));
writeFileSync(join(here, "fasthashes.wasm"), bytes);
writeFileSync(join(here, "esm/_fastwasm.js"), `// generated by build.mjs — do not edit\nexport default ${b64};\n`);
writeFileSync(
  join(here, "_fastwasm.js"),
  `"use strict";\n// generated by build.mjs — do not edit\nObject.defineProperty(exports, "__esModule", { value: true });\nexports.default = ${b64};\n`,
);

const esm = readFileSync(join(here, "esm/_fast.js"), "utf8");
const { code } = transformSync(esm, { format: "cjs", target: "es2020", legalComments: "inline" });
writeFileSync(join(here, "_fast.js"), `// generated by build.mjs from esm/_fast.js — do not edit\n${code}`);
console.log("wrote _fastwasm.js, esm/_fastwasm.js, _fast.js");
