// Build the wasm core and embed it (base64) into fastzlib.wasm.mjs.
// usage: node fast-pako/build.mjs [--no-opt]
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const crate = join(here, "rust");
execSync("cargo build --release", { cwd: crate, stdio: "inherit" });
let bytes = readFileSync(join(crate, "target/wasm32-unknown-unknown/release/fastzlib.wasm"));
console.log("raw wasm:", bytes.length, "bytes");

if (!process.argv.includes("--no-opt")) {
  try {
    const { default: binaryen } = await import("binaryen");
    const mod = binaryen.readBinary(bytes);
    mod.setFeatures(binaryen.Features.All);
    binaryen.setOptimizeLevel(3);
    binaryen.setShrinkLevel(0);
    mod.optimize();
    const out = mod.emitBinary();
    console.log("wasm-opt -O3:", out.length, "bytes");
    bytes = Buffer.from(out);
  } catch (e) {
    console.log("binaryen not available, skipping wasm-opt:", e.message);
  }
}

writeFileSync(join(here, "fastzlib.wasm"), bytes);
writeFileSync(
  join(here, "fastzlib.wasm.mjs"),
  `// generated by build.mjs — do not edit\nexport default ${JSON.stringify(bytes.toString("base64"))};\n`,
);
console.log("wrote fastzlib.wasm.mjs");
