// The shipped files are @noble/hashes 1.8.0 plus the patches in
// tools/patches.mjs and nothing else; the generated files are up to date.
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { transformSync } from "esbuild";
import { expected, vendoredFiles, upstream } from "../tools/vendor.mjs";
import { PATCHES } from "../tools/patches.mjs";

const here = join(dirname(fileURLToPath(import.meta.url)), "..");
let checks = 0, fails = 0;
const ok = (c, what) => {
  checks++;
  if (!c) {
    fails++;
    console.log("FAIL", what);
  }
};
const read = (rel) => readFileSync(join(here, rel), "utf8");

const files = vendoredFiles();
for (const rel of files) ok(existsSync(join(here, rel)) && read(rel) === expected(rel), `${rel} is upstream${PATCHES[rel] ? " + patches" : ""}`);
for (const rel of Object.keys(PATCHES)) ok(files.includes(rel), `patched file ${rel} exists upstream`);
ok(read("esm/package.json") === readFileSync(join(upstream, "esm/package.json"), "utf8"), "esm/package.json");
// nothing else in the shipped directories
const OWN = ["_fast.js", "_fastwasm.js", "esm/_fast.js", "esm/_fastwasm.js"];
for (const sub of ["", "esm"]) {
  for (const f of readdirSync(join(here, sub))) {
    const rel = sub ? `${sub}/${f}` : f;
    if (!/\.(js|d\.ts)$/.test(f)) continue;
    ok(files.includes(rel) || OWN.includes(rel), `unexpected file ${rel}`);
  }
}
// generated CommonJS glue is current
const { code } = transformSync(read("esm/_fast.js"), { format: "cjs", target: "es2020", legalComments: "inline" });
ok(read("_fast.js") === `// generated by build.mjs from esm/_fast.js — do not edit\n${code}`, "_fast.js is generated from esm/_fast.js (run node build.mjs)");
const b64 = (s) => s.match(/"([A-Za-z0-9+/=]+)"/)[1];
ok(b64(read("_fastwasm.js")) === b64(read("esm/_fastwasm.js")), "_fastwasm.js and esm/_fastwasm.js embed the same wasm");
// package.json mirrors upstream's entry points
const pkg = JSON.parse(read("package.json"));
const up = JSON.parse(readFileSync(join(upstream, "package.json"), "utf8"));
const { "./package.json": _, ...exp } = pkg.exports;
ok(JSON.stringify(exp) === JSON.stringify(up.exports), "exports = upstream's (+ ./package.json)");
ok(JSON.stringify(pkg.browser) === JSON.stringify(up.browser) && pkg.sideEffects === up.sideEffects, "browser / sideEffects");
ok(pkg.version === up.version && pkg.upstream === `@noble/hashes@${up.version}`, "version");
console.log(`files: ${checks} checks, ${fails} failures`);
process.exit(fails ? 1 : 0);
