// The shipped files are @noble/hashes 1.8.0 plus the patches in
// tools/patches.mjs and nothing else; the generated files are up to date.
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { transformSync } from "esbuild";
import { expected, vendoredFiles, upstream } from "../tools/vendor.mjs";
import { PATCHES } from "../tools/patches.mjs";

const here = join(dirname(fileURLToPath(import.meta.url)), "..");
let checks = 0, fails = 0;
const ok = (c, what) => {
  checks++;
  if (!c) {
    fails++;
    console.log("FAIL", what);
  }
};
const read = (rel) => readFileSync(join(here, rel), "utf8");

const files = vendoredFiles();
for (const rel of files) ok(existsSync(join(here, rel)) && read(rel) === expected(rel), `${rel} is upstream${PATCHES[rel] ? " + patches" : ""}`);
for (const rel of Object.keys(PATCHES)) ok(files.includes(rel), `patched file ${rel} exists upstream`);
ok(read("esm/package.json") === readFileSync(join(upstream, "esm/package.json"), "utf8"), "esm/package.json");
// nothing else in the shipped directories
const OWN = ["_fast.js", "esm/_fast.js"];
for (const rel of OWN) ok(existsSync(join(here, rel)), `${rel} exists`);
for (const sub of ["", "esm"]) {
  for (const f of readdirSync(join(here, sub))) {
    const rel = sub ? `${sub}/${f}` : f;
    if (!/\.(js|d\.ts)$/.test(f)) continue;
    ok(files.includes(rel) || OWN.includes(rel), `unexpected file ${rel}`);
  }
}
// generated CommonJS glue is current
const { code } = transformSync(read("esm/_fast.js"), { format: "cjs", target: "es2020", legalComments: "inline" });
ok(read("_fast.js") === `// generated by build.mjs from esm/_fast.js — do not edit\n${code}`, "_fast.js is generated from esm/_fast.js (run node build.mjs)");
// the wasm modules (the generated end of esm/_fast.ts) are there
const fast = await import(pathToFileURL(join(here, "esm/_fast.js")).href);
// (the texts of the templates and of scrypt's module)
ok(!("TABLE" in fast), "no table");
for (const n of ["COMMON", "WASM_SHA256", "WASM_SHA512", "WASM_SHA1", "WASM_MD5", "WASM_SCRYPT"]) ok(typeof fast[n] === "string" && fast[n].length > 200 && !/["\\]/.test(fast[n]), n);
// the texts decode to what wasm/ builds
const K = await import(pathToFileURL(join(here, "wasm/kernels.mjs")).href);
ok(Buffer.from(fast.bytes(fast.COMMON)).equals(Buffer.from(K.commonText())), "COMMON is wasm/kernels.mjs's");
for (const n of Object.keys(K.FAMILIES)) ok(Buffer.from(fast.bytes(fast[`WASM_${n}`])).equals(Buffer.from(K.familyText(n))), `WASM_${n} is wasm/kernels.mjs's`);
// package.json mirrors upstream's entry points
const pkg = JSON.parse(read("package.json"));
const up = JSON.parse(readFileSync(join(upstream, "package.json"), "utf8"));
const { "./package.json": _, ...exp } = pkg.exports;
ok(JSON.stringify(exp) === JSON.stringify(up.exports), "exports = upstream's (+ ./package.json)");
ok(JSON.stringify(pkg.browser) === JSON.stringify(up.browser) && pkg.sideEffects === up.sideEffects, "browser / sideEffects");
// patch releases of this package may run ahead of upstream's, so match major.minor and pin the upstream version
const mm = (v) => v.split(".").slice(0, 2).join(".");
ok(mm(pkg.version) === mm(up.version) && pkg.upstream === `@noble/hashes@${up.version}`, "version");
console.log(`files: ${checks} checks, ${fails} failures`);
process.exit(fails ? 1 : 0);
