// Generated by tools/gen_compat_css.mjs from esbuild's internal/compat/css_table.go.
// Do not edit by hand.
//
// compat.CSSFeature is a uint16 bit set in Go: a number here. CSSPrefix is a
// bit set too. CSSPrefixData returns a Map<D, CSSPrefix> or null (Go: nil).
import { Chrome, Edge, Firefox, IE, IOS, Opera, Safari, engineIsBrowser } from "./compat.mjs";
import type { Semver } from "./compat.mjs";
import { DAppearance, DBackdropFilter, DBackgroundClip, DBoxDecorationBreak, DClipPath, DFontKerning, DHeight, DHyphens, DInitialLetter, DMask, DMaskComposite, DMaskImage, DMaskOrigin, DMaskPosition, DMaskRepeat, DMaskSize, DMaxHeight, DMaxWidth, DMinHeight, DMinWidth, DPosition, DPrintColorAdjust, DTabSize, DTextDecorationColor, DTextDecorationLine, DTextDecorationSkip, DTextEmphasisColor, DTextEmphasisPosition, DTextEmphasisStyle, DTextOrientation, DTextSizeAdjust, DUserSelect, DWidth } from "./css_ast.mjs";

// CSSFeature
export const ColorFunctions = 1;
export const GradientDoublePosition = 2;
export const GradientInterpolation = 4;
export const GradientMidpoints = 8;
export const HWB = 16;
export const HexRGBA = 32;
export const InlineStyle = 64;
export const InsetProperty = 128;
export const IsPseudoClass = 256;
export const MediaRange = 512;
export const Modern_RGB_HSL = 1024;
export const Nesting = 2048;
export const RebeccaPurple = 4096;

export const StringToCSSFeature: Map<string, number> = new Map([
  ["color-functions", ColorFunctions],
  ["gradient-double-position", GradientDoublePosition],
  ["gradient-interpolation", GradientInterpolation],
  ["gradient-midpoints", GradientMidpoints],
  ["hwb", HWB],
  ["hex-rgba", HexRGBA],
  ["inline-style", InlineStyle],
  ["inset-property", InsetProperty],
  ["is-pseudo-class", IsPseudoClass],
  ["media-range", MediaRange],
  ["modern-rgb-hsl", Modern_RGB_HSL],
  ["nesting", Nesting],
  ["rebecca-purple", RebeccaPurple],
]);

// Go: func (features CSSFeature) Has(feature CSSFeature) bool
export function cssFeatureHas(features: number, feature: number): boolean {
  return (features & feature) !== 0;
}

// Go: func (features CSSFeature) ApplyOverrides(overrides CSSFeature, mask CSSFeature) CSSFeature
export function cssFeatureApplyOverrides(features: number, overrides: number, mask: number): number {
  return (features & ~mask) | (overrides & mask);
}

// [feature, [[engine, [[start major, minor, patch(, end major, minor, patch)], ...]], ...]]
const cssTable: [number, [number, number[][]][]][] = [
  [ColorFunctions, [[Chrome, [[111,0,0]]], [Edge, [[111,0,0]]], [Firefox, [[113,0,0]]], [IOS, [[15,4,0]]], [Opera, [[97,0,0]]], [Safari, [[15,4,0]]]]],
  [GradientDoublePosition, [[Chrome, [[72,0,0]]], [Edge, [[79,0,0]]], [Firefox, [[83,0,0]]], [IOS, [[12,2,0]]], [Opera, [[60,0,0]]], [Safari, [[12,1,0]]]]],
  [GradientInterpolation, [[Chrome, [[111,0,0]]], [Edge, [[111,0,0]]], [Firefox, [[137,0,0]]], [IOS, [[16,2,0]]], [Opera, [[97,0,0]]], [Safari, [[16,2,0]]]]],
  [GradientMidpoints, [[Chrome, [[40,0,0]]], [Edge, [[79,0,0]]], [Firefox, [[36,0,0]]], [IOS, [[7,0,0]]], [Opera, [[27,0,0]]], [Safari, [[7,0,0]]]]],
  [HWB, [[Chrome, [[101,0,0]]], [Edge, [[101,0,0]]], [Firefox, [[96,0,0]]], [IOS, [[15,0,0]]], [Opera, [[87,0,0]]], [Safari, [[15,0,0]]]]],
  [HexRGBA, [[Chrome, [[62,0,0]]], [Edge, [[79,0,0]]], [Firefox, [[49,0,0]]], [IOS, [[9,3,0]]], [Opera, [[49,0,0]]], [Safari, [[10,0,0]]]]],
  [InlineStyle, []],
  [InsetProperty, [[Chrome, [[87,0,0]]], [Edge, [[87,0,0]]], [Firefox, [[66,0,0]]], [IOS, [[14,5,0]]], [Opera, [[73,0,0]]], [Safari, [[14,1,0]]]]],
  [IsPseudoClass, [[Chrome, [[88,0,0]]], [Edge, [[88,0,0]]], [Firefox, [[78,0,0]]], [IOS, [[14,0,0]]], [Opera, [[75,0,0]]], [Safari, [[14,0,0]]]]],
  [MediaRange, [[Chrome, [[104,0,0]]], [Edge, [[104,0,0]]], [Firefox, [[63,0,0]]], [IOS, [[16,4,0]]], [Opera, [[91,0,0]]], [Safari, [[16,4,0]]]]],
  [Modern_RGB_HSL, [[Chrome, [[66,0,0]]], [Edge, [[79,0,0]]], [Firefox, [[52,0,0]]], [IOS, [[12,2,0]]], [Opera, [[53,0,0]]], [Safari, [[12,1,0]]]]],
  [Nesting, [[Chrome, [[120,0,0]]], [Edge, [[120,0,0]]], [Firefox, [[117,0,0]]], [IOS, [[17,2,0]]], [Opera, [[106,0,0]]], [Safari, [[17,2,0]]]]],
  [RebeccaPurple, [[Chrome, [[38,0,0]]], [Edge, [[12,0,0]]], [Firefox, [[33,0,0]]], [IE, [[11,0,0]]], [IOS, [[8,0,0]]], [Opera, [[25,0,0]]], [Safari, [[9,0,0]]]]],
];

// Go: func compareVersions(a v, b Semver) int. "a" is [major, minor, patch]
// at offset "i".
function compareVersions(a: number[], i: number, b: Semver): number {
  let diff = a[i];
  if (b.parts.length > 0) diff -= b.parts[0];
  if (diff === 0) {
    diff = a[i + 1];
    if (b.parts.length > 1) diff -= b.parts[1];
  }
  if (diff === 0) {
    diff = a[i + 2];
    if (b.parts.length > 2) diff -= b.parts[2];
  }
  if (diff === 0 && b.preRelease.length !== 0) {
    return 1; // "1.0.0" > "1.0.0-alpha"
  }
  return diff;
}

// Go: func isVersionSupported(ranges []versionRange, version Semver) bool
function isVersionSupported(ranges: number[][], version: Semver): boolean {
  for (let i = 0; i < ranges.length; i++) {
    const r = ranges[i];
    if (compareVersions(r, 0, version) <= 0 && (r.length === 3 || compareVersions(r, 3, version) > 0)) {
      return true;
    }
  }
  return false;
}

// Go: func UnsupportedCSSFeatures(constraints map[Engine]Semver) (unsupported CSSFeature)
// Return all features that are not available in at least one environment
export function unsupportedCSSFeatures(constraints: Map<number, Semver>): number {
  let unsupported = 0;
  for (let i = 0; i < cssTable.length; i++) {
    const feature = cssTable[i][0];
    const engines = cssTable[i][1];
    if (feature === InlineStyle) {
      continue; // This is purely user-specified
    }
    for (const [engine, version] of constraints) {
      if (!engineIsBrowser(engine)) {
        // Specifying "--target=es2020" shouldn't affect CSS
        continue;
      }
      let versionRanges: number[][] | null = null;
      for (let j = 0; j < engines.length; j++) {
        if (engines[j][0] === engine) {
          versionRanges = engines[j][1];
          break;
        }
      }
      if (versionRanges === null || !isVersionSupported(versionRanges, version)) {
        unsupported |= feature;
      }
    }
  }
  return unsupported;
}

// CSSPrefix
export const KhtmlPrefix = 1;
export const MozPrefix = 2;
export const MsPrefix = 4;
export const OPrefix = 8;
export const WebkitPrefix = 16;
export const NoPrefix = 0;

// [D, [[engine, prefix, withoutPrefix ([0, 0, 0] for Go's v{})], ...]]
const cssPrefixTable: [number, [number, number, number[]][]][] = [
  [DAppearance, [[Chrome, WebkitPrefix, [84,0,0]], [Edge, WebkitPrefix, [84,0,0]], [Firefox, MozPrefix, [80,0,0]], [IOS, WebkitPrefix, [15,4,0]], [Opera, WebkitPrefix, [73,0,0]], [Safari, WebkitPrefix, [15,4,0]]]],
  [DBackdropFilter, [[IOS, WebkitPrefix, [18,0,0]], [Safari, WebkitPrefix, [18,0,0]]]],
  [DBackgroundClip, [[Chrome, WebkitPrefix, [120,0,0]], [Edge, MsPrefix, [15,0,0]], [Edge, WebkitPrefix, [120,0,0]], [Opera, WebkitPrefix, [106,0,0]], [Safari, WebkitPrefix, [5,0,0]]]],
  [DBoxDecorationBreak, [[Chrome, WebkitPrefix, [130,0,0]], [Edge, WebkitPrefix, [130,0,0]], [IOS, WebkitPrefix, [0,0,0]], [Opera, WebkitPrefix, [116,0,0]], [Safari, WebkitPrefix, [0,0,0]]]],
  [DClipPath, [[Chrome, WebkitPrefix, [55,0,0]], [IOS, WebkitPrefix, [13,0,0]], [Opera, WebkitPrefix, [42,0,0]], [Safari, WebkitPrefix, [13,1,0]]]],
  [DFontKerning, [[Chrome, WebkitPrefix, [33,0,0]], [IOS, WebkitPrefix, [12,0,0]], [Opera, WebkitPrefix, [20,0,0]], [Safari, WebkitPrefix, [9,1,0]]]],
  [DHeight, [[Chrome, WebkitPrefix, [138,0,0]], [Edge, WebkitPrefix, [138,0,0]], [Firefox, WebkitPrefix, [0,0,0]], [IOS, WebkitPrefix, [0,0,0]], [Opera, WebkitPrefix, [122,0,0]], [Safari, WebkitPrefix, [0,0,0]]]],
  [DHyphens, [[Edge, MsPrefix, [79,0,0]], [Firefox, MozPrefix, [43,0,0]], [IE, MsPrefix, [0,0,0]], [IOS, WebkitPrefix, [17,0,0]], [Safari, WebkitPrefix, [17,0,0]]]],
  [DInitialLetter, [[IOS, WebkitPrefix, [0,0,0]], [Safari, WebkitPrefix, [0,0,0]]]],
  [DMask, [[Chrome, WebkitPrefix, [120,0,0]], [Edge, WebkitPrefix, [120,0,0]], [IOS, WebkitPrefix, [15,4,0]], [Opera, WebkitPrefix, [106,0,0]], [Safari, WebkitPrefix, [15,4,0]]]],
  [DMaskComposite, [[Chrome, WebkitPrefix, [120,0,0]], [Edge, WebkitPrefix, [120,0,0]], [IOS, WebkitPrefix, [15,4,0]], [Opera, WebkitPrefix, [106,0,0]], [Safari, WebkitPrefix, [15,4,0]]]],
  [DMaskImage, [[Chrome, WebkitPrefix, [120,0,0]], [Edge, WebkitPrefix, [120,0,0]], [IOS, WebkitPrefix, [15,4,0]], [Opera, WebkitPrefix, [0,0,0]], [Safari, WebkitPrefix, [15,4,0]]]],
  [DMaskOrigin, [[Chrome, WebkitPrefix, [120,0,0]], [Edge, WebkitPrefix, [120,0,0]], [IOS, WebkitPrefix, [15,4,0]], [Opera, WebkitPrefix, [106,0,0]], [Safari, WebkitPrefix, [15,4,0]]]],
  [DMaskPosition, [[Chrome, WebkitPrefix, [120,0,0]], [Edge, WebkitPrefix, [120,0,0]], [IOS, WebkitPrefix, [15,4,0]], [Opera, WebkitPrefix, [106,0,0]], [Safari, WebkitPrefix, [15,4,0]]]],
  [DMaskRepeat, [[Chrome, WebkitPrefix, [120,0,0]], [Edge, WebkitPrefix, [120,0,0]], [IOS, WebkitPrefix, [15,4,0]], [Opera, WebkitPrefix, [106,0,0]], [Safari, WebkitPrefix, [15,4,0]]]],
  [DMaskSize, [[Chrome, WebkitPrefix, [120,0,0]], [Edge, WebkitPrefix, [120,0,0]], [IOS, WebkitPrefix, [15,4,0]], [Opera, WebkitPrefix, [106,0,0]], [Safari, WebkitPrefix, [15,4,0]]]],
  [DMaxHeight, [[Chrome, WebkitPrefix, [138,0,0]], [Edge, WebkitPrefix, [138,0,0]], [IOS, WebkitPrefix, [0,0,0]], [Opera, WebkitPrefix, [122,0,0]], [Safari, WebkitPrefix, [0,0,0]]]],
  [DMaxWidth, [[Chrome, WebkitPrefix, [138,0,0]], [Edge, WebkitPrefix, [138,0,0]], [IOS, WebkitPrefix, [0,0,0]], [Opera, WebkitPrefix, [122,0,0]], [Safari, WebkitPrefix, [0,0,0]]]],
  [DMinHeight, [[Chrome, WebkitPrefix, [138,0,0]], [Edge, WebkitPrefix, [138,0,0]], [IOS, WebkitPrefix, [0,0,0]], [Opera, WebkitPrefix, [122,0,0]], [Safari, WebkitPrefix, [0,0,0]]]],
  [DMinWidth, [[Chrome, WebkitPrefix, [138,0,0]], [Edge, WebkitPrefix, [138,0,0]], [IOS, WebkitPrefix, [0,0,0]], [Opera, WebkitPrefix, [122,0,0]], [Safari, WebkitPrefix, [0,0,0]]]],
  [DPosition, [[IOS, WebkitPrefix, [13,0,0]], [Safari, WebkitPrefix, [13,0,0]]]],
  [DPrintColorAdjust, [[Chrome, WebkitPrefix, [0,0,0]], [Edge, WebkitPrefix, [0,0,0]], [Opera, WebkitPrefix, [0,0,0]], [Safari, WebkitPrefix, [15,4,0]]]],
  [DTabSize, [[Firefox, MozPrefix, [91,0,0]], [Opera, OPrefix, [15,0,0]]]],
  [DTextDecorationColor, [[Firefox, MozPrefix, [36,0,0]], [IOS, WebkitPrefix, [12,2,0]], [Safari, WebkitPrefix, [12,1,0]]]],
  [DTextDecorationLine, [[Firefox, MozPrefix, [36,0,0]], [IOS, WebkitPrefix, [12,2,0]], [Safari, WebkitPrefix, [12,1,0]]]],
  [DTextDecorationSkip, [[IOS, WebkitPrefix, [12,2,0]], [Safari, WebkitPrefix, [12,1,0]]]],
  [DTextEmphasisColor, [[Chrome, WebkitPrefix, [99,0,0]], [Edge, WebkitPrefix, [99,0,0]], [Opera, WebkitPrefix, [85,0,0]]]],
  [DTextEmphasisPosition, [[Chrome, WebkitPrefix, [99,0,0]], [Edge, WebkitPrefix, [99,0,0]], [Opera, WebkitPrefix, [85,0,0]]]],
  [DTextEmphasisStyle, [[Chrome, WebkitPrefix, [99,0,0]], [Edge, WebkitPrefix, [99,0,0]], [Opera, WebkitPrefix, [85,0,0]]]],
  [DTextOrientation, [[Safari, WebkitPrefix, [14,0,0]]]],
  [DTextSizeAdjust, [[Edge, MsPrefix, [79,0,0]], [IOS, WebkitPrefix, [0,0,0]]]],
  [DUserSelect, [[Chrome, WebkitPrefix, [54,0,0]], [Edge, MsPrefix, [79,0,0]], [Firefox, MozPrefix, [69,0,0]], [IE, MsPrefix, [0,0,0]], [IOS, WebkitPrefix, [0,0,0]], [Opera, WebkitPrefix, [41,0,0]], [Safari, KhtmlPrefix, [3,0,0]], [Safari, WebkitPrefix, [0,0,0]]]],
  [DWidth, [[Chrome, WebkitPrefix, [138,0,0]], [Edge, WebkitPrefix, [138,0,0]], [Firefox, WebkitPrefix, [0,0,0]], [IOS, WebkitPrefix, [0,0,0]], [Opera, WebkitPrefix, [122,0,0]], [Safari, WebkitPrefix, [0,0,0]]]],
];

// Go: func CSSPrefixData(constraints map[Engine]Semver) (entries map[css_ast.D]CSSPrefix)
export function cssPrefixData(constraints: Map<number, Semver>): Map<number, number> | null {
  let entries: Map<number, number> | null = null;
  for (let i = 0; i < cssPrefixTable.length; i++) {
    const property = cssPrefixTable[i][0];
    const items = cssPrefixTable[i][1];
    let prefixes = NoPrefix;
    for (const [engine, version] of constraints) {
      if (!engineIsBrowser(engine)) {
        // Specifying "--target=es2020" shouldn't affect CSS
        continue;
      }
      for (let j = 0; j < items.length; j++) {
        const item = items[j];
        const v = item[2];
        if (item[0] === engine && ((v[0] === 0 && v[1] === 0 && v[2] === 0) || compareVersions(v, 0, version) > 0)) {
          prefixes |= item[1];
        }
      }
    }
    if (prefixes !== NoPrefix) {
      if (entries === null) {
        entries = new Map();
      }
      entries.set(property, prefixes);
    }
  }
  return entries;
}
