// Port of the JavaScript half of internal/compat (compat.go, js_table.go).
//
// GENERATED by tools/gen_compat.mjs from the Go source. Do not edit by hand.
//
// compat.JSFeature is a uint64 bit set in Go ("1 << iota"). JS numbers cannot
// hold 64 bits, so a set is an immutable JSFeature object with two 32-bit
// halves: bit i of the Go value is bit i of "lo" (i < 32) or bit i-32 of "hi".
// The feature constants below are single-bit sets. Go's
// "features.Has(compat.X)" is "jsFeatureHas(features, X)", "a | b" is
// "jsFeatureOr(a, b)", and the empty set (Go's 0) is "JSFeatureNone".
import {
  SymbolPrivateField,
  SymbolPrivateMethod,
  SymbolPrivateGet,
  SymbolPrivateSet,
  SymbolPrivateGetSetPair,
  SymbolPrivateStaticField,
  SymbolPrivateStaticMethod,
  SymbolPrivateStaticGet,
  SymbolPrivateStaticSet,
  SymbolPrivateStaticGetSetPair,
} from "./ast.mjs";

export class JSFeature {
                     
                     
  constructor(lo        , hi        ) {
    this.lo = lo | 0;
    this.hi = hi | 0;
  }
  toString() {
    return this.hi + ":" + this.lo;
  }
}

function bit(i        )            {
  return Object.freeze(i < 32 ? new JSFeature(1 << i, 0) : new JSFeature(0, 1 << (i - 32)));
}

export const JSFeatureNone = Object.freeze(new JSFeature(0, 0));

// Go: func (features JSFeature) Has(feature JSFeature) bool
export function jsFeatureHas(features           , feature           )          {
  return (features.lo & feature.lo) !== 0 || (features.hi & feature.hi) !== 0;
}

// Go: a | b
export function jsFeatureOr(a           , b           )            {
  const lo = a.lo | b.lo;
  const hi = a.hi | b.hi;
  if (lo === a.lo && hi === a.hi) return a;
  return Object.freeze(new JSFeature(lo, hi));
}

// Go: a == b
export function jsFeatureEqual(a           , b           )          {
  return a.lo === b.lo && a.hi === b.hi;
}

export function jsFeatureIsEmpty(a           )          {
  return a.lo === 0 && a.hi === 0;
}

// Go: func (features JSFeature) ApplyOverrides(overrides JSFeature, mask JSFeature) JSFeature
export function jsFeatureApplyOverrides(features           , overrides           , mask           )            {
  return Object.freeze(new JSFeature((features.lo & ~mask.lo) | (overrides.lo & mask.lo), (features.hi & ~mask.hi) | (overrides.hi & mask.hi)));
}

// Engine
export const Chrome = 0;
export const Deno = 1;
export const Edge = 2;
export const ES = 3;
export const Firefox = 4;
export const Hermes = 5;
export const IE = 6;
export const IOS = 7;
export const Node = 8;
export const Opera = 9;
export const Rhino = 10;
export const Safari = 11;

// Go: func (e Engine) String() string
export function engineString(e        )         {
  switch (e) {
    case Chrome:
      return "chrome";
    case Deno:
      return "deno";
    case Edge:
      return "edge";
    case ES:
      return "es";
    case Firefox:
      return "firefox";
    case Hermes:
      return "hermes";
    case IE:
      return "ie";
    case IOS:
      return "ios";
    case Node:
      return "node";
    case Opera:
      return "opera";
    case Rhino:
      return "rhino";
    case Safari:
      return "safari";
  }
  return "";
}

// Go: func (e Engine) IsBrowser() bool
export function engineIsBrowser(e        )          {
  switch (e) {
    case Chrome:
    case Edge:
    case Firefox:
    case IE:
    case IOS:
    case Opera:
    case Safari:
      return true;
  }
  return false;
}

// JSFeature
export const ArbitraryModuleNamespaceNames = bit(0);
export const ArraySpread = bit(1);
export const Arrow = bit(2);
export const AsyncAwait = bit(3);
export const AsyncGenerator = bit(4);
export const Bigint = bit(5);
export const Class = bit(6);
export const ClassField = bit(7);
export const ClassPrivateAccessor = bit(8);
export const ClassPrivateBrandCheck = bit(9);
export const ClassPrivateField = bit(10);
export const ClassPrivateMethod = bit(11);
export const ClassPrivateStaticAccessor = bit(12);
export const ClassPrivateStaticField = bit(13);
export const ClassPrivateStaticMethod = bit(14);
export const ClassStaticBlocks = bit(15);
export const ClassStaticField = bit(16);
export const ConstAndLet = bit(17);
export const Decorators = bit(18);
export const DefaultArgument = bit(19);
export const Destructuring = bit(20);
export const DynamicImport = bit(21);
export const ExponentOperator = bit(22);
export const ExportStarAs = bit(23);
export const ForAwait = bit(24);
export const ForOf = bit(25);
export const FromBase64 = bit(26);
export const FunctionNameConfigurable = bit(27);
export const FunctionOrClassPropertyAccess = bit(28);
export const Generator = bit(29);
export const Hashbang = bit(30);
export const ImportAssertions = bit(31);
export const ImportAttributes = bit(32);
export const ImportDefer = bit(33);
export const ImportMeta = bit(34);
export const ImportSource = bit(35);
export const InlineScript = bit(36);
export const LogicalAssignment = bit(37);
export const NestedRestBinding = bit(38);
export const NewTarget = bit(39);
export const NodeColonPrefixImport = bit(40);
export const NodeColonPrefixRequire = bit(41);
export const NullishCoalescing = bit(42);
export const ObjectAccessors = bit(43);
export const ObjectExtensions = bit(44);
export const ObjectRestSpread = bit(45);
export const OptionalCatchBinding = bit(46);
export const OptionalChain = bit(47);
export const RegexpDotAllFlag = bit(48);
export const RegexpLookbehindAssertions = bit(49);
export const RegexpMatchIndices = bit(50);
export const RegexpNamedCaptureGroups = bit(51);
export const RegexpSetNotation = bit(52);
export const RegexpStickyAndUnicodeFlags = bit(53);
export const RegexpUnicodePropertyEscapes = bit(54);
export const RestArgument = bit(55);
export const TemplateLiteral = bit(56);
export const TopLevelAwait = bit(57);
export const TypeofExoticObjectIsObject = bit(58);
export const UnicodeEscapes = bit(59);
export const Using = bit(60);

export const StringToJSFeature                         = new Map([
  ["arbitrary-module-namespace-names", ArbitraryModuleNamespaceNames],
  ["array-spread", ArraySpread],
  ["arrow", Arrow],
  ["async-await", AsyncAwait],
  ["async-generator", AsyncGenerator],
  ["bigint", Bigint],
  ["class", Class],
  ["class-field", ClassField],
  ["class-private-accessor", ClassPrivateAccessor],
  ["class-private-brand-check", ClassPrivateBrandCheck],
  ["class-private-field", ClassPrivateField],
  ["class-private-method", ClassPrivateMethod],
  ["class-private-static-accessor", ClassPrivateStaticAccessor],
  ["class-private-static-field", ClassPrivateStaticField],
  ["class-private-static-method", ClassPrivateStaticMethod],
  ["class-static-blocks", ClassStaticBlocks],
  ["class-static-field", ClassStaticField],
  ["const-and-let", ConstAndLet],
  ["decorators", Decorators],
  ["default-argument", DefaultArgument],
  ["destructuring", Destructuring],
  ["dynamic-import", DynamicImport],
  ["exponent-operator", ExponentOperator],
  ["export-star-as", ExportStarAs],
  ["for-await", ForAwait],
  ["for-of", ForOf],
  ["from-base64", FromBase64],
  ["function-name-configurable", FunctionNameConfigurable],
  ["function-or-class-property-access", FunctionOrClassPropertyAccess],
  ["generator", Generator],
  ["hashbang", Hashbang],
  ["import-assertions", ImportAssertions],
  ["import-attributes", ImportAttributes],
  ["import-defer", ImportDefer],
  ["import-meta", ImportMeta],
  ["import-source", ImportSource],
  ["inline-script", InlineScript],
  ["logical-assignment", LogicalAssignment],
  ["nested-rest-binding", NestedRestBinding],
  ["new-target", NewTarget],
  ["node-colon-prefix-import", NodeColonPrefixImport],
  ["node-colon-prefix-require", NodeColonPrefixRequire],
  ["nullish-coalescing", NullishCoalescing],
  ["object-accessors", ObjectAccessors],
  ["object-extensions", ObjectExtensions],
  ["object-rest-spread", ObjectRestSpread],
  ["optional-catch-binding", OptionalCatchBinding],
  ["optional-chain", OptionalChain],
  ["regexp-dot-all-flag", RegexpDotAllFlag],
  ["regexp-lookbehind-assertions", RegexpLookbehindAssertions],
  ["regexp-match-indices", RegexpMatchIndices],
  ["regexp-named-capture-groups", RegexpNamedCaptureGroups],
  ["regexp-set-notation", RegexpSetNotation],
  ["regexp-sticky-and-unicode-flags", RegexpStickyAndUnicodeFlags],
  ["regexp-unicode-property-escapes", RegexpUnicodePropertyEscapes],
  ["rest-argument", RestArgument],
  ["template-literal", TemplateLiteral],
  ["top-level-await", TopLevelAwait],
  ["typeof-exotic-object-is-object", TypeofExoticObjectIsObject],
  ["unicode-escapes", UnicodeEscapes],
  ["using", Using],
]);

// Go: jsTable (feature -> engine -> version ranges). A range is
// [major, minor, patch] (no end) or [major, minor, patch, endMajor, endMinor, endPatch].
const jsTable                                        = [
  [ArbitraryModuleNamespaceNames, [[Chrome, [[90,0,0]]], [ES, [[2022,0,0]]], [Firefox, [[87,0,0]]], [IOS, [[14,5,0]]], [Node, [[16,0,0]]], [Safari, [[14,1,0]]]]],
  [ArraySpread, [[Chrome, [[46,0,0]]], [Deno, [[1,0,0]]], [Edge, [[13,0,0]]], [ES, [[2015,0,0]]], [Firefox, [[36,0,0]]], [Hermes, [[0,7,0]]], [IOS, [[10,0,0]]], [Node, [[5,0,0]]], [Opera, [[33,0,0]]], [Safari, [[10,0,0]]]]],
  [Arrow, [[Chrome, [[49,0,0]]], [Deno, [[1,0,0]]], [Edge, [[13,0,0]]], [ES, [[2015,0,0]]], [Firefox, [[45,0,0]]], [IOS, [[10,0,0]]], [Node, [[6,0,0]]], [Opera, [[36,0,0]]], [Safari, [[10,0,0]]]]],
  [AsyncAwait, [[Chrome, [[55,0,0]]], [Deno, [[1,0,0]]], [Edge, [[15,0,0]]], [ES, [[2017,0,0]]], [Firefox, [[52,0,0]]], [IOS, [[11,0,0]]], [Node, [[7,6,0]]], [Opera, [[42,0,0]]], [Safari, [[11,0,0]]]]],
  [AsyncGenerator, [[Chrome, [[63,0,0]]], [Deno, [[1,0,0]]], [Edge, [[79,0,0]]], [ES, [[2018,0,0]]], [Firefox, [[57,0,0]]], [IOS, [[12,0,0]]], [Node, [[10,0,0]]], [Opera, [[50,0,0]]], [Safari, [[12,0,0]]]]],
  [Bigint, [[Chrome, [[67,0,0]]], [Deno, [[1,0,0]]], [Edge, [[79,0,0]]], [ES, [[2020,0,0]]], [Firefox, [[68,0,0]]], [Hermes, [[0,12,0]]], [IOS, [[14,0,0]]], [Node, [[10,4,0]]], [Opera, [[54,0,0]]], [Rhino, [[1,7,14]]], [Safari, [[14,0,0]]]]],
  [Class, [[Chrome, [[49,0,0]]], [Deno, [[1,0,0]]], [Edge, [[13,0,0]]], [ES, [[2015,0,0]]], [Firefox, [[45,0,0]]], [IOS, [[10,0,0]]], [Node, [[6,0,0]]], [Opera, [[36,0,0]]], [Safari, [[10,0,0]]]]],
  [ClassField, [[Chrome, [[73,0,0]]], [Deno, [[1,0,0]]], [Edge, [[79,0,0]]], [ES, [[2022,0,0]]], [Firefox, [[69,0,0]]], [IOS, [[14,0,0]]], [Node, [[12,0,0]]], [Opera, [[60,0,0]]], [Safari, [[14,0,0]]]]],
  [ClassPrivateAccessor, [[Chrome, [[84,0,0]]], [Deno, [[1,0,0]]], [Edge, [[84,0,0]]], [ES, [[2022,0,0]]], [Firefox, [[90,0,0]]], [IOS, [[15,0,0]]], [Node, [[14,6,0]]], [Opera, [[70,0,0]]], [Safari, [[15,0,0]]]]],
  [ClassPrivateBrandCheck, [[Chrome, [[91,0,0]]], [Deno, [[1,9,0]]], [Edge, [[91,0,0]]], [ES, [[2022,0,0]]], [Firefox, [[90,0,0]]], [IOS, [[15,0,0]]], [Node, [[16,9,0]]], [Opera, [[77,0,0]]], [Safari, [[15,0,0]]]]],
  [ClassPrivateField, [[Chrome, [[84,0,0]]], [Deno, [[1,0,0]]], [Edge, [[84,0,0]]], [ES, [[2022,0,0]]], [Firefox, [[90,0,0]]], [IOS, [[14,5,0]]], [Node, [[14,6,0]]], [Opera, [[70,0,0]]], [Safari, [[14,1,0]]]]],
  [ClassPrivateMethod, [[Chrome, [[84,0,0]]], [Deno, [[1,0,0]]], [Edge, [[84,0,0]]], [ES, [[2022,0,0]]], [Firefox, [[90,0,0]]], [IOS, [[15,0,0]]], [Node, [[14,6,0]]], [Opera, [[70,0,0]]], [Safari, [[15,0,0]]]]],
  [ClassPrivateStaticAccessor, [[Chrome, [[84,0,0]]], [Deno, [[1,0,0]]], [Edge, [[84,0,0]]], [ES, [[2022,0,0]]], [Firefox, [[90,0,0]]], [IOS, [[15,0,0]]], [Node, [[14,6,0]]], [Opera, [[70,0,0]]], [Safari, [[15,0,0]]]]],
  [ClassPrivateStaticField, [[Chrome, [[74,0,0]]], [Deno, [[1,0,0]]], [Edge, [[79,0,0]]], [ES, [[2022,0,0]]], [Firefox, [[90,0,0]]], [IOS, [[14,5,0]]], [Node, [[12,0,0]]], [Opera, [[62,0,0]]], [Safari, [[14,1,0]]]]],
  [ClassPrivateStaticMethod, [[Chrome, [[84,0,0]]], [Deno, [[1,0,0]]], [Edge, [[84,0,0]]], [ES, [[2022,0,0]]], [Firefox, [[90,0,0]]], [IOS, [[15,0,0]]], [Node, [[14,6,0]]], [Opera, [[70,0,0]]], [Safari, [[15,0,0]]]]],
  [ClassStaticBlocks, [[Chrome, [[91,0,0]]], [Deno, [[1,14,0]]], [Edge, [[94,0,0]]], [ES, [[2022,0,0]]], [Firefox, [[93,0,0]]], [IOS, [[16,4,0]]], [Node, [[16,11,0]]], [Opera, [[80,0,0]]], [Safari, [[16,4,0]]]]],
  [ClassStaticField, [[Chrome, [[73,0,0]]], [Deno, [[1,0,0]]], [Edge, [[79,0,0]]], [ES, [[2022,0,0]]], [Firefox, [[75,0,0]]], [IOS, [[14,5,0]]], [Node, [[12,0,0]]], [Opera, [[60,0,0]]], [Safari, [[14,1,0]]]]],
  [ConstAndLet, [[Chrome, [[49,0,0]]], [Deno, [[1,0,0]]], [Edge, [[14,0,0]]], [ES, [[2015,0,0]]], [Firefox, [[51,0,0]]], [IOS, [[11,0,0]]], [Node, [[6,0,0]]], [Opera, [[36,0,0]]], [Safari, [[11,0,0]]]]],
  [Decorators, []],
  [DefaultArgument, [[Chrome, [[49,0,0]]], [Deno, [[1,0,0]]], [Edge, [[14,0,0]]], [ES, [[2015,0,0]]], [Firefox, [[53,0,0]]], [IOS, [[10,0,0]]], [Node, [[6,0,0]]], [Opera, [[36,0,0]]], [Safari, [[10,0,0]]]]],
  [Destructuring, [[Chrome, [[51,0,0]]], [Deno, [[1,0,0]]], [Edge, [[18,0,0]]], [ES, [[2015,0,0]]], [Firefox, [[53,0,0]]], [IOS, [[14,5,0]]], [Node, [[6,5,0]]], [Opera, [[38,0,0]]], [Safari, [[14,1,0]]]]],
  [DynamicImport, [[Chrome, [[63,0,0]]], [Edge, [[79,0,0]]], [ES, [[2015,0,0]]], [Firefox, [[67,0,0]]], [IOS, [[11,0,0]]], [Node, [[12,20,0,13,0,0],[13,2,0]]], [Opera, [[50,0,0]]], [Safari, [[11,1,0]]]]],
  [ExponentOperator, [[Chrome, [[52,0,0]]], [Deno, [[1,0,0]]], [Edge, [[14,0,0]]], [ES, [[2016,0,0]]], [Firefox, [[52,0,0]]], [Hermes, [[0,7,0]]], [IOS, [[10,3,0]]], [Node, [[7,0,0]]], [Opera, [[39,0,0]]], [Rhino, [[1,7,14]]], [Safari, [[10,1,0]]]]],
  [ExportStarAs, [[Chrome, [[72,0,0]]], [Deno, [[1,0,0]]], [Edge, [[79,0,0]]], [ES, [[2020,0,0]]], [Firefox, [[80,0,0]]], [IOS, [[14,5,0]]], [Node, [[13,2,0]]], [Opera, [[60,0,0]]], [Safari, [[14,1,0]]]]],
  [ForAwait, [[Chrome, [[63,0,0]]], [Deno, [[1,0,0]]], [Edge, [[79,0,0]]], [ES, [[2018,0,0]]], [Firefox, [[57,0,0]]], [IOS, [[12,0,0]]], [Node, [[10,0,0]]], [Opera, [[50,0,0]]], [Safari, [[12,0,0]]]]],
  [ForOf, [[Chrome, [[51,0,0]]], [Deno, [[1,0,0]]], [Edge, [[15,0,0]]], [ES, [[2015,0,0]]], [Firefox, [[53,0,0]]], [Hermes, [[0,7,0]]], [IOS, [[10,0,0]]], [Node, [[6,5,0]]], [Opera, [[38,0,0]]], [Safari, [[10,0,0]]]]],
  [FromBase64, [[Chrome, [[140,0,0]]], [Deno, [[2,5,0]]], [Edge, [[140,0,0]]], [Firefox, [[133,0,0]]], [IOS, [[18,2,0]]], [Node, [[25,0,0]]], [Opera, [[124,0,0]]], [Safari, [[18,2,0]]]]],
  [FunctionNameConfigurable, [[Chrome, [[43,0,0]]], [Deno, [[1,0,0]]], [Edge, [[12,0,0]]], [ES, [[2015,0,0]]], [Firefox, [[38,0,0]]], [Hermes, [[0,7,0]]], [IOS, [[10,0,0]]], [Node, [[4,0,0]]], [Opera, [[30,0,0]]], [Rhino, [[1,7,15]]], [Safari, [[10,0,0]]]]],
  [FunctionOrClassPropertyAccess, [[Chrome, [[0,0,0]]], [Deno, [[0,0,0]]], [Edge, [[0,0,0]]], [ES, [[0,0,0]]], [Firefox, [[0,0,0]]], [Hermes, [[0,0,0]]], [IE, [[0,0,0]]], [IOS, [[0,0,0]]], [Node, [[0,0,0]]], [Opera, [[0,0,0]]], [Rhino, [[0,0,0]]], [Safari, [[16,3,0]]]]],
  [Generator, [[Chrome, [[50,0,0]]], [Deno, [[1,0,0]]], [Edge, [[13,0,0]]], [ES, [[2015,0,0]]], [Firefox, [[53,0,0]]], [IOS, [[10,0,0]]], [Node, [[6,0,0]]], [Opera, [[37,0,0]]], [Safari, [[10,0,0]]]]],
  [Hashbang, [[Chrome, [[74,0,0]]], [Deno, [[1,0,0]]], [Edge, [[79,0,0]]], [ES, [[2023,0,0]]], [Firefox, [[67,0,0]]], [Hermes, [[0,7,0]]], [IOS, [[13,4,0]]], [Node, [[12,0,0]]], [Opera, [[62,0,0]]], [Rhino, [[1,7,15]]], [Safari, [[13,1,0]]]]],
  [ImportAssertions, [[Chrome, [[91,0,0]]], [Deno, [[1,17,0]]], [Edge, [[91,0,0]]], [Node, [[16,14,0,22,0,0]]]]],
  [ImportAttributes, [[Chrome, [[123,0,0]]], [Deno, [[1,37,0]]], [Edge, [[123,0,0]]], [Firefox, [[138,0,0]]], [IOS, [[17,2,0]]], [Node, [[18,20,0,19,0,0],[20,10,0]]], [Opera, [[109,0,0]]], [Safari, [[17,2,0]]]]],
  [ImportDefer, []],
  [ImportMeta, [[Chrome, [[64,0,0]]], [Deno, [[1,0,0]]], [Edge, [[79,0,0]]], [ES, [[2020,0,0]]], [Firefox, [[62,0,0]]], [IOS, [[12,0,0]]], [Node, [[10,4,0]]], [Opera, [[51,0,0]]], [Safari, [[11,1,0]]]]],
  [ImportSource, []],
  [InlineScript, []],
  [LogicalAssignment, [[Chrome, [[85,0,0]]], [Deno, [[1,2,0]]], [Edge, [[85,0,0]]], [ES, [[2021,0,0]]], [Firefox, [[79,0,0]]], [Hermes, [[0,7,0]]], [IOS, [[14,0,0]]], [Node, [[15,0,0]]], [Opera, [[71,0,0]]], [Safari, [[14,0,0]]]]],
  [NestedRestBinding, [[Chrome, [[49,0,0]]], [Deno, [[1,0,0]]], [Edge, [[14,0,0]]], [ES, [[2016,0,0]]], [Firefox, [[47,0,0]]], [Hermes, [[0,7,0]]], [IOS, [[10,3,0]]], [Node, [[6,0,0]]], [Opera, [[36,0,0]]], [Safari, [[10,1,0]]]]],
  [NewTarget, [[Chrome, [[46,0,0]]], [Deno, [[1,0,0]]], [Edge, [[14,0,0]]], [ES, [[2015,0,0]]], [Firefox, [[41,0,0]]], [Hermes, [[0,7,0]]], [IOS, [[10,0,0]]], [Node, [[5,0,0]]], [Opera, [[33,0,0]]], [Safari, [[10,0,0]]]]],
  [NodeColonPrefixImport, [[ES, [[0,0,0]]], [Node, [[12,20,0,13,0,0],[14,13,1]]]]],
  [NodeColonPrefixRequire, [[ES, [[0,0,0]]], [Node, [[14,18,0,15,0,0],[16,0,0]]]]],
  [NullishCoalescing, [[Chrome, [[80,0,0]]], [Deno, [[1,0,0]]], [Edge, [[80,0,0]]], [ES, [[2020,0,0]]], [Firefox, [[72,0,0]]], [Hermes, [[0,7,0]]], [IOS, [[13,4,0]]], [Node, [[14,0,0]]], [Opera, [[67,0,0]]], [Rhino, [[1,8,0]]], [Safari, [[13,1,0]]]]],
  [ObjectAccessors, [[Chrome, [[5,0,0]]], [Deno, [[1,0,0]]], [Edge, [[12,0,0]]], [ES, [[5,0,0]]], [Firefox, [[2,0,0]]], [Hermes, [[0,7,0]]], [IE, [[9,0,0]]], [IOS, [[6,0,0]]], [Node, [[0,4,0]]], [Opera, [[10,10,0]]], [Rhino, [[1,7,13]]], [Safari, [[3,1,0]]]]],
  [ObjectExtensions, [[Chrome, [[44,0,0]]], [Deno, [[1,0,0]]], [Edge, [[12,0,0]]], [ES, [[2015,0,0]]], [Firefox, [[34,0,0]]], [Hermes, [[0,7,0]]], [IOS, [[10,0,0]]], [Node, [[4,0,0]]], [Opera, [[31,0,0]]], [Rhino, [[1,8,0]]], [Safari, [[10,0,0]]]]],
  [ObjectRestSpread, [[Chrome, [[60,0,0]]], [Deno, [[1,0,0]]], [Edge, [[79,0,0]]], [ES, [[2018,0,0]]], [Firefox, [[55,0,0]]], [Hermes, [[0,7,0]]], [IOS, [[11,3,0]]], [Node, [[8,3,0]]], [Opera, [[47,0,0]]], [Safari, [[11,1,0]]]]],
  [OptionalCatchBinding, [[Chrome, [[66,0,0]]], [Deno, [[1,0,0]]], [Edge, [[79,0,0]]], [ES, [[2019,0,0]]], [Firefox, [[58,0,0]]], [Hermes, [[0,12,0]]], [IOS, [[11,3,0]]], [Node, [[10,0,0]]], [Opera, [[53,0,0]]], [Safari, [[11,1,0]]]]],
  [OptionalChain, [[Chrome, [[91,0,0]]], [Deno, [[1,9,0]]], [Edge, [[91,0,0]]], [ES, [[2020,0,0]]], [Firefox, [[74,0,0]]], [Hermes, [[0,12,0]]], [IOS, [[13,4,0]]], [Node, [[16,9,0]]], [Opera, [[77,0,0]]], [Safari, [[13,1,0]]]]],
  [RegexpDotAllFlag, [[Chrome, [[62,0,0]]], [Deno, [[1,0,0]]], [Edge, [[79,0,0]]], [ES, [[2018,0,0]]], [Firefox, [[78,0,0]]], [Hermes, [[0,7,0]]], [IOS, [[11,3,0]]], [Node, [[8,10,0]]], [Opera, [[49,0,0]]], [Rhino, [[1,7,15]]], [Safari, [[11,1,0]]]]],
  [RegexpLookbehindAssertions, [[Chrome, [[62,0,0]]], [Deno, [[1,0,0]]], [Edge, [[79,0,0]]], [ES, [[2018,0,0]]], [Firefox, [[78,0,0]]], [Hermes, [[0,7,0]]], [IOS, [[16,4,0]]], [Node, [[8,10,0]]], [Opera, [[49,0,0]]], [Rhino, [[1,9,0]]], [Safari, [[16,4,0]]]]],
  [RegexpMatchIndices, [[Chrome, [[90,0,0]]], [Deno, [[1,8,0]]], [Edge, [[90,0,0]]], [ES, [[2022,0,0]]], [Firefox, [[88,0,0]]], [IOS, [[15,0,0]]], [Node, [[16,0,0]]], [Opera, [[76,0,0]]], [Safari, [[15,0,0]]]]],
  [RegexpNamedCaptureGroups, [[Chrome, [[64,0,0]]], [Deno, [[1,0,0]]], [Edge, [[79,0,0]]], [ES, [[2018,0,0]]], [Firefox, [[78,0,0]]], [IOS, [[11,3,0]]], [Node, [[10,0,0]]], [Opera, [[51,0,0]]], [Rhino, [[1,9,0]]], [Safari, [[11,1,0]]]]],
  [RegexpSetNotation, [[ES, [[2024,0,0]]]]],
  [RegexpStickyAndUnicodeFlags, [[Chrome, [[50,0,0]]], [Deno, [[1,0,0]]], [Edge, [[13,0,0]]], [ES, [[2015,0,0]]], [Firefox, [[46,0,0]]], [Hermes, [[0,7,0]]], [IOS, [[12,0,0]]], [Node, [[6,0,0]]], [Opera, [[37,0,0]]], [Safari, [[12,0,0]]]]],
  [RegexpUnicodePropertyEscapes, [[ES, [[2018,0,0]]], [Firefox, [[147,0,0]]]]],
  [RestArgument, [[Chrome, [[47,0,0]]], [Deno, [[1,0,0]]], [Edge, [[12,0,0]]], [ES, [[2015,0,0]]], [Firefox, [[43,0,0]]], [IOS, [[10,0,0]]], [Node, [[6,0,0]]], [Opera, [[34,0,0]]], [Safari, [[10,0,0]]]]],
  [TemplateLiteral, [[Chrome, [[62,0,0]]], [Deno, [[1,0,0]]], [Edge, [[79,0,0]]], [ES, [[2015,0,0]]], [Firefox, [[53,0,0]]], [IOS, [[13,0,0]]], [Node, [[8,10,0]]], [Opera, [[49,0,0]]], [Rhino, [[1,9,0]]], [Safari, [[13,0,0]]]]],
  [TopLevelAwait, [[Chrome, [[89,0,0]]], [Deno, [[1,0,0]]], [Edge, [[89,0,0]]], [ES, [[2022,0,0]]], [Firefox, [[89,0,0]]], [IOS, [[15,0,0]]], [Node, [[14,8,0]]], [Opera, [[75,0,0]]], [Safari, [[15,0,0]]]]],
  [TypeofExoticObjectIsObject, [[Chrome, [[0,0,0]]], [Deno, [[0,0,0]]], [Edge, [[0,0,0]]], [ES, [[2020,0,0]]], [Firefox, [[0,0,0]]], [Hermes, [[0,0,0]]], [IOS, [[0,0,0]]], [Node, [[0,0,0]]], [Opera, [[0,0,0]]], [Rhino, [[0,0,0]]], [Safari, [[0,0,0]]]]],
  [UnicodeEscapes, [[Chrome, [[44,0,0]]], [Deno, [[1,0,0]]], [Edge, [[12,0,0]]], [ES, [[2015,0,0]]], [Firefox, [[53,0,0]]], [Hermes, [[0,7,0]]], [IOS, [[9,0,0]]], [Node, [[4,0,0]]], [Opera, [[31,0,0]]], [Rhino, [[1,7,15]]], [Safari, [[9,0,0]]]]],
  [Using, [[Chrome, [[141,0,0]]], [Edge, [[141,0,0]]], [Firefox, [[141,0,0]]], [Node, [[25,0,0]]]]],
];

// Go: type Semver struct { Parts []int; PreRelease string }
export class Semver {
                          
                             
  constructor(parts           = [], preRelease = "") {
    this.parts = parts;
    this.preRelease = preRelease;
  }
}

// Go: func compareVersions(a v, b Semver) int. "a" is [major, minor, patch]
// at offset "i" of a range.
function compareVersions(a          , i        , b        )         {
  let diff = a[i];
  if (b.parts.length > 0) diff -= b.parts[0];
  if (diff === 0) {
    diff = a[i + 1];
    if (b.parts.length > 1) diff -= b.parts[1];
  }
  if (diff === 0) {
    diff = a[i + 2];
    if (b.parts.length > 2) diff -= b.parts[2];
  }
  if (diff === 0 && b.preRelease.length !== 0) {
    return 1; // "1.0.0" > "1.0.0-alpha"
  }
  return diff;
}

function splitOffNextPreReleasePart(text        )                   {
  const i = text.indexOf(".");
  if (i !== -1) return [text.slice(0, i), text.slice(i + 1)];
  return [text, ""];
}

// Go: strconv.Atoi of a string of ASCII digits ("ok" is false on overflow)
function preReleasePartToNumber(text        )                    {
  for (let i = 0; i < text.length; i++) {
    const c = text.charCodeAt(i);
    if (c < 48 || c > 57) return [0, false];
  }
  if (text === "") return [0, false];
  const n = Number(text);
  if (n > 9223372036854775807) return [0, false];
  return [n, true];
}

// Go: func CompareSemver(a Semver, b Semver) int
export function compareSemver(a        , b        )         {
  const an = a.parts.length;
  const bn = b.parts.length;
  let n = an;
  if (bn > n) n = bn;
  for (let i = 0; i < n; i++) {
    let ai = 0;
    let bi = 0;
    if (i < an) ai = a.parts[i];
    if (i < bn) bi = b.parts[i];
    if (ai !== bi) return ai - bi;
  }
  if ((a.preRelease !== "") !== (b.preRelease !== "")) {
    return b.preRelease.length - a.preRelease.length;
  }
  let a_tail = a.preRelease.startsWith("-") ? a.preRelease.slice(1) : a.preRelease;
  let b_tail = b.preRelease.startsWith("-") ? b.preRelease.slice(1) : b.preRelease;
  while (a_tail !== "" && b_tail !== "") {
    let a_head        , b_head        ;
    [a_head, a_tail] = splitOffNextPreReleasePart(a_tail);
    [b_head, b_tail] = splitOffNextPreReleasePart(b_tail);
    if (a_head === b_head) continue;
    const [a_num, a_isnum] = preReleasePartToNumber(a_head);
    const [b_num, b_isnum] = preReleasePartToNumber(b_head);
    if (!a_isnum && !b_isnum) {
      // Lexicographic comparison for non-numbers (ASCII, so UTF-16 order is byte order)
      return a_head < b_head ? -1 : 1;
    } else if (a_isnum && b_isnum) {
      if (a_num !== b_num) return a_num - b_num;
      // Compare lengths for different text but equal numbers (e.g. "0" vs. "00")
      return a_head.length - b_head.length;
    } else {
      return a_isnum ? -1 : 1;
    }
  }
  return a_tail.length - b_tail.length;
}

// Go: func (v Semver) String() string
export function semverString(v        )         {
  return v.parts.join(".") + v.preRelease;
}

// Go: func isVersionSupported(ranges []versionRange, version Semver) bool
function isVersionSupported(ranges            , version        )          {
  for (let i = 0; i < ranges.length; i++) {
    const r = ranges[i];
    if (compareVersions(r, 0, version) <= 0 && (r.length === 3 || compareVersions(r, 3, version) > 0)) {
      return true;
    }
  }
  return false;
}

// Go: func UnsupportedJSFeatures(constraints map[Engine]Semver) (unsupported JSFeature)
// Return all features that are not available in at least one environment
export function unsupportedJSFeatures(constraints                     )            {
  let lo = 0;
  let hi = 0;
  for (let i = 0; i < jsTable.length; i++) {
    const [feature, engines] = jsTable[i];
    if (feature === InlineScript) {
      continue; // This is purely user-specified
    }
    for (const [engine, version] of constraints) {
      let versionRanges                    = null;
      for (let j = 0; j < engines.length; j++) {
        if (engines[j][0] === engine) {
          versionRanges = engines[j][1];
          break;
        }
      }
      if (versionRanges === null || !isVersionSupported(versionRanges, version)) {
        lo |= feature.lo;
        hi |= feature.hi;
      }
    }
  }
  return lo === 0 && hi === 0 ? JSFeatureNone : Object.freeze(new JSFeature(lo, hi));
}

// Go: func SymbolFeature(kind ast.SymbolKind) JSFeature
export function symbolFeature(kind        )            {
  switch (kind) {
    case SymbolPrivateField:
      return ClassPrivateField;
    case SymbolPrivateMethod:
      return ClassPrivateMethod;
    case SymbolPrivateGet:
    case SymbolPrivateSet:
    case SymbolPrivateGetSetPair:
      return ClassPrivateAccessor;
    case SymbolPrivateStaticField:
      return ClassPrivateStaticField;
    case SymbolPrivateStaticMethod:
      return ClassPrivateStaticMethod;
    case SymbolPrivateStaticGet:
    case SymbolPrivateStaticSet:
    case SymbolPrivateStaticGetSetPair:
      return ClassPrivateStaticAccessor;
    default:
      return JSFeatureNone;
  }
}
// generated from compat.mts by tools/ts-build.mjs; edit that file
