// Port of internal/js_ast/js_ident.go and internal/js_ast/unicode.go.
// GENERATED by tools/gen_js_ident.mjs from the esbuild Go source: do not edit
// by hand (edit the generator instead).
//
// Go strings iterated with "range" are WTF-8 there; here they are JS strings.
// A lone surrogate is never an identifier character in either representation.

// ---------------------------------------------------------------------------
// Unicode tables (unicode.go). Each table is a sorted list of inclusive
// [lo, hi] ranges (all Go ranges have Stride 1), encoded as base-36 deltas:
// lo0, hi0-lo0, lo1-hi0, hi1-lo1, ...

// 255 ranges
const idStartES5AndESNextEnc =
  "1t,p,7,p,1c,0,b,0,5,0,6,m,2,u,2,87,3,h,t,2l,3,8,3,6,f,1,f,4,a,0,3w,0,c,0,2,2,2,0,2,j,2,17,2,7,3,p,d," +
  "3l,b,1k,3,1,3,1,4,11,3,1,1k,11,3,0,8,12,21,q,6,2,1b,p,6,a,13,2q,2,0,g,1,k,2,k,0,2,q,2c,11,9s,1g,4,0," +
  "j,0,8,9,10,7,3,1,3,l,2,6,2,0,4,3,z,1,2,2,f,1,k,5,5,1,3,l,2,6,2,1,2,1,2,1,w,3,2,0,k,2,h,6,2,0,2,2,2,l," +
  "2,6,2,1,2,4,4,0,j,0,g,0,11,7,3,1,3,l,2,6,2,1,3,3,4,0,v,1,2,2,10,5,4,2,2,3,4,1,2,0,2,1,4,1,4,2,4,7,2," +
  "2,24,7,2,2,2,m,2,9,2,4,13,1,10,7,2,2,2,m,2,9,2,4,11,0,2,1,10,7,2,2,2,m,2,f,13,1,10,h,4,n,2,8,2,0,3,6," +
  "1n,1b,2,1,d,6,1n,1,2,0,3,1,2,0,3,0,7,3,2,6,2,2,2,0,2,0,3,1,2,3,2,1,a,0,3,4,2,0,m,1,z,0,1s,7,2,x,u,3," +
  "39,x,2,4,2,1,12,5,23,11,b,12,a,2h,6,1v,6,29,7,6,2,1q,2,0,2,3,3,6,2,0,2,3,3,12,2,0,2,3,3,u,2,0,2,3,3," +
  "6,2,0,2,3,3,6,2,6,2,m,2,u,2,0,2,3,3,6,2,12,2,i,1y,2c,d,h7,3,7,b,p,6,22,46,1f,31,2f,9,14,120,4b,5,2h," +
  "7,l,3,5,3,11,3,5,3,7,2,0,2,0,2,0,2,u,3,1g,2,6,2,0,4,2,2,6,4,3,3,5,5,c,6,2,2,6,3n,0,3n,0,5,0,3,9,2,0," +
  "4,4,7,0,2,0,2,0,2,3,2,2,2,6,2x8,1,17,4,c,2b,9,1,3,2h,2,2,7,13,5,2l,i,n,g9,52t,23,g4l,2j,wc,1h0,8mb," +
  "6l9,8d,5v,6,d,4,6,0,2,9,2,c,2,4,2,0,2,1,2,1,2,2z,y,a2,j,1r,3,1h,15,b,39,2,2,0,2,3q,11,p,7,p,c,2g,4,5," +
  "3,5,3,5,3,2";
// 345 ranges
const idContinueES5AndESNextEnc =
  "1c,9,8,p,5,0,2,p,1c,0,b,0,5,0,6,m,2,u,2,87,3,h,t,2l,3,8,3,6,f,1,f,4,a,0,i,26,i,2,o,0,c,0,2,2,2,0,2,j," +
  "2,17,2,7,3,p,d,3l,2,3,6,1k,3,1,3,1,4,11,3,1,1k,11,3,0,8,12,a,g,2,m,2,2,2,0,2,1,2,0,c,q,6,2,1b,p,6,l," +
  "b,9,7,2r,2,7,3,9,2,3,3,c,k,s,4,q,1i,1c,9d,2,2,1g,3,h,3,4,4,b,3,9,i,2,2,7,3,1,3,l,2,6,2,0,4,3,3,0,2,6," +
  "3,1,3,2,a,0,5,1,2,4,3,b,h,0,3,5,5,1,3,l,2,6,2,1,2,1,2,1,3,0,2,4,5,1,3,2,c,3,2,0,8,e,d,2,2,6,2,0,2,2," +
  "2,l,2,6,2,1,2,4,3,9,2,2,2,2,3,0,g,0,6,9,i,2,2,7,3,1,3,l,2,6,2,1,3,3,3,7,4,1,3,2,9,1,5,1,2,2,5,9,j,1," +
  "2,5,4,2,2,3,4,1,2,0,2,1,4,1,4,2,4,7,2,2,5,4,4,2,2,3,a,0,g,8,i,2,2,7,2,2,2,m,2,9,2,4,5,6,2,2,2,3,8,1," +
  "a,1,5,9,j,1,2,7,2,2,2,m,2,9,2,4,5,6,2,2,2,3,8,1,8,0,2,1,5,9,j,1,2,7,2,2,2,m,2,f,5,5,3,2,2,3,a,0,9,1," +
  "5,9,j,1,2,h,4,n,2,8,2,0,3,6,4,0,5,5,2,0,2,7,j,1,e,1l,6,e,2,9,14,1,2,0,3,1,2,0,3,0,7,3,2,6,2,2,2,0,2," +
  "0,3,1,2,c,2,2,3,4,2,0,2,5,3,9,3,1,z,0,o,1,7,9,c,0,2,0,2,0,5,9,2,x,7,j,2,5,5,7,2,z,a,0,1m,x,2,4,2,1,2," +
  "6,4,3,7,9,7,9,1z,11,b,12,a,2h,6,1v,6,29,7,6,2,1q,2,0,2,3,3,6,2,0,2,3,3,12,2,0,2,3,3,u,2,0,2,3,3,6,2," +
  "0,2,3,3,6,2,6,2,m,2,u,2,0,2,3,3,6,2,12,2,i,f,8,1b,2c,d,h7,3,7,b,p,6,22,46,2b,d,9,13,9,7,2f,9,15,11z," +
  "4b,5,2h,7,l,3,5,3,11,3,5,3,7,2,0,2,0,2,0,2,u,3,1g,2,6,2,0,4,2,2,6,4,3,3,5,5,c,6,2,2,6,1v,1,1r,0,29,c," +
  "5,0,x,0,5,0,3,9,2,0,4,4,7,0,2,0,2,0,2,3,2,2,2,6,2x8,1,10,5,2,4,c,2b,5,1,3,1,3,2h,2,2,7,13,5,2l,i,n," +
  "g9,52t,23,g4l,2j,wc,1h0,8mb,6l9,8d,5v,6,d,4,6,b,2,c,2,4,2,0,2,1,2,1,2,2z,y,a2,j,1r,3,1h,15,b,11,3,g," +
  "1,p,2,x,2,2,0,2,3q,k,9,8,p,5,0,2,p,c,2g,4,5,3,5,3,5,3,2";
// 660 ranges
const idStartES5OrESNextEnc =
  "1t,p,7,p,1c,0,b,0,5,0,6,m,2,u,2,cp,5,b,f,4,8,0,2,0,3m,4,2,1,3,3,2,0,7,0,2,2,2,0,2,j,2,2a,2,3u,9,4l,2," +
  "11,3,0,7,14,20,q,5,3,1a,16,10,1,2,2q,2,0,g,1,8,1,b,2,3,0,h,0,2,t,u,2g,c,0,p,w,a,1,5,0,6,l,5,0,a,0,4," +
  "0,o,o,8,a,6,n,2,5,i,15,1n,1h,4,0,j,0,8,9,g,f,5,7,3,1,3,l,2,6,2,0,4,3,4,0,h,0,e,1,2,2,f,1,b,0,9,5,5,1," +
  "3,l,2,6,2,1,2,1,2,1,w,3,2,0,k,2,h,8,2,2,2,l,2,6,2,1,2,4,4,0,j,0,g,1,o,0,c,7,3,1,3,l,2,6,2,1,2,4,4,0," +
  "v,1,2,2,g,0,i,0,2,5,4,2,2,3,4,1,2,0,2,1,4,1,4,2,4,b,n,0,1h,7,2,2,2,m,2,f,4,0,r,2,3,0,3,1,v,0,5,7,2,2," +
  "2,m,2,9,2,4,4,0,w,1,2,1,g,1,i,8,2,2,2,14,3,0,h,0,6,2,9,2,p,5,6,h,4,n,2,8,2,0,3,6,1n,1b,2,1,d,6,1n,1," +
  "2,0,2,4,2,n,2,0,2,9,2,1,a,0,3,4,2,0,m,3,x,0,1s,7,2,z,s,4,38,16,l,0,h,5,5,3,4,0,4,1,8,2,5,c,d,0,i,11," +
  "2,0,6,0,3,16,2,98,2,3,3,6,2,0,2,3,3,14,2,3,3,w,2,3,3,6,2,0,2,3,3,e,2,1k,2,3,3,1u,12,f,h,2d,3,5,4,h7," +
  "3,g,2,p,6,22,4,a,8,h,e,i,f,h,f,c,2,2,g,1f,10,0,5,0,1w,2g,8,14,2,0,6,1x,b,u,1e,t,3,4,c,17,5,p,1j,m,a," +
  "1g,2b,0,2m,1a,i,7,1j,t,e,1,b,17,r,z,16,2,b,z,3,8,8,16,3,2,16,3,2,5,2,1,4,0,6,5b,1t,7p,3,5,3,11,3,5,3," +
  "7,2,0,2,0,2,0,2,u,3,1g,2,6,2,0,4,2,2,6,4,3,3,5,5,c,6,2,2,6,39,0,e,0,h,c,2u,0,5,0,3,9,2,0,3,5,7,0,2,0," +
  "2,0,2,f,3,3,6,4,5,0,i,14,22g,6c,7,3,4,1,d,11,2,0,6,0,3,1j,8,0,h,m,a,6,2,6,2,6,2,6,2,6,2,6,2,6,2,6,fb," +
  "2,q,8,8,4,3,4,5,2d,5,4,2,2h,2,3,6,16,2,2l,i,v,1d,f,e9,533,1t,h3g,1w,19,3,7g,4,f,b,1,l,1a,h,u,3,27,14," +
  "8,3,2u,3,1r,6,1,2,0,2,4,p,f,2,2,2,3,2,m,u,1f,f,1d,1r,5,4,0,2,1,c,r,b,m,q,s,8,1a,t,0,h,4,2,9,b,4,2,14," +
  "o,2,2,7,l,m,4,0,4,1d,2,0,4,1,3,4,3,0,2,0,p,2,3,a,8,2,d,5,3,5,3,5,a,6,2,6,2,16,2,d,7,36,u,8mb,d,m,5," +
  "1c,6it,a5,3,2x,13,6,d,4,6,0,2,9,2,c,2,4,2,0,2,1,2,1,2,2z,y,a2,j,1r,3,1h,15,b,39,4,2,3q,11,p,7,p,c,2g," +
  "4,5,3,5,3,5,3,2,10,b,2,p,2,i,2,1,2,e,3,d,z,3e,1y,1g,7g,s,4,1c,1c,v,e,t,6,11,b,t,3,z,5,7,2,4,17,4d,j," +
  "z,5,z,5,13,9,1f,d,a,2,e,2,6,2,1,2,a,2,e,2,6,2,1,1w,8m,a,l,b,7,p,5,2,15,2,8,1y,5,3,0,2,17,2,1,4,0,3,m," +
  "b,m,a,u,1u,i,2,1,b,l,b,p,1z,1j,7,1,1t,0,g,3,2,2,2,s,17,s,4,s,10,7,2,r,s,1h,b,l,b,i,e,h,33,20,1k,1e,e," +
  "1e,e,z,9p,15,7,1,27,s,b,0,9,l,17,h,1b,k,s,m,d,1g,1m,1,3,0,e,18,x,o,r,z,u,0,3,0,9,y,4,0,d,1b,f,3,m,0," +
  "2,0,10,h,2,o,k,1,1s,6,2,0,2,3,2,e,2,9,8,1a,13,7,3,1,3,l,2,6,2,1,2,4,4,0,j,0,d,4,4f,1g,j,3,l,2,v,1b,l," +
  "1,2,0,55,1a,16,3,11,1b,l,0,1o,16,e,0,20,q,12,6,56,17,39,1r,w,7,3,0,3,7,2,1,2,n,g,0,2,0,2n,7,3,12,h,0," +
  "2,0,t,0,b,13,8,0,m,0,c,19,k,0,j,20,7c,8,2,10,i,0,1e,t,35,6,2,1,2,11,m,0,q,5,2,1,2,v,f,0,94,i,g,0,2,c," +
  "2,x,3h,0,28,pl,2v,32,i,5f,219,2o,g,tr,i,5,33u,g6,6nu,fs,8,u,i,26,i,t,j,1b,h,3,w,k,6,i,j5,1r,3l,22,6," +
  "0,1v,c,1t,1,2,0,t,4qf,9,yd,17,8,6w8,3,2,6,2,1,2,82,g,0,u,2,3,0,f,3,9,az,1s5,2y,6,c,4,8,8,9,4mf,2c,2," +
  "1y,2,1,3,0,3,1,3,3,2,b,2,0,2,6,2,1s,2,3,3,7,2,6,2,r,2,3,2,4,2,0,4,6,2,9f,3,o,2,o,2,u,2,o,2,u,2,o,2,u," +
  "2,o,2,u,2,o,2,7,1f9,u,7,5,7a,1p,43,18,b,6,h,0,8y,t,j,17,dh,r,l1,6,2,3,2,1,2,e,2,5g,1o,1v,8,0,xh,3,2," +
  "q,2,1,2,0,3,0,2,9,2,3,2,0,2,0,7,0,5,0,2,0,2,0,2,2,2,1,2,0,3,0,2,0,2,0,2,0,2,0,2,1,2,0,3,3,2,6,2,3,2," +
  "3,2,0,2,9,2,g,6,2,2,4,2,g,3et,wyn,x,37d,7,65,3,4g1,f,5rk,g,h9,1wj,f1,15v,3t6,6,38f";
// 769 ranges
const idContinueES5OrESNextEnc =
  "1c,9,8,p,5,0,2,p,1c,0,b,0,2,0,3,0,6,m,2,u,2,cp,5,b,f,4,8,0,2,0,i,38,2,1,3,3,2,0,7,4,2,0,2,j,2,2a,2," +
  "3u,2,4,3,4l,2,11,3,0,7,14,9,18,2,0,2,1,2,1,2,0,9,q,5,3,u,a,6,21,5,2t,2,7,3,9,2,i,3,0,h,1m,3,2s,f,1h," +
  "5,0,3,0,3,19,j,r,5,a,6,n,2,5,a,21,2,3k,3,9,2,i,2,7,3,1,3,l,2,6,2,0,4,3,3,8,3,1,3,3,9,0,5,1,2,4,3,b,b," +
  "0,2,0,3,2,2,5,5,1,3,l,2,6,2,1,2,1,2,1,3,0,2,4,5,1,3,2,4,0,8,3,2,0,8,f,c,2,2,8,2,2,2,l,2,6,2,1,2,4,3," +
  "9,2,2,2,2,3,0,g,3,3,9,a,6,2,2,2,7,3,1,3,l,2,6,2,1,2,4,3,8,3,1,3,2,8,2,5,1,2,4,3,9,2,0,h,1,2,5,4,2,2," +
  "3,4,1,2,0,2,1,4,1,4,2,4,b,5,4,4,2,2,3,3,0,7,0,f,9,h,c,2,2,2,m,2,f,3,8,2,2,2,3,8,1,2,2,3,0,3,3,3,9,h," +
  "3,2,7,2,2,2,m,2,9,2,4,3,8,2,2,2,3,8,1,7,1,2,3,3,9,2,2,d,c,2,2,2,1e,2,2,2,4,6,3,8,4,3,9,b,5,2,2,2,h,4," +
  "n,2,8,2,0,3,6,4,0,5,5,2,0,2,7,7,9,3,1,e,1l,6,e,2,9,14,1,2,0,2,4,2,n,2,0,2,m,3,4,2,0,2,6,2,9,3,3,x,0," +
  "o,1,7,9,c,0,2,0,2,0,5,9,2,z,5,j,2,h,2,z,a,0,1m,21,7,25,3,11,2,0,6,0,3,16,2,98,2,3,3,6,2,0,2,3,3,14,2," +
  "3,3,w,2,3,3,6,2,0,2,3,3,e,2,1k,2,3,3,1u,3,2,a,8,f,f,h,2d,3,5,4,h7,3,g,2,p,6,22,4,a,8,l,a,l,c,j,d,c,2," +
  "2,2,1,d,2b,4,0,5,1,3,9,y,2,2,a,7,2g,8,16,6,1x,b,u,2,b,5,b,b,13,3,4,c,17,5,p,7,a,12,r,5,1q,2,s,3,a,7," +
  "9,e,0,9,d,2,f,1e,24,4,9,i,8,d,37,d,1j,9,9,4,1c,3,8,8,16,3,2,h,2,2,12,6,et,3,5,3,11,3,5,3,7,2,0,2,0,2," +
  "0,2,u,3,1g,2,6,2,0,4,2,2,6,4,3,3,5,5,c,6,2,2,6,g,1,1e,1,k,0,t,0,e,0,h,c,1g,c,5,0,4,b,i,0,5,0,3,9,2,0," +
  "3,5,7,0,2,0,2,0,2,f,3,3,6,4,5,0,i,14,22g,6c,7,8,d,11,2,0,6,0,3,1j,8,0,g,n,a,6,2,6,2,6,2,6,2,6,2,6,2," +
  "6,2,6,2,v,ee,2,q,e,2,4,3,4,5,2d,3,6,2,2m,6,16,2,2l,i,v,1d,f,e9,533,1t,h3g,1w,19,3,7g,4,r,l,1b,5,9,2," +
  "36,12,8,3,2u,3,1r,6,1,2,0,2,4,p,1h,5,0,k,1f,d,1x,b,9,7,n,4,0,2,1c,3,z,d,s,4,1s,f,a,7,u,2,1i,a,d,3,9," +
  "7,m,4,20,p,2,3,f,3,4,b,5,3,5,3,5,a,6,2,6,2,16,2,d,7,3e,2,1,3,9,7,8mb,d,m,5,1c,6it,a5,3,2x,13,6,d,4,6," +
  "b,2,c,2,4,2,0,2,1,2,1,2,2z,y,a2,j,1r,3,1h,15,b,5,f,h,f,4,1,p,2,x,4,2,3q,k,9,8,p,5,0,2,p,b,2h,4,5,3,5," +
  "3,5,3,2,10,b,2,p,2,i,2,1,2,e,3,d,z,3e,1y,1g,3t,0,3n,s,4,1c,g,0,w,v,e,t,6,16,6,t,3,z,5,7,2,4,17,4d,3," +
  "9,7,z,5,z,5,13,9,1f,d,a,2,e,2,6,2,1,2,a,2,e,2,6,2,1,1w,8m,a,l,b,7,p,5,2,15,2,8,1y,5,3,0,2,17,2,1,4,0," +
  "3,m,b,m,a,u,1u,i,2,1,b,l,b,p,1z,1j,7,1,1t,3,2,1,6,7,2,2,2,s,3,2,5,0,x,s,4,s,10,7,2,t,q,1h,b,l,b,i,e," +
  "h,33,20,1k,1e,e,1e,e,13,9,9,93,15,2,1,4,1,24,v,b,0,9,w,w,l,17,k,s,m,a,1y,w,f,a,1n,8,0,e,o,8,9,7,1g,2," +
  "9,5,3,9,z,3,0,a,1w,5,3,2,c,2,0,10,h,2,10,7,3,1r,6,2,0,2,3,2,e,2,9,8,1m,6,9,7,3,2,7,3,1,3,l,2,6,2,1,2," +
  "4,2,9,3,1,3,2,3,0,7,0,6,6,3,6,4,4,3w,22,6,9,5,3,v,1x,2,0,9,9,4n,1h,3,8,o,5,z,1s,4,0,c,9,13,1k,8,9,1j," +
  "q,3,e,5,9,7,6,56,1m,2u,21,m,7,3,0,3,7,2,1,2,t,2,1,3,8,d,9,1z,7,3,19,3,7,2,1,s,1q,9,0,9,21,4,0,j,20," +
  "7c,8,2,18,2,8,g,9,p,t,3,l,2,d,22,6,2,1,2,17,4,0,2,1,2,8,9,9,7,5,2,1,2,10,2,1,2,5,8,9,8n,m,a,g,2,14,4," +
  "4,e,9,2f,0,28,pl,2v,32,i,5f,219,2o,g,tr,h,l,33f,g6,6nu,fs,8,u,2,9,7,26,2,9,7,t,3,4,c,1i,a,3,d,9,a,k," +
  "6,i,j5,1r,3l,22,5,1k,8,g,1t,1,2,1,c,1,f,4qf,9,yd,17,8,6w8,3,2,6,2,1,2,82,g,0,u,2,3,0,f,3,9,az,1s5,2y," +
  "6,c,4,8,8,9,4,1,3mq,19,3,m,f3,4,4,5,9,7,3,6,v,3,45,2,cc,2c,2,1y,2,1,3,0,3,1,3,3,2,b,2,0,2,6,2,1s,2,3," +
  "3,7,2,6,2,r,2,3,2,4,2,0,4,6,2,9f,3,o,2,o,2,u,2,o,2,u,2,o,2,u,2,o,2,u,2,o,2,7,3,1d,e9,1i,5,1d,9,0,f,0," +
  "n,4,2,e,up,u,7,5,5y,6,2,g,3,6,2,1,2,4,6,1p,y,0,35,18,4,d,3,9,5,0,8y,u,i,1l,d3,15,kn,6,2,3,2,1,2,e,2," +
  "5g,c,6,16,23,5,9,x3,3,2,q,2,1,2,0,3,0,2,9,2,3,2,0,2,0,7,0,5,0,2,0,2,0,2,2,2,1,2,0,3,0,2,0,2,0,2,0,2," +
  "0,2,1,2,0,3,3,2,6,2,3,2,3,2,0,2,9,2,g,6,2,2,4,2,g,2lx,9,sn,wyn,x,37d,7,65,3,4g1,f,5rk,g,h9,1wj,f1," +
  "15v,3t6,6,38f,f9e9,6n";

// A decoded table: a bitmap for the BMP plus sorted astral ranges. Tables are
// decoded lazily on the first non-ASCII query.
class IdentTable {
  constructor(enc) {
    this.enc = enc;
    this.bmp = null; // Uint32Array bitmap of 0x10000 bits
    this.astral = null; // Int32Array [lo0, hi0, lo1, hi1, ...] for ranges above 0xFFFF
  }

  init() {
    const parts = this.enc.split(",");
    const bmp = new Uint32Array(0x10000 >>> 5);
    const astral = [];
    let prev = 0;
    for (let k = 0; k < parts.length; k += 2) {
      const lo = prev + parseInt(parts[k], 36);
      const hi = lo + parseInt(parts[k + 1], 36);
      prev = hi;
      const bmpHi = hi > 0xffff ? 0xffff : hi;
      for (let c = lo; c <= bmpHi; c++) bmp[c >>> 5] |= 1 << (c & 31);
      if (hi > 0xffff) astral.push(lo > 0xffff ? lo : 0x10000, hi);
    }
    this.bmp = bmp;
    this.astral = Int32Array.from(astral);
  }

  // Equivalent to Go's unicode.Is(table, codePoint)
  has(c) {
    if (this.bmp === null) this.init();
    if (c < 0) return false;
    if (c <= 0xffff) return (this.bmp[c >>> 5] & (1 << (c & 31))) !== 0;
    const a = this.astral;
    let lo = 0;
    let hi = (a.length >>> 1) - 1;
    while (lo <= hi) {
      const mid = (lo + hi) >>> 1;
      if (c < a[mid * 2]) hi = mid - 1;
      else if (c > a[mid * 2 + 1]) lo = mid + 1;
      else return true;
    }
    return false;
  }
}

const idStartES5AndESNext = new IdentTable(idStartES5AndESNextEnc);
const idContinueES5AndESNext = new IdentTable(idContinueES5AndESNextEnc);
const idStartES5OrESNext = new IdentTable(idStartES5OrESNextEnc);
const idContinueES5OrESNext = new IdentTable(idContinueES5OrESNextEnc);

// ---------------------------------------------------------------------------
// js_ident.go

// ASCII classification: 1 = identifier start (and continue), 2 = continue only
const asciiIdent = new Uint8Array(128);
for (let c = 97; c <= 122; c++) asciiIdent[c] = 1;
for (let c = 65; c <= 90; c++) asciiIdent[c] = 1;
asciiIdent[95] = 1; // _
asciiIdent[36] = 1; // $
for (let c = 48; c <= 57; c++) asciiIdent[c] = 2;

export function isIdentifier(text) {
  const n = text.length;
  if (n === 0) return false;
  // (JS-only: ASCII fast path, the same result as the loop below)
  let c0 = text.charCodeAt(0);
  if (c0 < 0x80) {
    if (asciiIdent[c0] !== 1) return false;
    let j = 1;
    for (; j < n; j++) {
      c0 = text.charCodeAt(j);
      if (c0 >= 0x80) break;
      if (asciiIdent[c0] === 0) return false;
    }
    if (j === n) return true;
  }
  for (let i = 0; i < n; i++) {
    let c = text.charCodeAt(i);
    if (c >= 0xd800 && c <= 0xdbff && i + 1 < n) {
      const c2 = text.charCodeAt(i + 1);
      if (c2 >= 0xdc00 && c2 <= 0xdfff) {
        c = ((c - 0xd800) << 10) + (c2 - 0xdc00) + 0x10000;
        if (i === 0) {
          if (!isIdentifierStart(c)) return false;
        } else if (!isIdentifierContinue(c)) return false;
        i++;
        continue;
      }
    }
    if (i === 0) {
      if (!isIdentifierStart(c)) return false;
    } else if (!isIdentifierContinue(c)) return false;
  }
  return true;
}

export function isIdentifierES5AndESNext(text) {
  const n = text.length;
  if (n === 0) return false;
  // (JS-only: ASCII fast path, the same result as the loop below)
  let c0 = text.charCodeAt(0);
  if (c0 < 0x80) {
    if (asciiIdent[c0] !== 1) return false;
    let j = 1;
    for (; j < n; j++) {
      c0 = text.charCodeAt(j);
      if (c0 >= 0x80) break;
      if (asciiIdent[c0] === 0) return false;
    }
    if (j === n) return true;
  }
  for (let i = 0; i < n; i++) {
    let c = text.charCodeAt(i);
    if (c >= 0xd800 && c <= 0xdbff && i + 1 < n) {
      const c2 = text.charCodeAt(i + 1);
      if (c2 >= 0xdc00 && c2 <= 0xdfff) {
        c = ((c - 0xd800) << 10) + (c2 - 0xdc00) + 0x10000;
        if (i === 0) {
          if (!isIdentifierStartES5AndESNext(c)) return false;
        } else if (!isIdentifierContinueES5AndESNext(c)) return false;
        i++;
        continue;
      }
    }
    if (i === 0) {
      if (!isIdentifierStartES5AndESNext(c)) return false;
    } else if (!isIdentifierContinueES5AndESNext(c)) return false;
  }
  return true;
}

// Note: Go decodes the text as UTF-8 here, so a lone surrogate (3 bytes of
// WTF-8) becomes three U+FFFD runes and therefore three "_" characters.
export function forceValidIdentifier(prefix, text) {
  let sb = "";

  // Private identifiers must be prefixed by "#"
  if (prefix !== "") sb += prefix;

  const n = text.length;
  let i = 0;
  let isFirst = true;
  while (isFirst || i < n) {
    let c;
    let width = 1;
    if (i >= n) {
      c = 0xfffd; // utf8.DecodeRuneInString("") returns RuneError
      width = 0;
    } else {
      c = text.charCodeAt(i);
      if (c >= 0xd800 && c <= 0xdfff) {
        const c2 = i + 1 < n ? text.charCodeAt(i + 1) : 0;
        if (c <= 0xdbff && c2 >= 0xdc00 && c2 <= 0xdfff) {
          c = ((c - 0xd800) << 10) + (c2 - 0xdc00) + 0x10000;
          width = 2;
        } else {
          // Lone surrogate: three invalid UTF-8 bytes in Go
          sb += "___";
          i++;
          isFirst = false;
          continue;
        }
      }
    }
    i += width;
    const ok = isFirst ? isIdentifierStart(c) : isIdentifierContinue(c);
    isFirst = false;
    if (ok) sb += width === 2 ? text.slice(i - 2, i) : String.fromCharCode(c);
    else sb += "_";
  }

  return sb;
}

// This does "IsIdentifier(UTF16ToString(text))" without any allocations
export function isIdentifierUTF16(text) {
  return isIdentifier(text);
}

// This does "IsIdentifierES5AndESNext(UTF16ToString(text))" without any allocations
export function isIdentifierES5AndESNextUTF16(text) {
  return isIdentifierES5AndESNext(text);
}

export function isIdentifierStart(codePoint) {
  if (codePoint < 0x80) return codePoint >= 0 && asciiIdent[codePoint] === 1;

  // All ASCII identifier start code points are listed above
  return idStartES5OrESNext.has(codePoint);
}

export function isIdentifierContinue(codePoint) {
  if (codePoint < 0x80) return codePoint >= 0 && asciiIdent[codePoint] !== 0;

  // ZWNJ and ZWJ are allowed in identifiers
  if (codePoint === 0x200c || codePoint === 0x200d) return true;

  return idContinueES5OrESNext.has(codePoint);
}

export function isIdentifierStartES5AndESNext(codePoint) {
  if (codePoint < 0x80) return codePoint >= 0 && asciiIdent[codePoint] === 1;

  // All ASCII identifier start code points are listed above
  return idStartES5AndESNext.has(codePoint);
}

export function isIdentifierContinueES5AndESNext(codePoint) {
  if (codePoint < 0x80) return codePoint >= 0 && asciiIdent[codePoint] !== 0;

  // ZWNJ and ZWJ are allowed in identifiers
  if (codePoint === 0x200c || codePoint === 0x200d) return true;

  return idContinueES5AndESNext.has(codePoint);
}

// See the "White Space Code Points" table in the ECMAScript standard
export function isWhitespace(codePoint) {
  switch (codePoint) {
    case 0x0009: // character tabulation
    case 0x000b: // line tabulation
    case 0x000c: // form feed
    case 0x0020: // space
    case 0x00a0: // no-break space

    // Unicode "Space_Separator" code points
    case 0x1680: // ogham space mark
    case 0x2000: // en quad
    case 0x2001: // em quad
    case 0x2002: // en space
    case 0x2003: // em space
    case 0x2004: // three-per-em space
    case 0x2005: // four-per-em space
    case 0x2006: // six-per-em space
    case 0x2007: // figure space
    case 0x2008: // punctuation space
    case 0x2009: // thin space
    case 0x200a: // hair space
    case 0x202f: // narrow no-break space
    case 0x205f: // medium mathematical space
    case 0x3000: // ideographic space

    case 0xfeff: // zero width non-breaking space
      return true;

    default:
      return false;
  }
}
