// Writes index.d.mts: the declarations of @types/pako 2.0.4 (the types for
// pako 2.x, a devDependency), unchanged, as an ES module.
// usage: node packages/fast-pako/tools/gen-types.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = join(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(join(here, "package.json"));
const typesDir = dirname(require.resolve("@types/pako/package.json"));
const { version } = JSON.parse(readFileSync(join(typesDir, "package.json"), "utf8"));
if (version !== "2.0.4") throw new Error("expected @types/pako 2.0.4, found " + version);
const src = readFileSync(join(typesDir, "index.d.ts"), "utf8").replace(/\r/g, "");
const HEAD = "export = Pako;\nexport as namespace pako;\n";
if (!src.startsWith(HEAD)) throw new Error("unexpected @types/pako index.d.ts");
const body = src.slice(HEAD.length);
const names = ["constants", "FlushValues", "StrategyValues", "ReturnCodes", "DeflateOptions", "DeflateFunctionOptions", "InflateOptions", "InflateFunctionOptions",
  "Header", "Data", "Uint8ArrayReturnType", "deflate", "deflateRaw", "gzip", "inflate", "inflateRaw", "ungzip", "Deflate", "Inflate"];
for (const n of names) if (!new RegExp(`\\b(enum|type|interface|function|class) ${n}\\b`).test(body)) throw new Error("missing " + n);

writeFileSync(
  join(here, "index.d.mts"),
  `// Types for @r1ck404/fast-pako: the declarations of @types/pako 2.0.4 (the
// types for pako 2.x; MIT, Copyright (c) Microsoft Corporation and the
// DefinitelyTyped contributors Caleb Eggensperger, Muhammet Öztürk and
// Thibault Poisson), unchanged, as an ES module: the namespace is the default
// export (\`import pako from "pako"\`, \`pako.DeflateOptions\`) and each member
// is also a named export (\`import { ungzip } from "pako"\`).
// Generated by tools/gen-types.mjs. Do not edit.
${body.trimEnd()}

export default Pako;
${names.map((n) => `export import ${n} = Pako.${n};`).join("\n")}
`,
);
console.log("wrote index.d.mts");
