// Builds the JavaScript the packages ship from their TypeScript sources:
// every packages/**/X.mts / X.cts / X.ts (not .d.ts) becomes X.mjs / X.cjs /
// X.js next to it, with the type annotations replaced by whitespace
// (ts-blank-space). Nothing else changes: the code, the comments and every
// line and column are the source's, so the shipped JavaScript runs exactly
// as the hand-written JavaScript did. Syntax that would need code generation
// (enums, namespaces, parameter properties, ...) is an error here (and in
// tsc, via erasableSyntaxOnly).
// The generated files are committed (packages publish and test from the
// tree as before); `--check` fails when one is out of date.
// usage: node tools/ts-build.mjs [--check | --watch]
import { readFileSync, writeFileSync, readdirSync, existsSync, watch } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import tsBlankSpace from "ts-blank-space";

export const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SKIP = new Set(["node_modules", "rust", "target", ".scratch"]);
const OUT_EXT = { ".mts": ".mjs", ".cts": ".cjs", ".ts": ".js" };

/** [source, output] pairs, relative to the repository root */
export function sources(dir = join(root, "packages"), out = []) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (SKIP.has(e.name)) continue;
    const p = join(dir, e.name);
    if (e.isDirectory()) sources(p, out);
    else if (!/\.d\.[cm]?ts$/.test(e.name)) {
      const m = e.name.match(/\.(mts|cts|ts)$/);
      if (m) out.push([relative(root, p), relative(root, p.slice(0, -m[0].length) + OUT_EXT[m[0]])]);
    }
  }
  return out;
}

/** the JavaScript for one TypeScript source */
export function compile(rel, text) {
  const errors = [];
  const js = tsBlankSpace(text, (node) => errors.push(node));
  if (errors.length) {
    const lines = errors.map((n) => {
      const sf = n.getSourceFile();
      const { line, character } = sf.getLineAndCharacterOfPosition(n.getStart(sf));
      return `  ${rel}:${line + 1}:${character + 1}: ${n.getText(sf).split("\n")[0].slice(0, 80)}`;
    });
    throw new Error(`syntax that is not erasable (it would change the JavaScript):\n${lines.join("\n")}`);
  }
  const src = rel.split(sep).join("/").split("/").pop();
  return `${js}${js.endsWith("\n") ? "" : "\n"}// generated from ${src} by tools/ts-build.mjs; edit that file\n`;
}

// .gitattributes: the generated files are collapsed in GitHub diffs
const GA_BEGIN = "# begin generated by tools/ts-build.mjs";
const GA_END = "# end generated by tools/ts-build.mjs";
function gitattributes(outs) {
  const file = join(root, ".gitattributes");
  const cur = existsSync(file) ? readFileSync(file, "utf8") : "";
  const block = [GA_BEGIN, ...outs.map((o) => o.split(sep).join("/") + " linguist-generated=true"), GA_END].join("\n");
  const i = cur.indexOf(GA_BEGIN), j = cur.indexOf(GA_END);
  const next =
    i >= 0 && j > i
      ? cur.slice(0, i) + block + cur.slice(j + GA_END.length)
      : (cur ? cur.replace(/\n*$/, "\n\n") : "") + block + "\n";
  return { file, cur, next };
}

function build(check) {
  const stale = [];
  let n = 0;
  const pairs = sources();
  const ga = gitattributes(pairs.map(([, out]) => out).sort());
  if (ga.cur !== ga.next) {
    if (check) stale.push(".gitattributes");
    else writeFileSync(ga.file, ga.next);
  }
  for (const [src, out] of pairs) {
    const js = compile(src, readFileSync(join(root, src), "utf8"));
    const cur = existsSync(join(root, out)) ? readFileSync(join(root, out), "utf8") : null;
    n++;
    if (cur === js) continue;
    if (check) stale.push(out);
    else writeFileSync(join(root, out), js);
  }
  return { n, stale };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.includes("--check")) {
    const { n, stale } = build(true);
    if (stale.length) {
      console.log(`out of date (run node tools/ts-build.mjs):\n  ${stale.join("\n  ")}`);
      process.exit(1);
    }
    console.log(`ts-build: ${n} generated files up to date`);
  } else {
    console.log(`ts-build: ${build(false).n} files`);
    if (args.includes("--watch")) {
      let timer = null;
      watch(join(root, "packages"), { recursive: true }, (_, f) => {
        if (!f || !/\.[cm]?ts$/.test(f) || /\.d\.[cm]?ts$/.test(f)) return;
        clearTimeout(timer);
        timer = setTimeout(() => {
          try {
            console.log(`ts-build: ${build(false).n} files (${f})`);
          } catch (e) {
            console.log(e.message);
          }
        }, 50);
      });
      console.log("watching packages/ for .ts/.mts/.cts changes");
    }
  }
}
